### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by ezequias** [puikinsh/gentelella#1]
Hi, this template is just perfect.

I would like to translate it to Portuguese, my mother language.

Is the best way to fork and translate or is there any I18n files I can translate?

Best regards
Ezequias Rocha
Brazil

**Comment by amutisya** [comment]
Hello..

Thanks for the interest, you're free to folk and translate to Portuguese
and even contribute changes on any bugs you notice. Hope this gets to make
it as helpful to as many people as possible..

--
Regards,
Anthony Mutisya

On Mon, May 18, 2015 at 6:57 PM, Ezequias Rodrigues da Rocha <
notifications@github.com> wrote:

> Hi, this template is just perfect.
>
> I would like to translate it to Portuguese, my mother language.
>
> Is the best way to fork and translate or there is any I18n files I can
> translate?
>
> Best regards
> Ezequias Rocha
> Brazil
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kimlabs/gentelella/issues/1>.
>



-- 
Warm regards,
Anthony Mutisya,
Web/Mobile Developer.

**Comment by ezequias** [comment]
@puikinsh I don't know if you noticed but on my fork the application is already translated to Portuguese.

Sincerely
Ezequias Rocha
