### ISSUE TITLE
form_upload.html  upload more file well Display is not normal

### ISSUE THREAD

**Issue by fmpoffice** [puikinsh/gentelella#108]
![123123](https://cloud.githubusercontent.com/assets/11001031/14805482/de4338f0-0b9e-11e6-9303-bc65b0cab688.png)
Display is not normal

**Comment by christianesperar** [comment]
This is  because of the declaration of inline style 'height'. Fix is on PR https://github.com/puikinsh/gentelella/pull/109

**Comment by fmpoffice** [comment]
谢谢
