### ISSUE TITLE
How to collapse side menu on start?

### ISSUE THREAD

**Issue by bthppong** [puikinsh/gentelella#112]
I already try
Method#1: Set body class "nav-md" > "nav-sm"
Method#2: $('#menu_toggle').click(); on document ready

Menu is collapsed but side menu did work correct. It's still slide down.

Please advise.

**Comment by christianesperar** [comment]
Method 1 (changing the nav-md from nav-sm) will work, did you do it on the latest one?

**Comment by bthppong** [comment]
@christianesperar I already try. It's ok, the menu collapsed but when I click on menu icon, child menu still slide down (normal, they should show on right side).
 
Thank

**Comment by christianesperar** [comment]
Did you use the latest gentelella?

**Comment by bthppong** [comment]
@christianesperar I'm not sure but I downloaded from here for 5 week ago.

**Comment by christianesperar** [comment]
The demo is updated now. Can you try again?

**Comment by bthppong** [comment]
@christianesperar Thank :)
PS. Do you have advise if I want only update it? Just use new css & js?

**Comment by christianesperar** [comment]
Just js but it's better if you update both files to benefit on new updates.

**Comment by etchkay** [comment]
Method 1 is a fail on the latest, as using nav-sm starts it collapsed but it displays the sub-menu all the time.
Method 2 worked just fine for me, I did change put click trigger before every other form, table, etc initializations as then the page length was initialized as wider.
Thanks

**Comment by nelsonluiz** [comment]
@bthppong 

Please, can you show the hole code you've done.... I've got the same problem and I dont know how to solve...

**Comment by kunbero** [comment]
$(function() {
	$('body').removeClass('nav-md').addClass('nav-sm');
	$('.left_col').removeClass('scroll-view').removeAttr('style');
	$('#sidebar-menu li').removeClass('active');
        $('#sidebar-menu li ul').slideUp();
});

i use this code and it works, can yout try?

**Comment by nelsonluiz** [comment]
Fantastic, it's working... really good... thanks.

**Comment by emads3** [comment]
@kunbero works but not the radical solution and has some problems like it's considered extra processing, and if you have a dom structure that is constructed based on the width of the page it would be a problem

**Comment by kapyaar** [comment]
I am trying to achieve the same result (collapse the sidemenu on start). I tried the nav-sm and it works except if you open the page on a mobile device, then the collapsed nav bar still shows, where as I would like it to be hidden on narrow view ports. Anyone solved this?

**Comment by sreedevness** [comment]
If someone's still trying to achieve this, here is the way to go:

```
function menuToggle(){
  if ($('body').hasClass('nav-md')) {
    $("#sidebar-menu").find('li.active ul').hide();
    $("#sidebar-menu").find('li.active').addClass('active-sm').removeClass('active');
  } else {
    $("#sidebar-menu").find('li.active-sm ul').show();
    $("#sidebar-menu").find('li.active-sm').addClass('active').removeClass('active-sm');
  }
  $('body').toggleClass('nav-md nav-sm');
  setHeight();
}

function setHeight(){
  $('.right_col').css('min-height', $(window).height());
  var bodyHeight = $('body').outerHeight();
  var footerHeight = $('body').hasClass('footer_fixed') ? -10 : $('footer').height();
  var leftColHeight = $('.left_col').eq(1).height() + $('.sidebar-footer').height();
  var contentHeight = bodyHeight < leftColHeight ? leftColHeight : bodyHeight;
  contentHeight -= $('.nav_menu').height() + footerHeight;
  $('.right_col').css('min-height', contentHeight);
}

```

Add the two functions and call the menuToggle(); function on $(document).ready();

**Comment by tomtheone** [comment]
I do not get how to apply your sample provided. Could you explain how to handle the last info?

> Add the two functions and call the menuToggle(); function on $(document).ready();

**Comment by sreedevness** [comment]
@tomtheone copy the functions in snippet i've provided. once that's done.

just add the following code:

$(document).ready(function(){
 menuToggle();
});

This will call the function that you've already copied which toggles the menu on document ready event. (jQuery)

**Comment by KlinGonVI** [comment]
Hi, 

I have a ul with li menu items has children. I would like open specific UL when page load! Anyone can help me ?

thanks

**Comment by DarkyRobin** [comment]
can we store a session that if the menu collapses, it will remain collapse on the other menu selection?

**Comment by luaugii** [comment]
Hola despues de tanto buscar en muchos foros, funciono para mi, cuando ejecute 
`// Comenzar con Barra de Menu Small
  $("#menu_toggle").click();` al Final del `$(document).ready(function(){ ... })` mi explicación es que se debe cargar todo el DOM y despues ejecutar el click... así, los submenus también no se desplegaran...

**Comment by ghostyared** [comment]
$(document).ready(function() {
          $('#menu_toggle').click();
  });
