### ISSUE TITLE
Form Action Problem

### ISSUE THREAD

**Issue by diogomacedo92** [puikinsh/gentelella#113]
Dear Friends,
I have a Smart Wizard wich have some <form> (one for each wizard "step")
Now, i need to send it all to a new .php page. I´m facing some issues with that.

I already tried something like:

<form method="POST" action="new-page.php">

  *Smart wizard content with all that <form> inside. 

</form>

But it changes all the field positions inside Smar Wizard.
For example: 
Name: ....
Age: ..

Seems like this:

Name:... Age...

Can you help me please?

**Comment by c0mrade** [comment]
First of all what are you even asking, please re-read your question, while pretending not to know anything about your problem, pretty sure you'll be confused like everyone else is here.

Also what do you mean by some issues, are you expecting us to try everything out until some of us encounters some issue, or how does it work in your head when you say some issues, how exactly are you expecting someone to identify your exact problem and suggests a fix. Or are you expecting that there is a single fix for all possible problems? I m pretty excited to learn more about your thought process

**Comment by diogomacedo92** [comment]
Hello c0mrade ,
Thank you for your comment. 

I appologize for the confusion.  I will try to explain it better. 

What I mean is: 
- I have a smart wizard. And each step of it have a <form> tag. 
Example (index.php): 
  <div id="step-1">
                      <form class="form-horizontal form-label-left">
                            <input type="text" id="somethinghere" required="required" class="form-control col-md-7 col-xs-12">
   <input type="text" id="somethinghere" required="required" class="form-control col-md-7 col-xs-12">
                      </form>
</div>

<div id="step-2">
                      <form class="form-horizontal form-label-left">
                                     <input type="text" id="somethinghere" required="required" class="form-control col-md-7 col-xs-12">
   <input type="text" id="somethinghere" required="required" class="form-control col-md-7 col-xs-12">
                     </form>
</div>

Now i need to send all the input information to: check.php
How can i do this? 

I hope you understand better now. Thanks :)

**Comment by christianesperar** [comment]
I think this is a question for php and not gentelella but a good starting point to solve your problem is http://www.formget.com/form-validation-using-php/
