### ISSUE TITLE
first opend general_elements.html  tab show Abnormal！

### ISSUE THREAD

**Issue by fmpoffice** [puikinsh/gentelella#115]
first opend general_elements.html  tab show Abnormal！
![fs1](https://cloud.githubusercontent.com/assets/11001031/14934842/9c80cc34-0ef0-11e6-9761-581fb0c9006a.png)

![t2](https://cloud.githubusercontent.com/assets/11001031/14934855/e279653e-0ef0-11e6-987e-60f71d2b503e.png)

**Comment by fmpoffice** [comment]
style="border-color: #ddd;"

**Comment by christianesperar** [comment]
Fix is on PR https://github.com/puikinsh/gentelella/pulls
