### ISSUE TITLE
Accordion / Collapse not working

### ISSUE THREAD

**Issue by DarkSlash** [puikinsh/gentelella#116]
Im implementing Gentelella on Yii2 and I have a problem with the collapse / accordion. Im manage the collapse panel to collapse by putting 

`/** ******  collapse panel  *********************** **/
// Close ibox function
$('.close-link').click(function () {
    var content = $(this).closest('div.x_panel');
    content.remove();
});

// Collapse ibox function
$('.collapse-link').click(function () {
    var x_panel = $(this).closest('div.x_panel');
    var button = $(this).find('i');
    var content = x_panel.find('div.x_content');
    content.slideToggle(200);
    (x_panel.hasClass('fixed_height_390') ? x_panel.toggleClass('').toggleClass('fixed_height_390') : '');
    (x_panel.hasClass('fixed_height_320') ? x_panel.toggleClass('').toggleClass('fixed_height_320') : '');
    button.toggleClass('fa-chevron-up').toggleClass('fa-chevron-down');
    setTimeout(function () {
        x_panel.resize();
    }, 50);
});
/** ******  /collapse panel  *********************** **/`

on script loaded at the bottom. So the collapse panel collapse when you click on the icon. But the accordion inside it doesn't work. I tried to put this code on the bottom, on the top, before collapse, after collapse, and nothing happens, what else I need to add for the accordions to load?

`/** ******  Accordion  *********************** **/

$(function () {
    $(".expand").on("click", function () {
        $(this).next().slideToggle(200);
        $expand = $(this).find(">:first-child");

        if ($expand.text() == "+") {
            $expand.text("-");
        } else {
            $expand.text("+");
        }
    });
});

/** ******  Accordion  *********************** **/`

Here's a list of scripts I load in Yii2:
js/custom.js,
'js/moment/moment.min.js',
'js/nicescroll/jquery.nicescroll.min.js',
'js/datepicker/daterangepicker.js',
'js/custom2.js'

**Comment by christianesperar** [comment]
Is this solve? Please reopen it not.
