### ISSUE TITLE
Make demo site sync on every update/release

### ISSUE THREAD

**Issue by christianesperar** [puikinsh/gentelella#117]
I think it's better if demo site will sync on every update/release since some issues reported comes on the demo site. I think they copy the scripts of the demo site which is outdated and contains some bug already fix on our repo.

**Comment by huglester** [comment]
Good idea. Since we often refer to the DEMO examples, copy code or something
If it is your hosted server, I think it would be pretty easy to send a trigger to the server, when there is update on master, so your website just run git pull... so Simply create a cron to git pull every N minutes?

**Comment by christianesperar** [comment]
We can put a hookings on our repo or just use continous integration tools..... maybe Travis?
