### ISSUE TITLE
setContentHeight() not working without a link on side bar menu

### ISSUE THREAD

**Issue by ThiagoHara** [puikinsh/gentelella#119]
Hi i was facing a problem with the content height when opened a link that does not exist on sidebar-menu, so i modified the custom.js to execute the function  setContentHeight() on the document.ready().

There is a reason to not run this function on ready()?

Below, on the last line is the change... 
```

// Sidebar
$(document).ready(function() {
    // TODO: This is some kind of easy fix, maybe we can improve this
    var setContentHeight = function () {
        // reset height
        $RIGHT_COL.css('min-height', $(window).height());

        var bodyHeight = $BODY.height(),
            leftColHeight = $LEFT_COL.eq(1).height() + $SIDEBAR_FOOTER.height(),
            contentHeight = bodyHeight < leftColHeight ? leftColHeight : bodyHeight;

        // normalize content
        contentHeight -= $NAV_MENU.height() + $FOOTER.height();

        $RIGHT_COL.css('min-height', contentHeight);
    };
    setContentHeight();
```

**Comment by christianesperar** [comment]
Thanks! Here is the PR for this https://github.com/puikinsh/gentelella/pull/173

**Comment by sterlingdiazd** [comment]
I was having the same problem. After debugging for a while, I found the solution. I don't know what happen because my page was ok, and then this error appear.

// recompute content when resizing
$(window).smartresize(function () {
// setContentHeight(); //JUST NEED TO COMMENT THIS AND VOILÁ!
});
