### ISSUE TITLE
JqueryUI sortable conflict

### ISSUE THREAD

**Issue by trawen** [puikinsh/gentelella#120]
I added a plugin Jquery Sortable. I do the sorting grid in this example: http://jqueryui.com/sortable/#display-grid

and when you drag elements of the first row are lower, they fly up high.

If you disable file **custom.css** then everything works fine. So I think the problem in css.

Please help solve the problem.

**Comment by christianesperar** [comment]
Can you add more details? I tried it on a plane gentelella page and all seem working as expected
