### ISSUE TITLE
updated select2

### ISSUE THREAD

**Issue by huglester** [puikinsh/gentelella#123]
Hello,

when I switched to select2 (4.0.2), I needed to add this for it to work correctly:
.select2-hidden-accessible {
    display: none;
}

**Comment by christianesperar** [comment]
Hi do you mean you use bower update?

**Comment by huglester** [comment]
Yes, I have switched to bower  dependencies.

But I think if we solve this #117 then probably such scenarios could be catched and fixed earlier..
We also cold try switching the /production stuff to bower components also.

**Comment by christianesperar** [comment]
Oh so it's already fixed on that update? That's cool!
