### ISSUE TITLE
On Sidebar nav of nav-sm as default, Child menu is not workable

### ISSUE THREAD

**Issue by geetsam** [puikinsh/gentelella#124]
On sidebar of nav-sm which i set as default, the child menus or the submenu goes missing. What's the best possible solution?

**Comment by christianesperar** [comment]
Did you try this on the latest gentelella?

**Comment by christianesperar** [comment]
Is this solve? Please reopen it not.

**Comment by geetsam** [comment]
Yeap it worked. Thanks for suggesting to update latest gentelella.
