### ISSUE TITLE
Profile Picture Issue

### ISSUE THREAD

**Issue by CodeAhmed** [puikinsh/gentelella#125]
The Profile picture doesnt get uploaded. What changes needs to be incorporated to do the same.

**Comment by christianesperar** [comment]
Hi, uploading picture does not cover by the themes itself. What server side language do you use?

**Comment by CodeAhmed** [comment]
ASP Dot.Net C#

**Comment by CodeAhmed** [comment]
What additional changes do i need to implement to make it work.

**Comment by christianesperar** [comment]
I don't know how asp works but solution can found by searching on a search engine and the template has nothing to do with it. Maybe try searching "asp .net upload file" on google.

**Comment by CodeAhmed** [comment]
I appreciate your response, however the code in HTML supports uploading. If we click on upload button it does ask file to upload. I just need to confirm whether it has anything with the script file "crop", which might be doing something.
