### ISSUE TITLE
Prevent Notification Box From Closing When Clicking Inside It

### ISSUE THREAD

**Issue by Especially** [puikinsh/gentelella#127]
How do I prevent the notification box in the toolbar from closing? I mimicked the element in order to create an easy to access form and so when I click the select and text box on the inside, the box closes. However, I still want to be able to close the box when clicking outside of it

**Comment by Especially** [comment]
^ Specifically when using the select box element

**Comment by christianesperar** [comment]
Is this solve? Please reopen it not.
