### ISSUE TITLE
Side bar sub menu FLAPPING

### ISSUE THREAD

**Issue by anandpujari** [puikinsh/gentelella#128]
Side nav bar sub menu's list are flapping in mobile and in tab....

**Comment by christianesperar** [comment]
What do you mean by flapping? Did you try this on the current gentelella version and not the demo?

**Comment by anandpujari** [comment]
When i click on menu in tab or in mobile it will open sub menus drop down and it will close immediately, it is not letting to do any further action.

**Comment by fennellgb23** [comment]
Check to make sure you are not loading 'js/custom.js' multiple times.  I had this happen and found I was loading it more than once on a page.

**Comment by christianesperar** [comment]
This is the fix for this problem https://github.com/puikinsh/gentelella/pull/172
