### ISSUE TITLE
Integration with AngularJS

### ISSUE THREAD

**Issue by aayusharora** [puikinsh/gentelella#134]
Hi , I have to use this template with Angular project , it includes jquery . What is the best way to integrate the modules.
This is my directory structure of existing project.
![directory](https://cloud.githubusercontent.com/assets/12194719/15100270/c05d050a-158a-11e6-811f-93d2ef1a874a.png)
Kindly help :)

**Comment by paulinhowoox** [comment]
Nice work, tks for this!

**Comment by christianesperar** [comment]
It seems your question is for AngularJs specific question and not for gentelella.
