### ISSUE TITLE
Form - Little Help

### ISSUE THREAD

**Issue by diogomacedo92** [puikinsh/gentelella#135]
I´m trying to insert the form values in Database, but I can´t finish it well..

What I have:

Page 1: Contains the smartwizard with <form method="post" action="new_user.php"> and in the bottom of the page
             `<script type="text/javascript">
function submitform()
{
  document.new_user.submit();
}
</script>`

Then when i create my "new_user.php" page i need to check if the Smartwizard Finish button was clicked before I insert the values in DB. How can I do that?

Thanks in Advance

**Comment by samuelrbo** [comment]
You can use jquery to manipulate the form data before submit it to the server page.

```html
<form name="my_form" id="myForm" onsubmit="return false;">
    <input type="text" name="form_field_1" value="" />
    <input type="text" name="form_field_2" value="" />
    ...
    <button type="submit" id="btnSubmit">Send</button>
</form>
```

And the JS in the end of the page

```js
jQuery(document).ready(function(){
    jQuery("btnSubmit").click(function(event){
        event.preventDefault();

        // Do what do you want
        // If you want a AJAX Submit
        var formData = jQuery("#myForm").serialize();
        jQuery.ajax('the/server/page', {
            type: "POST",
            data: formData,
            dataType: "json",
            success: function(response) {
                // do something
            }
        });
    });
});
```

In server side you can do something like it:

```php
<?php

// Single 
$field1 = $_POST['form_field_1'];
$field2 = $_POST['form_field_2'];

....

// If you ave a validate class
$form = new MyFormValidationClass($_POST);

if ( $form.validate() ) {
    // do something
}

// The jQuery AJAX submit is expecting some JSON return you can send in PHP this way

echo json_encode(array(
    'status' => 'success or error',
    'data' => 'some data to manipulate in form after the submition'
));

```

I hope it help you.

**Comment by diogomacedo92** [comment]
Hi samuelrbo,
Thank you very much for your help!

**Comment by christianesperar** [comment]
Is your problem solve? You can see the documentation of the libraries that we use on the wizard https://github.com/mstratman/jQuery-Smart-Wizard

**Comment by diogomacedo92** [comment]
Dear christianesperar,
It´s ok now. Thank you both for your help! 

Best Regards,
Diogo
