### ISSUE TITLE
CodeMirror is not displaying properly

### ISSUE THREAD

**Issue by microvb** [puikinsh/gentelella#138]
When using CodeMirror in the right panel, it is being hidden when the TextArea element is hidden.  When the TextArea is forced to `display: block;` after CodeMirror has been initialized, CodeMirror shows up correctly.

Expected result :  When using CodeMirror to replace a TextArea element, the TextArea element should be hidden and collapsed, and CodeMirror should be visible.

I have an issue open on [stackoverflow](http://stackoverflow.com/questions/37107120/codemirror-vanishes-when-it-hides-the-textarea-it-is-hooked-into-in-gentelella-t) which is more in depth on how to reproduce this issue reliably. (and also created the `Gentelella` tag for future stackoverflow questions and/or if you decide to put up a wiki over there).

**Comment by christianesperar** [comment]
I tried the basic example of CodeMirror and it work as expected. Can you try to comment out feautures little by little maybe one of this is conflicting with gentelella

**Comment by microvb** [comment]
I presume you mean using less modules in CodeMirror ?   The only module I believe that would be possible to conflict (or highest probability) would be the search/replace feature.   Were you able to test using the directions (and build + modules of CodeMirror) as I put on the StackOverflow question ?

**Comment by christianesperar** [comment]
Add div with class **x_content**
