### ISSUE TITLE
Data Table Excel download not working

### ISSUE THREAD

**Issue by thr27** [puikinsh/gentelella#139]
There is a problem in datatables sample with the Excel download butto not working. Console shows an error "d.createObjectURL is not a function". According to https://datatables.net/forums this is caused by gloablly define variable "URL" somewhere in the page. in custom.js there is a definiton for "var URL" ... chaning this to "var _URL" and all references fixes the error ...

var _URL = window.location.href.split('?')[0],
    $BODY = $('body'),
    $MENU_TOGGLE = $('#menu_toggle'),

**Comment by christianesperar** [comment]
Nice catch! PR is https://github.com/puikinsh/gentelella/pull/140. Next time make a PR for your awesome discovery 👍
