### ISSUE TITLE
Less files

### ISSUE THREAD

**Issue by benjhoo** [puikinsh/gentelella#142]
Hi,
is it possible to provide, in the sources, the less files (or sass) used to generate 'custom.css' ?
In order to contribute to this great project.

Thanks.

**Comment by christianesperar** [comment]
To tell you the truth the Less file is just identical copy of css (cheat) but migration to a css preprocessors (I prefer sass) is on a roadmap but if you want you can start the awesomeness now! That would be awesome!

**Comment by benjhoo** [comment]
Ok.
Let's go ! I start working on it then ;-)

**Comment by caiohdf** [comment]
@christianesperar is there any sort of "roadmap view" so we can track it down all the changes coming on the road?

**Comment by Neo478** [comment]
@benjhoo I was wondering the same thing! May the force be with you! And if you need any help call me :D

**Comment by christianesperar** [comment]
I already made PR for gulp build for preparation for this but this still the original sass file. Feel free to modularize it!

**Comment by AngryElephant** [comment]
Hi, any news about the sass file ?

**Comment by benjhoo** [comment]
Hi,
I start making the sass files based on css.
For the moment I've only done the main structure (header, left column, right column, footer) due to a lack of time.

You could find my fork here : https://github.com/benjhoo/gentelella/tree/master
