### ISSUE TITLE
Content does not fit appropriately as per the side Navigation and shows theme colour(blue)

### ISSUE THREAD

**Issue by CodeAhmed** [puikinsh/gentelella#143]
The content section when gets deleted or if it is shorter as compared to side Navigation list then the page looks pretty bad as content section of the page will have page colour and the remaining page will have the side navigation bar colour.

**Comment by christianesperar** [comment]
Yup, that's right. May I know why you want to delete the right_col? This needs to be there.

**Comment by christianesperar** [comment]
Is this solve? Please reopen it not.
