### ISSUE TITLE
Sidebar Nav breaking with query strings

### ISSUE THREAD

**Issue by fennellgb23** [puikinsh/gentelella#147]
If you add a query string to the end of a page that is part of the sidemenu, the menu will collapse and not show the menu selected.  (example using the page 'production/form.html', the menu on the left will show that 'General Form' is selected.  If you add ?test=true to the end of the url, the nav collapses and does not show the General menu open with the "General Form" option selected.

**Comment by christianesperar** [comment]
The demo is a bit outdated, try to use the later version on master where it fix
