### ISSUE TITLE
"Create Account" does not work properly!

### ISSUE THREAD

**Issue by semihkiroglu** [puikinsh/gentelella#158]
Hi. Sorry for bad English. I'm clicking "Create Account" link on login page. Create Account page is coming but hidden. Login page isn't hidding but login textboxes aren't clickable, create account textboxes are clickable and selectable (ghost).

Location: https://sistem.izubilisim.org/template/login.html
Tested on Chrome and Edge

**Comment by bhasinmohit** [comment]
Am also facing same issue. Any suggestions?

**Comment by christianesperar** [comment]
What do you need to achieve? Is it to redirect on new page or to show a modal. This is because you supplied an anchor links without any event embedded.

**Comment by semihkiroglu** [comment]
Demo does work properly but master branch does not work. I think some problems available on master branch and I want only tell to you.

**Comment by christianesperar** [comment]
What problem? You mean there is no functionalities? This is intended since you are the one who will develop this.

**Comment by bhasinmohit** [comment]
just to elaborate on issue.......click on "Create Account" on login.html is not working in the latest template version uploaded. Functionality we have to implement but like in demo click should animate to switch between modals #toregister & #tologin.

**Comment by christianesperar** [comment]
I already send a PR for this on #164

**Comment by semihkiroglu** [comment]
Thanks to you :)

2016-05-22 19:36 GMT+03:00 Christian Esperar <notifications@github.com>:
