### ISSUE TITLE
Wide tables looks streches outside background

### ISSUE THREAD

**Issue by asio** [puikinsh/gentelella#16]
This is how the demo page (http://demo.kimlabs.com/gentelella/production/tables_dynamic.html) looks like in Safari on an iphone.

![gentelella-tables-view](https://cloud.githubusercontent.com/assets/289876/9552411/21e59684-4db8-11e5-8a5d-abe0b45128cf.PNG)

**Comment by amutisya** [comment]
Hello..

Noted working on fixing that.. Thank you

On Fri, Aug 28, 2015 at 8:09 PM, Marcel Asio <notifications@github.com>
wrote:

> This is how the demo page (
> http://demo.kimlabs.com/gentelella/production/tables_dynamic.html) looks
> like in Safari on an iphone.
>
> [image: gentelella-tables-view]
> <https://cloud.githubusercontent.com/assets/289876/9552411/21e59684-4db8-11e5-8a5d-abe0b45128cf.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kimlabs/gentelella/issues/16>.
>



-- 
Warm regards,
Anthony Mutisya,
Web/Mobile Developer.

**Comment by BlineHodd** [comment]
There is a easy way to solve this using ScrollX on datatables. https://datatables.net/reference/option/scrollX

**Comment by Maraket** [comment]
You don't even have to do that, you can wrap the table in a div with class ".table-responsive", as this is included from the bootstrap css as per http://getbootstrap.com/css/#tables-responsive (this is for bootstrap 3). A proper fix would be more suitable in my opinion, simply as scrolling on mobile devices is a  pain, and this falls over at almost all resolutions smaller then the table.

**Comment by Maraket** [comment]
I should clarify I am not looking to criticize this for the creator, as he has made a good template, I just wanted to clarify that the table is affected by more then just safari and it seems when the table shrinks beyond about 1000px it seems

**Comment by Maraket** [comment]
Oh I should also put to fix the issue, in one of the css files change the table-layout: fixed; and this should restrain the table to its container I believe

**Comment by puikinsh** [comment]
Responsive table option have been available for a while now and you can see it [here](https://colorlib.com/polygon/gentelella/tables_dynamic.html).
