### ISSUE TITLE
DataTables Buttons HTML5 Do Not Work

### ISSUE THREAD

**Issue by Especially** [puikinsh/gentelella#168]
Viewing the Dynamic Tables demo page, you see that you're able to export files as a PDF and as Excel, along with other options. However, this is not made possible because the custom.js page uses the same variable (var `URL`) that the buttons.html5 uses. Read the discussion here:

https://datatables.net/forums/discussion/33460/buttons-html5-min-js-is-throwing-error-in-chrome-browser-version-45-0-2454-85-m

**Comment by christianesperar** [comment]
Can you try again with the new release? This issue is resolve a long time ago.

**Comment by christianesperar** [comment]
Demo is now updated and this problem is now fix
