### ISSUE TITLE
Options within main sidebar categories don't collapse along with everything else

### ISSUE THREAD

**Issue by patrickkerrypei** [puikinsh/gentelella#171]
(I opened a pull request explaining in detail)

Here's a picture: 
![sidebarfix](https://cloud.githubusercontent.com/assets/14530807/15625422/f97efd62-246b-11e6-9687-8f0dc0a1ddc9.PNG)

**Comment by christianesperar** [comment]
Fix is on this PR https://github.com/puikinsh/gentelella/pull/172
