### ISSUE TITLE
Login Page not show Register form when click.

### ISSUE THREAD

**Issue by t2hv33** [puikinsh/gentelella#175]
Login Page not show Register form when click #register link.
login.html

**Comment by sebastienfi** [comment]
It is missing the Bootstrap.js reference.
At the end of the document, add : 
`
      <script src="../vendor/Bootstrap/dist/js/bootstrap.min.js"></script>`

**Comment by t2hv33** [comment]
Can you post a raw source login.html, I fix follow you said but not work.

**Comment by t2hv33** [comment]
Thanks you @sebastienfi  :dancer:

**Comment by christianesperar** [comment]
I think the problem is not on bootstrap but on animate.js which is already fix on this commit https://github.com/puikinsh/gentelella/commit/b60a6c08fdcc03c70954c5ae635d5f166069ac5f
