### ISSUE TITLE
Main files out of the production dir

### ISSUE THREAD

**Issue by krzysiekpiasecki** [puikinsh/gentelella#178]
Why main css and js files are out of the production dir?

**Comment by christianesperar** [comment]
Production directory is a sample template or guide that can be use on your application. Little by little, we will move some of this assets outside production folder. Btw, I accidentally close you pr, can you open it again and put some necessary changes? Sorry.

**Comment by krzysiekpiasecki** [comment]
>> Production directory is a sample template or guide that can be use on your application

That's the point. Every front-end project should have a distribution folder which includes all required files. These files are located then on the web root.

Actually I must copy files from production and build folders and place them into asset dir on the web root
