### ISSUE TITLE
Gentelella license question

### ISSUE THREAD

**Issue by guidoeffe** [puikinsh/gentelella#18]
Gentelella looks to have a MIT license but in documentation I read ".... full featured admin template build exclusively for sale at ThemeForest."

Can I use for deploy my project? 
Wich limitations I have?

Thank you

**Comment by amutisya** [comment]
Hey kindly ignore that..  you can use it.. Do share a link please of what
you working on would like to see at least what guys are doing with it, if
you dont mind..

Regards.,

On Wed, Sep 9, 2015 at 5:30 PM, Guido Fiamozzi <notifications@github.com>
wrote:

> Gentelella looks to have a MIT license but in documentation I read "....
> full featured admin template build exclusively for sale at ThemeForest."
>
> Can I use for deploy my project?
> Wich limitations I have?
>
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kimlabs/gentelella/issues/18>.
>



-- 
Warm regards,
Anthony Mutisya,
Web/Mobile Developer.

**Comment by BlineHodd** [comment]
This project is perfect for a personal project. In a future probably i'll sell it as part of and admin backend project. Could I do that?

**Comment by puikinsh** [comment]
@moiseslodeiro
Sorry for slow response. This repository was not maintained but I am hare to change that.  

Template is licensed under MIT license and you can read its short summary here: https://opensource.org/licenses/MIT

You can use it as part of your software/app but you need to leave a license in place that states author of this template.

**Comment by huzjakd** [comment]
I don't understand much about licenses so please excuse me if this is a stupid question.
But what does "leave a license in place" mean?
Can I delete the footer with license notification?
Is it enough just to leave license texts inside source files (.js and .css)? Like the guy says for this template here: https://github.com/ColorlibHQ/AdminLTE/issues/1077

**Comment by cristianraiber** [comment]
@huzjakd - it means you need to bundle a copy of the license (in .txt format), that mentions the author of this template with a backlink. You can remove the footer, but that license.txt file that links back to Gentelella and his creator MUST remain there.

To put it shortly: attribution is required.
