### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by fps01** [puikinsh/gentelella#180]
I think that a breadcrumbs is a very useful and comfortable interface solution for navigation.
Could you add it to theme?

**Comment by Firestorm-Graphics** [comment]
not sure breadcrumbs fit in with a dashboard, you already have persistant navigation

**Comment by fps01** [comment]
@Firestorm-Graphics left sidebar shows main categories of navigation but some category can have a big depth.
For example, `Forms list -> Some form submissions list -> Form submission details`. I want to go back to `Some form sumbissions list` with one click but i can't.

**Comment by Firestorm-Graphics** [comment]
i see what you mean, would the stock bootstrap breadcrumb not suffice ? i havent used them in this theme myself but they should take on its styling quite nicely,
