### ISSUE TITLE
Button in the modal not aligned properly

### ISSUE THREAD

**Issue by the7th** [puikinsh/gentelella#183]
I noticed that the modal's buttons are not aligned properly.

<img width="235" alt="screen shot 2016-06-02 at 12 30 38 pm" src="https://cloud.githubusercontent.com/assets/2613772/15733957/e7463fe2-28bd-11e6-9249-a53ce4a579a3.png">

**Comment by christianesperar** [comment]
Fix on this pr https://github.com/puikinsh/gentelella/pull/194
