### ISSUE TITLE
Gauge.js not found

### ISSUE THREAD

**Issue by krzysiekpiasecki** [puikinsh/gentelella#184]
Currently Bower manager is installing the package at: ``` .../gauge.js/dist/gauge.min.js ```
At the repository package is installed here: ``` .../berni/gauge.js/dist/gauge.min.js ```

Files:
- index
- index3

includes old path.

**Comment by christianesperar** [comment]
What do you mean? It looks good.

**Comment by krzysiekpiasecki** [comment]
Do clean bower install. This package doesn't have a bernii directory.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Orange network.                                                                                                                                                                                                                From: Christian EsperarSent: czwartek, 2 czerwca 2016 14:53To: puikinsh/gentelellaReply To: puikinsh/gentelellaCc: Krzysztof Piasecki; AuthorSubject: Re: [puikinsh/gentelella] Gauge.js not found (#184)What do you mean? It looks good.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by christianesperar** [comment]
Nice catch, it seems they already accept my pr so the structure is change. Anyway this is the pr for the fix https://github.com/puikinsh/gentelella/pull/185
