### ISSUE TITLE
1.3.0 missing css in production/css

### ISSUE THREAD

**Issue by bhoriuchi** [puikinsh/gentelella#186]
The custom css is now missing from production/css

**Comment by christianesperar** [comment]
Yup, it is now move on build folder since build system was introduce

**Comment by bhoriuchi** [comment]
Sorry for the late response, but using the build folder with webpack is not working. The issue is that the images directory is referenced by ../images but there is no build/images directory in the npm package. If i copy images from production/images to build then everything works fine.
