### ISSUE TITLE
Decouple HTML examples from CSS/JS/Images

### ISSUE THREAD

**Issue by marios-zindilis** [puikinsh/gentelella#189]
Hi,

To make it easier to adopt Gentelella and adapt it to projects, I think it would be useful if its own (non-vendor-provided) CSS, JS and images weren't in the `production` directory. In my tests, I created a subdirectory named `gentelella` inside `vendors` and moved those files in there. That makes it much easier to just copy `vendors` inside a new project, and use the HTML files in `production` as base examples.

If this is OK with the maintainer, I will try to send some PRs next week for this. It requires moving the files, and updating all HTML to point to the new positions.

**Comment by christianesperar** [comment]
That's right, the problem is this library is still has conflict on how gentelella is made especially the datepicker. We will focus on this part one of this days. No worries.
