### ISSUE TITLE
How to show all sub menu when one of the sub menu is selected by user?

### ISSUE THREAD

**Issue by sl5310** [puikinsh/gentelella#19]
When i clicked one sub menu and the menu bar will only show the sub menu that i clicked, how to make it show all?
i have attached the picture for you refer.

I have 2 sub-menu call "Add Department" and "Department List".
![menu1](https://cloud.githubusercontent.com/assets/13160047/9785823/c98a0ff8-57e7-11e5-9890-fbb752983900.png)

When I selected "Add Department", the menu bar cannot show the "Department List".
![menu2](https://cloud.githubusercontent.com/assets/13160047/9785824/c98e982a-57e7-11e5-919a-d42d4d6979c9.png)

**Comment by sl5310** [comment]
![picture](https://cloud.githubusercontent.com/assets/13160047/9829630/f93f5d9a-593e-11e5-8a29-6cbd5efd21df.png)
This also I have sub-menu call "Add Department" and "Department List". But it only show "Department List"

**Comment by christianesperar** [comment]
Added functionality for multilevel menu on this pr https://github.com/puikinsh/gentelella/pull/93
