### ISSUE TITLE
Angular 2 Components

### ISSUE THREAD

**Issue by dszmaj** [puikinsh/gentelella#190]
Hey,

I am using this admin for angular2 app, and will create repo with reusable components. Are you interested in translating this to angular2?

**Comment by christianesperar** [comment]
Sure, create your own repo and translate it so we can add it on the list of https://github.com/puikinsh/gentelella#gentellela-for-other-platforms-and-frameworks

**Comment by bonaparte89** [comment]
hey dszmaj.. did you have any success integrating the template into angular2?

**Comment by kmkatsma** [comment]
I've actually just published new repo where I converted the core of gentelella to Angular2.  The link is here:  https://github.com/kmkatsma/angular2-webpack-starter-gentelella

I used the angular2-webpack-starter as the basis, so you have some cool stuff for that.  I haven't converted all the pages there, but all the core is there, with index.html and inbox.html as available content items.

I'm working on a similar conversion to Aurelia, built off of their typescript webpack skeleton.
