### ISSUE TITLE
Mismatch in Page Title and project name: Gentallela Alela! <=> gentelella

### ISSUE THREAD

**Issue by thr27** [puikinsh/gentelella#197]
Hi,

I'm just curious. The project name is 'gentelella' but the samples pages greet you with 'Gentallela'.
Is this a typo, or is there another reason for this ?
Does 'Gentallela' /  'gentelella' have a real world meaning or is this just a artificial word?

PS: Thanks for the great work!

**Comment by christianesperar** [comment]
Sound like just an artificial words only. Anyway, small issue but still corrected it on this PR https://github.com/puikinsh/gentelella/pull/199
