### ISSUE TITLE
smartresize

### ISSUE THREAD

**Issue by thedanielhanke** [puikinsh/gentelella#201]
Hi,

seems like smartresize function evaluation happens on the wrong lines. 

moving the page-load-function in custom.js prevents a some-times-happening "unknown function smartresize" when clicking through forms fast.

since i dont know wether i use the js stuff wrong, i rather just mention this instead of creating a maybe useless PR. 

cheers. and thanks!

**Comment by christianesperar** [comment]
May I know where is this error occured?

**Comment by schrose** [comment]
I'm having similar issue with smartresize "unknown function" . I am fairly new to programming so I will try to give as much info as possiable. I am using this template for a ASP.NET 4.6.1 MVC web app. I am getting the error from the custom.min.js just loading up the main index page where it states : 
Line: 1
Error: Object doesn't support property or method 'smartresize'

then when I stop and debug on the custom.min.js this line is where the "Object doesn't support property or method 'smartresize'". $(window).smartresize(function(){e()})

Any direction to help solve this would be great. Also just let me know if there is any other info that I could provide that can help.

**Comment by markceron** [comment]
Hello

I solved this problem by lowering the script smartresize , because for some reason not in the application

this is the direction https://github.com/louisremi/jquery-smartresize

I hope it helps you.

**Comment by schrose** [comment]
can you explain lowering? I have been to the link you provided and not sure what that term "lowering" means.

**Comment by markceron** [comment]
Ok, soy un poco malo para el ingles, te lo explico en español.

Ve al siguiente link https://gist.github.com/Pushplaybang/3341936, copea el texto y crea un archivo js en tu proyecto y pega lo que copiastes, luego escribe en header la sintansis para que linkee el archivo.

eso hice yo y me funciono, solo que lo hice en un proyecto PHP, en ASP es un poco diferente.

saludos.

**Comment by schrose** [comment]
eso hice yo y me funciono, estoy agradecido markceron.

**Comment by markceron** [comment]
De nada

Ya sabes estoy para ayudarte, cualquier cosa me puedes escribir

Saludos

**Comment by christianesperar** [comment]
I reorder how gulp minify the scripts. Please reopen if still occur.
PR is https://github.com/puikinsh/gentelella/pull/226
