### ISSUE TITLE
Scrollable Sidebar

### ISSUE THREAD

**Issue by baweek** [puikinsh/gentelella#203]
Hi I'm currently using gentelella for a project and can't figure out how to make the sidebar scroll when a child menu is opened. 

![scroll](https://cloud.githubusercontent.com/assets/14225652/16050917/2108466c-3223-11e6-95f0-5908ab721a40.PNG)

I just want the scroll to appear and form under the child menus when I click on a parent menu. I thought a simple overflow-y in the CSS would work, but my CSS skills are failing me. Anyone able to assist?

**Comment by cmbirk** [comment]
I believe you just need to add the `menu_fixed` class to `left_col`

https://colorlib.com/polygon/gentelella/fixed_sidebar.html

**Comment by christianesperar** [comment]
@cmbirk is right. This will fix your problem
