### ISSUE TITLE
autocomplete's suggestions not aligned

### ISSUE THREAD

**Issue by armandohg** [puikinsh/gentelella#205]
When using jQuery's $.autocomplete() the suggestions seem to be floating and not aligned with the input.

See the screenshot:
![screen shot 2016-06-14 at 5 26 05 pm](https://cloud.githubusercontent.com/assets/1440573/16061865/290b1948-3255-11e6-9727-920ec8937d24.png)

**Comment by christianesperar** [comment]
Fix on this PR: https://github.com/puikinsh/gentelella/pull/217
