### ISSUE TITLE
.html files when changed to .php are not working

### ISSUE THREAD

**Issue by Softdigits** [puikinsh/gentelella#21]
Dear All,
I m calling form.html file in another file of my application after changing into form.php but it gives me an error on server.
"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, webmaster@softdigits.co.in and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request."

This works well in my local machine but not on the server.

Thanks

**Comment by Narno** [comment]
Hello, what is the problem? The message is clear: contact your administrator! :-)

**Comment by hadyfayed** [comment]
check permissions, check ownership, check path,
