### ISSUE TITLE
Bad image paths in build/css/custom.css for Bower version 1.3.0

### ISSUE THREAD

**Issue by JanCVanB** [puikinsh/gentelella#211]
I used to source `bower_components/gentelella/production/css/custom.css`, but `bower_components/gentelella/production/` moved to `bower_components/gentelella/build/` with the release of version 1.3.0.

Now, when I source `build/css/custom.css` from `bower_components/gentelella`, I get errors stating that files in `../images/` are unavailable. Should these image paths update to be `../../production/images`?

I'm not using Grunt or Gulp, just Bower and Webpack.

**Comment by christianesperar** [comment]
Is there any chance to see your changes? Thanks!

**Comment by skrosoft** [comment]
I need this change too, i cant use cssembed because of this :(
