### ISSUE TITLE
Popover tooltips not visible

### ISSUE THREAD

**Issue by gauravmak** [puikinsh/gentelella#213]
Tooltips for the the links at the bottom of the sidebar aren't being displayed as the div with class **left_col** is having bigger z-index. Observed that it crosses it at **z-index** of 1071.

Screenshot attached for reference : 
![screenshot](https://cloud.githubusercontent.com/assets/11887260/16185775/d8142cb2-36e3-11e6-8291-37241ce5eac6.png)

**Comment by christianesperar** [comment]
Fix on this PR: https://github.com/puikinsh/gentelella/pull/216
