### ISSUE TITLE
jQuery Vertical Splitter

### ISSUE THREAD

**Issue by Savsan** [puikinsh/gentelella#215]
How can I use this [jQuery Vertical Splitter](http://methvin.com/splitter/vsplitter.html)?

I haven't used jQuery library yet. I don't have an experience with it yet.
Their library is conflicting with library in your theme. Can you add split library to your theme or help me with it if it possible?

Thanks!

**Comment by christianesperar** [comment]
Probably this will not implement soon. Where do you want to put this?

**Comment by Savsan** [comment]
Hello ! I need to put it to right col.
=====
