### ISSUE TITLE
The sidebar will be cut into 2 parts when using fixed footer

### ISSUE THREAD

**Issue by xiao0bai** [puikinsh/gentelella#218]
gentelella version: 1.3.0
Broswer: Chrome 51.0.2704
Resolution: 1920*1080
Reproduce: https://colorlib.com/polygon/gentelella/fixed_footer.html
![image](https://cloud.githubusercontent.com/assets/9377596/16388932/2c1a2240-3cce-11e6-8a83-93e5c407c7d2.png)

**Comment by christianesperar** [comment]
Here is fix https://github.com/puikinsh/gentelella/pull/234
