### ISSUE TITLE
This theme seems to break ng-table

### ISSUE THREAD

**Issue by chorlick** [puikinsh/gentelella#219]
Working on a project using this theme and i need to use it with ng-table. Ng-table is a fairly popular data drive table directive for angular.js. Looks like the issue is from the css directive on line 826 in custom.css. This defines a class called filter which collides with ng-table's filter and everything looks gnarly. Think you could issue a patch to change that class name to something else to prevent the collision? 

Thanks
chorlick@gmail.com

**Comment by christianesperar** [comment]
Can you give some sample snippets?
