### ISSUE TITLE
DataTables Dynamics Not Working Php

### ISSUE THREAD

**Issue by ergungunduz** [puikinsh/gentelella#22]
The problem is that DataTables Dynamics dont work in .php pages. In .html page works good. But when change the page php it doesnt work.

**Comment by BlineHodd** [comment]
PHP is just a language to do things on the server. After that, you could print some html content. If the "raw" html file works should work too when you print the code with php ( or python, asp.. ). Probably you forget to include some javascript files or css.

**Comment by marlonrsbr** [comment]
@ergungunduz 
Did you solve it?
I have the same problem

thanks

**Comment by hero28** [comment]
Yes me too.
Please help me solve the problem.

Thanks .

**Comment by puikinsh** [comment]
I recently took over this project and I haven't yet looked into DataTables Dynamics. Will slowly push updates over the coming weeks as there are loads of things that needs to be fixed and updated.

**Comment by ergungunduz** [comment]
I solved problem different way. I have changed the some javascript file and css file(now i dont know which of them). Actually i dont use datatables dynamics full functionality but it gives me to that i want.
