### ISSUE TITLE
Table and Table-Responsive cannot be combined

### ISSUE THREAD

**Issue by PadawanTony** [puikinsh/gentelella#221]
I'm trying to combine the Tables-Design (from tables) with the Default-Example (from table dynamic).
Although the checkboxes in the first page are displayed ok, when I display more rows (by choosing 25 from the dropdown in the top left corner) then the checkboxes are not formated with the `.icheckbox_flat-green, .iradio_flat-green` class anymore.

Here is an image:
![image](https://cloud.githubusercontent.com/assets/9202029/16558187/94eed9be-41ec-11e6-98da-4e9aace8789a.png)

**Comment by christianesperar** [comment]
The problem is iCheck only apply on visible checkbox so you need to initialize it's script whenever datatable data change. I made a sample on this pr https://github.com/puikinsh/gentelella/pull/225
