### ISSUE TITLE
Which js is used for hiding site title on menu click

### ISSUE THREAD

**Issue by rishinhr** [puikinsh/gentelella#229]
Hi,
     i am replacing site title text to image for that i wanted to know from which js there is css which is hiding. 
.nav-sm .navbar.nav_title a span{
display: none;
}

**Comment by christianesperar** [comment]
What do you mean? Js just basically modify the element from **nav-md** to **nav-sm** then contains some style on respective element. To answer your question, it's on **custom.js**
