### ISSUE TITLE
Side bar menu is not responsive

### ISSUE THREAD

**Issue by sl5310** [puikinsh/gentelella#23]
Side bar menu is not responsive on phone view, cannot scroll down

**Comment by bluepenlabs** [comment]
Well I can"t scroll when even in Desktop view in side bar left menu when it is minimized

**Comment by wedotechs** [comment]
If the menu goes too long, when I expand one of the menu, i cannot see the full child menu. Please help.

**Comment by jonhylafarm** [comment]
Try using this 

.nav-sm .main_menu_side {
    overflow: auto;
    height: 400px !important;
}

**Comment by madhanminho** [comment]
Change the position property of sidebar from fixed to absolute in order to navigate all the menu items.

```
body.nav-sm .container.body .left_col {
    width: 70px;
    padding: 0;
    /*position: fixed;*/
    position:absolute;
    height: 100%;
    z-index: 200;
}
```

**Comment by christianesperar** [comment]
Just remove arrow on this pr #70

**Comment by christianesperar** [comment]
Can we close this?
