### ISSUE TITLE
Collapse div collapsed on default

### ISSUE THREAD

**Issue by Maxattar** [puikinsh/gentelella#236]
Hi, 

I have not found the mean to display the collapsible div hidden on default

Can you help me please ?

Thank you

**Comment by christianesperar** [comment]
Sorry but I don't understand the problem. Can you explain a little bit more

**Comment by dkobia** [comment]
@Maxattar if you mean the x-panels, you can do so by adding a collapsed class to the div e.g. `<div class="x_panel collapsed">` and adding the following to your custom.js

```
$('.collapsed').css('height', 'auto');
$('.collapsed').find('.x_content').css('display', 'none');
$('.collapsed').find('i').toggleClass('fa-chevron-up fa-chevron-down');
```

Alternatively you can achieve it with css (sass) via the following. Only problem is the chevron (up/down) won't face the right way.

```
.collapsed{
  height: auto;
  .x_content{
    display:none;
  }
}
```

**Comment by micksp** [comment]
two corrections, i think: 

`	$('.collapsed')
		.css('height', 'auto')
		.find('.collapse-link i').toggleClass('fa-chevron-up fa-chevron-down').end()
		.find('.x_content').css('display', 'none');`

- use .collapse-link to make sure the right icon is changed. 
- use .end() to reset the chaining to the original selector
