### ISSUE TITLE
dynamic tables, search button is not working in responsive design.

### ISSUE THREAD

**Issue by jimmibond** [puikinsh/gentelella#241]
dynamic tables, search button is not working in responsive design.

http://quirktools.com/screenfly/#u=https%3A//colorlib.com/polygon/gentelella/tables_dynamic.html&w=768&h=1024&a=22&s=1

**Comment by AndreiCN** [comment]
Hi there @jimmibond,

Thank you for reporting this, we will take care of it in a future update.

Regards,
Andrew.
