### ISSUE TITLE
Is there datetimepicker component? 

### ISSUE THREAD

**Issue by leonlee985** [puikinsh/gentelella#244]
I only see date picker in advanced components. I want to input time like 'Y-m-d h:i:s'

**Comment by bensonkb** [comment]
Needed Date-Time Picker components too...

**Comment by devlprcbe** [comment]
there is only data in advance Component. I want to have data and time component too.......

**Comment by devlprcbe** [comment]
@puikinsh Kindly add Time Component too..

**Comment by krzysiekpiasecki** [comment]
> Is there datetimepicker component?

> The Date Range Picker can also be used to select times. Hour, minute and (optional) second dropdowns are added below the calendars. An option exists to set the increment count of the minutes dropdown to e.g. offer only 15-minute or 30-minute increments

[See examples how to customize this component](http://www.daterangepicker.com/#examples)

**Comment by devlprcbe** [comment]
@krzysiekpiasecki

As mentioned in [example](http://www.daterangepicker.com/#examples)
i tried out. Time is not reflecting in textbox...
      $(document).ready(function() {
        $('#birthday').daterangepicker({
          singleDatePicker: true,
          calender_style: "picker_4",
		  timePicker: true,
       	  timePickerIncrement: 30,
		  locale: {
            format: 'MM/DD/YYYY h:mm A'
        }
        }, function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
        });
      });
    </script>
`

**Comment by christianesperar** [comment]
Enhancement on this PR: https://github.com/puikinsh/gentelella/pull/304

**Comment by ximenqiuxue** [comment]
how to configure the locale language? I

**Comment by William-H-M** [comment]
You can use the either [bootstrap-datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker), currently in code freeze, or use [tempus-dominus](https://tempusdominus.github.io/bootstrap-3/)

Both have options to change language, and this template has examples of it
