### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by krzysiekpiasecki** [puikinsh/gentelella#247]
What are the plans for a new release?

**Comment by krzysiekpiasecki** [comment]
@puikinsh @christianesperar

**Comment by puikinsh** [comment]
Hopefully we'll be back on track in October. If you have any suggestions for future release, please let us know.

**Comment by chilukey** [comment]
For the dynamic table page, when there are many entries, the table loads entries at beginning then it changes to the format of 10 rows per page. So it always has a period to Chang from long table to the short table, although the period is short, it still seems strange. I was wondering if there is a way to fix this in future.

**Comment by AndreiCN** [comment]
Hi @krzysiekpiasecki, for a large number of items it can act like this, a temporary solution would be to add a preloader, a solution from the actual script maybe it can be found in the documentation and maybe some sample code from the author.

**Comment by krzysiekpiasecki** [comment]
It's all about a new release and it wasn't my question.
