### ISSUE TITLE
seperate sass files

### ISSUE THREAD

**Issue by leantony** [puikinsh/gentelella#248]
Hi. Is it possible to include separate sass files instead of one large one. Just for development purposes of course

**Comment by ptournem** [comment]
Hi,
I do agree with Leantony. 
Moreover it would be great if we could have the sass file using variable, mixins, pseudo-classes... It could then be easier to customize the theme.
Thanks

**Comment by tdekoekkoek** [comment]
This one is major for me.  That one .sass file is huge and really hard to tell what I actually need in my product and what I don't need.  But otherwise a great looking theme.

**Comment by Firestorm-Graphics** [comment]
unless in mistaken bootstrap is by default: less and bootstrap 4 comes sass by default.
