### ISSUE TITLE
Sidebar - save state (nav-md nav-sm)

### ISSUE THREAD

**Issue by sazmer** [puikinsh/gentelella#249]
If the user chooses to minimize the sidebar, and then clicks a link in the sidebar, the sidebar doesnt stay minimized on the new page. It always seems to check the browser width and toggle the state according to this.

I would like for my users to be able to keep the state, i.e. with localstorage. I'm going to implement this myself, just wondering if this was overlooked or on purpose?

Love the interface.
Samuel

**Comment by christianesperar** [comment]
Localstorage implementation is fine, but this can be handle on server side and can make the flickering transition less visible or not at all.

**Comment by sazmer** [comment]
Thanks for the tip, sounds like server side is a better idea.
