### ISSUE TITLE
Sidebar/Dropdown

### ISSUE THREAD

**Issue by Maraket** [puikinsh/gentelella#25]
So I'm currently trying to use Gentelella in a project for a nice simple dashboard though I'm finding the following as problems:

* The dropdown appears to only be a single level, is there a way of extending this to multilevel
* When a page opens, it automatically opens the first occuring dropdown, how can i disable this

**Comment by mcyenikoylu** [comment]
I need it in me.
"js / sidebar" There are files in the folder. but no property.

**Comment by eferdi** [comment]
multilevel sidebar would be nice

**Comment by ishaqsharief318** [comment]
Yeah multilevel sidebar would be great.

**Comment by christianesperar** [comment]
Added functionality for multilevel menu on this pr https://github.com/puikinsh/gentelella/pull/93

**Comment by christianesperar** [comment]
Fix sidebar is now on pr https://github.com/puikinsh/gentelella/pull/137
