### ISSUE TITLE
Datatable responsive breaks on mobile

### ISSUE THREAD

**Issue by sazmer** [puikinsh/gentelella#250]
Viewing the datatables on mobile device, the search field ends up outside the design. If you remove the search bar, other elements (1 of 57 rows/show 10) ends up on top of each other.

Google chrome on Android, Samsung Galaxy S6.

![screenshot_20160803-153252](https://cloud.githubusercontent.com/assets/5465115/17367280/b3094dac-598f-11e6-8429-3743cc653a03.jpg)
![screenshot_20160803-153803](https://cloud.githubusercontent.com/assets/5465115/17367509/70775ff0-5990-11e6-90dd-9c6ea53d44f8.jpg)

**Comment by AndreiCN** [comment]
Hi @sazmer ,

Thank you for noticing that, we'll take care of it in our future update, 

Regards,
Andrew.
