### ISSUE TITLE
Large modal displays under sidebar-menu

### ISSUE THREAD

**Issue by sazmer** [puikinsh/gentelella#252]
On the example-page, the modal is placed below the menu and the issue therefore doesn't occur. If the user chooses to place the large modal closer to the top of the page, the modal (and overlay) displays under the menu.

In custom.css, `.nav-md .container.body .col-md-3.left_col`, has a z-index set to 9999 and the modal/overlay is 1050 something. I set z-index of `.nav-md .container.body .col-md-3.left_col` to 1000 in the head of my page and it fixes the problem. However, I don't know if this will cause other issues to the theme?

**Comment by sumbad** [comment]
Hi, now I'm using the same approach. It works fine for me.
