### ISSUE TITLE
Dynamic Tables missing some functionality

### ISSUE THREAD

**Issue by eladelad11** [puikinsh/gentelella#253]
First, I would like to thank you for a great contribution. This project is awesome!

After downloading source code, I was trying to use the "Button Example" dynamic table and noticed the _**Excel**_ button does not generate an Excel file. However, in Colorlib site example, it works.
In addition, the Colorlib site example has another button - _**PDF**_ (this button does not exist in github sample).

Is this an outdated DataTables sample?

[github](https://github.com/puikinsh/gentelella)
![2016-08-08_1709](https://cloud.githubusercontent.com/assets/20298340/17482536/dcc755a4-5d8a-11e6-86a8-f16c3a541ab8.png)

[Colorlib:](https://colorlib.com/polygon/gentelella/tables_dynamic.html)
![2016-08-08_1708](https://cloud.githubusercontent.com/assets/20298340/17482512/c142ca48-5d8a-11e6-8d81-f8b98ac0504f.png)

Thanks!
Elad

**Comment by eladelad11** [comment]
Thanks @AndreiCN.
I've just verified, still Excel button does not work and PDF button is missing with Chrome.
With IE and FF, Excel button is also missing.

I've downloaded latest version through "Download ZIP" button.

**Comment by pallavidesai** [comment]
Did you find any fix for that ?@eladealad11
Thanks in advance.

**Comment by eladelad11** [comment]
@pallavidesai, unfortunately I didn't :|

**Comment by young310** [comment]
@AndreiCN PDF button is still missing
@eladelad11 Did you find any work around?

**Comment by young310** [comment]
@AndreiCN 
I just found the work around by moving 
  `<script src="../vendors/pdfmake/build/pdfmake.min.js"></script> `
in front of 
  `<script src="../vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>`

and it works now

**Comment by AndreiCN** [comment]
Ok @young310, thank you for your contribution.

**Comment by AndreiCN** [comment]
fixed it.

**Comment by raihan71** [comment]
thank you all, this discuss has been fixed my problem
