### ISSUE TITLE
Missing distribution files?

### ISSUE THREAD

**Issue by nelson6e65** [puikinsh/gentelella#256]
This an awesome theme! :smiley:

I explore the demo, and is beautiful and useful. I'm glad to use this. :smiley:

But I think is necessary a `dist` directory with "usable" assets, like [Bootstrap](https://github.com/twbs/bootstrap/tree/master/dist), [jQuery](https://github.com/jquery/jquery-dist/tree/master/dist), and other packages does.

That will make this package easier to use and configure paths. 

Also, about the bower install, dependencies are missing. #254 
Related with: #178

**Comment by AndreiCN** [comment]
Thank you @nelson6e65,

We'll take that into consideration in our future update.

Regards,
Andrew.
