### ISSUE TITLE
Multiple file uploader not working properly

### ISSUE THREAD

**Issue by dESourcesra** [puikinsh/gentelella#258]
1- Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

2- View is not responsive

**Comment by AndreiCN** [comment]
Hi there @dESourcesra, 

1. Please make sure you're using the latest version of dropzone plugin, their documentation was really helpful while integrating this with our code, here is the author website: http://www.dropzonejs.com , if you encounter problems with the actual plugin take a look on their git account (https://github.com/enyo/dropzone/issues), maybe someone had the same issues.

2. We had some testing with responsive scenarios however there are a lot of devices and browsers version over there, please provide some screenshots so we can figure out how can we improve this even further!

Regards, 
Andrew.
