### ISSUE TITLE
dynamic tables on mobile

### ISSUE THREAD

**Issue by mshannaq** [puikinsh/gentelella#265]
the dynamic tables shown outside the layout when you use open it in mobile

see the following example

http://u.di.net.sa//getfile.php?file=2943371869.png

**Comment by mshannaq** [comment]
http://u.di.net.sa//getfile.php?file=2943371869.png&ds

this the correct screenshot

**Comment by AndreiCN** [comment]
Hello mshannaq,

That happens because those one aren't responsive, please check the responsive example.

Cheers,
Andrew.
