### ISSUE TITLE
Calendar - Bug when updating event

### ISSUE THREAD

**Issue by clem983** [puikinsh/gentelella#269]
Hi !

Thank you for your theme ! It's perfect !
I encountered a bug with the calendar : when I click on an event without update it, and, then I want to update another event, both are modified.
The "click" handler is called twice. If you have clicked on 10 events, the action will be executed 10 times.
Do you know how to change that ?

Thanks a lot :)

**Comment by AndreiCN** [comment]
Hi clem,

Thank you for reporting this, we'll take care of it in our future update !

Cheers,
Andrew !
