### ISSUE TITLE
"Uncaught TypeError" on getting body style!

### ISSUE THREAD

**Issue by gonzalesc** [puikinsh/gentelella#27]
Hi.
First, Gentelella is a nice dash!

Hi, there is a bug "Uncaught TypeError: Cannot read property 'style' of null " on this line:  @376
in the script "nprogress.js"

In the demo : http://demo.kimlabs.com/gentelella/production/index.html  appears this bug

// Sniff on document.body.style
var bodyStyle = document.body.style;

**Comment by christianesperar** [comment]
This pr #30 also fix this bug
