### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by faasantos** [puikinsh/gentelella#271]
Hi
Great template!
How can I check a checkbox  through js?

**Comment by lwbritz** [comment]
Hi! You can use jQuery .prop() method to do this.  Or you can use pure javascript `document.getElementById("yourCheckboxId").checked = true/false;`
Using jQuery: http://stackoverflow.com/questions/426258/setting-checked-for-a-checkbox-with-jquery

**Comment by faasantos** [comment]
Hi
Thanks for quick answer.
Unfortunatelly, no success. 
Tried getElement, prop, attr ... the only thing that matters is what is on the HTML before running JS:
 <input type="checkbox" name="cenabled" id="cenabled" class="flat" **_checked >_** Ativo<br>

If I have "checked" on it, it load allways on. And it's value is ok when saving after (I can change it)
If not, it loads not checked and it is allways false when saving, even if visually it is checked.
Thanks for any ideas!
