### ISSUE TITLE
Move the sidebar to the right

### ISSUE THREAD

**Issue by isantosp** [puikinsh/gentelella#272]
Hi everyone.. 

As the title, I want to move the side menu to the right instead of the current position on the left.. Just that, I mean I don't even need a full RTL version.

Can someone help me with this thing?? o_O

**Comment by AndreiCN** [comment]
Hi @isantosp ,

Do you still have that problem ?

**Comment by isantosp** [comment]
Nope @AndreiCN  :(
I couldn't did it and found anything :-/
You have some clues?? o_O

**Comment by AndreiCN** [comment]
Ok @isantosp,

Well needs some custom work here, but with a little bit of attention it should work so i will try to gide you :)

First of all you must find "" , when you found it, replace it with this :


        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              
              <ul class="nav navbar-nav navbar-left">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="images/img.jpg" alt="">John Doe
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    <li>
                      <a href="javascript:;">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Settings</span>
                      </a>
                    </li>
                    <li><a href="javascript:;">Help</a></li>
                    <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>

                <li role="presentation" class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="text-center">
                        <a>
                          <strong>See All Alerts</strong>
                          <i class="fa fa-angle-right"></i>
                        </a>
                      </div>
                    </li>
                  </ul>
                </li>
              </ul>
			  
			  <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
			  
            </nav>
          </div>
        </div>
        

       Second, go to your CSS file and put this part right to the bottom ( after your last line of code )
       
       .nav-md .container.body .right_col 											{ margin-right: 230px;margin-left:0; }
  .nav-md .container.body .col-md-3.left_col 									{ right:0; }
  .top_nav .navbar-left 														{ float:left; }
  .toggle  																		{ float:right; }  
  .nav-sm .container.body .col-md-3.left_col 									{ right:0; }
  .nav-sm .container.body .right_col 											{ margin-left:0;margin-right:70px; } 
  .nav-sm .main_container .top_nav 												{ margin-left:0;margin-right:70px; }
  .main_container .top_nav 														{ margin-left:0;margin-right:230px; }
  
  footer 																		{ margin-right:230px;margin-left:0; }
  
 So this should do the trick , i hope this will be helpful for you. If you have another issues don't hesitate to put it here :)

  Regards,
  Andrew.

**Comment by Rndwiga** [comment]
Hi Andrew,

You should make that as a commit on a different page such that its available to everyone by default on next pull.

**Comment by AndreiCN** [comment]
Yep, we will take that into consideration, thank you !

Cheers,
Andrew.
