### ISSUE TITLE
Sidebar menu doesn't work with angular.js

### ISSUE THREAD

**Issue by hardmaster92** [puikinsh/gentelella#273]
Hello, I've tried using gentelella for my admin panel. Everything works fine but when I tried to make an angular project using templates the sidebar menu doesn't work. The menu links themselves work but they don't highlight when you hover over them and also dropdowns don't unfold when you click them. However there aren't any errors in the console which is weird. The sidebar menu also hides/appears when changing window size.
I use an abstract state for the main emplate and I load sidebar menu, navbar and content in 3 different ui-view elements. If you are interested in seeing the code itself I can upload it.

**Comment by hardmaster92** [comment]
Nevermind, it's not gentelella related issue. It's just that the gentelella.js file is being loaded earlier than the actual angular.js framework and its templates and these variables:
$MENU_TOGGLE = $('#menu_toggle');
$SIDEBAR_MENU = $('#sidebar-menu');
$SIDEBAR_FOOTER = $('.sidebar-footer');
$LEFT_COL = $('.left_col');
$RIGHT_COL = $('.right_col');
$NAV_MENU = $('.nav_menu');

are being set before the sidebar and menu are even being loaded.

**Comment by ocliuziyang** [comment]
Hi, When i use vue.js 2.0 to load gentelella, the sidebar can't be click with js.

**Comment by jaimohann** [comment]
Hi hardmaster92 , how did you solve the problem ?. Can you please share your solution for this.

**Comment by DivingPigy** [comment]
The sider menu does not work normally when clicking on it. Why?
