### ISSUE TITLE
Select2 with Bootstrap Dropdown-Menu

### ISSUE THREAD

**Issue by Especially** [puikinsh/gentelella#274]
I'm trying to use the the 'select2' library on a bootstrap dropdown-menu, however a problem that I've come across is that when wrapped in the `<li>` tag, the select2 library fails to work. When I click on the select box, the carat turns downwards, however it does not list options for me to click, nor does it display the appended search-to-select input box. In addition to this, when clicking a select WITHIN a dropdown-menu, the menu box closes as if I clicked away from the box, I'm not sure how to fix these problems.

**Comment by AndreiCN** [comment]
Hi there @Especially,

Are you still have that problem ?

**Comment by Especially** [comment]
Yes i'm still having this problem.

**Comment by Especially** [comment]
@AndreiCN Additionally, using the timepicker fails to work; the dropdown for selecting times appears and then disappears.
