### ISSUE TITLE
Main menu dosn't often work in IE browser!!!! 

### ISSUE THREAD

**Issue by ccr1027** [puikinsh/gentelella#28]
Hi~ I used IE 11 64bit browser to view your demo web, and the first linked web, click page link, it can  work, but after it, click orther link, it didn't respond any something!! what do i do to resolve it?

**Comment by christianesperar** [comment]
This pr #30 also fix this bug

**Comment by puikinsh** [comment]
Fixed on #30 thanks to @christianesperar

Yesterday I took over this project and more updates are coming soon.
