### ISSUE TITLE
General Form - Cancel button - Validating and submitting

### ISSUE THREAD

**Issue by helly168** [puikinsh/gentelella#280]
In the first general forms the cancel button is submitting the request.

I have changed it in my project to reset but it will still validate first before resetting the form
<button type="reset" class="btn btn-primary">Cancel</button>

See here:
https://colorlib.com/polygon/gentelella/form.html

**Comment by AndreiCN** [comment]
Hi helly,

We handled this one, will be available in our future update.

Regards,
Andrew.
