### ISSUE TITLE
Smart wizard : Double click on Next or Previous buttons loads two steps on one page

### ISSUE THREAD

**Issue by ardent-qadeer** [puikinsh/gentelella#282]
As soon as you double click the next or previous buttons it loads the next two steps on the page.
How can we resolve this issue?

![previous-button-wizard-issue](https://cloud.githubusercontent.com/assets/20680745/18833895/9d3f547a-8410-11e6-8f24-a4afc0165437.png)
![next-button-wizard-issue](https://cloud.githubusercontent.com/assets/20680745/18833896/9d422a42-8410-11e6-9586-8e1af2ff85c0.png)

**Comment by AndreiCN** [comment]
Hello ardent,

It works just fine now,

Regards,
Andrei.
