### ISSUE TITLE
When will be available the next release ?

### ISSUE THREAD

**Issue by Lith** [puikinsh/gentelella#283]
Hello,

I would like to know when the next release with all latest updates (since June 1st) will be pushed on NPM/Bower ?
I would like to use this project with Webpack and Angular2, but for now it's not possible because of some errors corrected after the 1.3.0 like this commit :
- https://github.com/puikinsh/gentelella/commit/c3fb2b45621c35fd8a700b23d4fe03c6ab64b1e7#diff-d37f597de7a8588e980ffe960c706466

Thanks :)

**Comment by krzysiekpiasecki** [comment]
Related to #247

**Comment by mkarajohn** [comment]
@Lith I had the same issue. The way I worked around it was to `npm uninstall` the gentelella package, manually add the entry `"gentelella" : "git@github.com:puikinsh/gentelella.git"` to `package.json` and then `npm install` again. This way it pulls from the repo, where the errors do not exist.

**Comment by tellonelson** [comment]
Please, what install for application java, please?, help me!
