### ISSUE TITLE
Sidebar with "nav-sm" on current page always display child menu

### ISSUE THREAD

**Issue by federicoha** [puikinsh/gentelella#286]
Hi All, first thanks for your amazing template.

Not sure if is an issue, so if you please confirm behavior will be great. When using `<body class="nav-sm">` and menu find your current page, automatically show the child menu items for that father.

![image](https://cloud.githubusercontent.com/assets/22528354/18999550/97cc6e4a-8714-11e6-91b1-322d80613989.png)
(yellow is the current and this is showing when page is loading)

I saw a similar wording change in pull request ([https://github.com/puikinsh/gentelella/pull/281]) but not work for me.

Making a change in custom.js i was able to not show the child items and also reflect the active menu, but if i click again, lost the active, and the second click show the child menu

This is the change:

Commented line:
`
//$SIDEBAR_MENU.find('a').filter(function () {
//    return this.href == CURRENT_URL;
//}).parent('li').addClass('current-page').parents('ul').slideDown(function () {
//    setContentHeight();
//}).parent().addClass('active');
`

New one:
`
$SIDEBAR_MENU.find('a').filter(function () {
return this.href == CURRENT_URL;
}).parent('li').addClass('current-page').parents('ul').parent().addClass('active active-sm');
`

Version i use is getting from bower and version is: "gentelella": "^1.3.0"

Thanks in advance.

**Comment by chocobot21** [comment]
remove this line : 
`.parent("li").addClass("current-page").parents("ul").slideDown(function() { e() })`

custom.min.js

**Comment by federicoha** [comment]
perfect, thanks!

**Comment by funilrys** [comment]
a simple way is to change/apply display:none to the object

**Comment by freel132** [comment]
Non of these solutions worked for me. seems that what ever I am doing always when I am opening it displays open sub meniu.

**Comment by nelsonluiz** [comment]
Guys I need a help... I included a include page in div id=content where that links are going to open, and I would like that (when on mobile) in the moment the user clicks on a link the menu totaly disapare. 

Can someone help me?
