### ISSUE TITLE
Lost style checkbox after ajax update

### ISSUE THREAD

**Issue by Buranzo** [puikinsh/gentelella#289]
I wrote code:
`<div id='block'></div>`
Also added JS script with atomatic reload values from database and updates checkbox in the 'block'.
`var checkbox = '<input type="checkbox" class="js-switch" />';
$('#block').html(checkbox);
`
After run application (before update 'block') style checkbox is ok, but after ajax update 'block' style of checkbox will be clearing to default bootstrap style.

**Comment by SerginhuXavier** [comment]
same bug. Please someone help!

**Comment by AndreiCN** [comment]
Will take this for a further investigation, thank you !

**Comment by Zubair530** [comment]
I am also facing the same problem, any update regarding this problem?

**Comment by AndreiCN** [comment]
Working on it @Zubair530 , will be solved this one once the new update will be released :)

**Comment by Zubair530** [comment]
Thanks for such a prompt reply :)

**Comment by AndreiCN** [comment]
You welcome 👍

**Comment by AndreiCN** [comment]
Well unfortunately we do not use ajax for it but I can come up with a solution though.

After your ajax request is completed what should you to is reinitialize this code : 

`$(document).ready(function() {
    if ($("input.flat")[0]) {
        $(document).ready(function () {
            $('input.flat').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass: 'iradio_flat-green'
            });
        });
    }
});`

or

create a function called "init_checkbox" for example and again, reinitialize it after ajax request is complete, this should do the trick :)

**Comment by Zubair530** [comment]
Thank you very much, it did the trick for me with document.ready()

**Comment by AndreiCN** [comment]
Glad to hear that :)
