### ISSUE TITLE
how to hide sidebar (like it does in mobile mode)?

### ISSUE THREAD

**Issue by KrishnaPG** [puikinsh/gentelella#290]
The `nav-sm` and `nav-md` display the sidebar nicely.

However, for some pages, I would like to, irrespective of current view is mobile or desktop or large, hide the sidebar? Which setting controls this?

When I load the page (on any device / display size) I just want to show the `menu toggle bars` without showing the sidebar. Help is appreciated.

**Comment by christianesperar** [comment]
Do you mean without the icons?

**Comment by KrishnaPG** [comment]
Yes, hiding the complete sidebar, with only showing the `toggle bar` (so that when user clicks on the `toggle bar` the sidebar with full icons will slide into view)

**Comment by LuisCamargoTI** [comment]
Hello KrishnaPG,

My solution was edit custom.js and custom.css;

- In custom.js edit the part $MENU_TOGGLE , only the part $BODY.toggleClass('nav-md nav-lg'); , change nav-sm to nav-lg;

- In custom.css include code below:
//move to left menu top and footer
.nav-lg .top_nav {
  margin-left: 0px;
}
.nav-lg footer {
  margin-left: 0px;
}

//hidden left menu
.nav-lg .left_col{
	display: none;
}

**Comment by KrishnaPG** [comment]
Thank you @LuisCamargoTI  Will try it.
