### ISSUE TITLE
Some how-to questions

### ISSUE THREAD

**Issue by dashinghunk** [puikinsh/gentelella#293]
Hello, I would appreciate if someone can point me in the right direction:
1. How can I freeze the headers of data tables? 
2. How can I freeze, say, first 2 columns in a data table with 20+ columns? 
3. The tabs run into each other on mobile view or when they run into multiple lines
4. How can I add a button like 'Add new row' and add an empty row in a data table?
5. How can I click a row action button like 'Edit this row' that will turn label into editable textboxes? I did see a blue edit icon in data tables, but it doesn't seem to do anything?
6. All data table searchboxes search the entire table. Do you have a more advanced example where you can search individual columns with text/number/checkbox/date/currency filters?
7. Column sorting in data tables appears to be text based. Can it be 'smart'? As in if the column has a number or currency it must do integer sorting not string based. 
8. Is there an easy way to customize the site colors/theme (as in clicking some buttons as opposed to hacking the CSS)?
9. Is it possible to have breadcrumbs on the top? As in if you are in sub menu 2, then on the top there must be a site road that automatically displays something like 'Home -> Menu 1 -> Sub menu 2'.

**Comment by omega-inspiron** [comment]
1 . You need to use the data-tables fixedHeader plugin.  Include the css and js file and then when you initialize your datatable, add fixedHeader: true.  The table_dynamic.html file in the demo has an example.

2. You need to use the data-tables fixedColumns plugin.  Include the css and js file and then when you initialize your data-table, add the following:
        fixedColumns:   { leftColumns: 2 }  //2 signifies the number of columns you want to freeze

8. Define what you mean by easy.  If you want to change the color theme, then you'll have to set your own color classes, and then with for example jquery, in the button's on.click event, you can make use of addClass(), removeClass() or toggleClass() to change the color scheme on the fly.  

9. Yes it is possible to have breadcrumbs on the top.   Solution put a div container at the top in the top_nav area, and then either attach a click event to each navigation menu item that overwrites that container, or for elegance, add a class and a data attribute to all of the navigation items then attach a click event to that class and with a switch statement cycle through to find which one was clicked on and then change the div container text accordingly.

**Comment by alfaquinog** [comment]
Hello,

I need to change the DataTable text box Search label to Buscar:
how can I do it?

**Comment by William-H-M** [comment]
@alfaquinog This is not something related to this template (Is not a bug, that's what I mean), but if you search at [DataTables](https://datatables.net/) official page this is the result https://datatables.net/reference/option/language
For those kinds of question please use google, is not that hard.

**Comment by martinmurciego** [comment]
Maybe late, but I want to contribute to someone.

`myDatatable = $("#dataTablePersonas").DataTable({
    language: {
        sProcessing: "Procesando...",
        sLengthMenu: "Mostrar _MENU_ registros ", //Original "Mostrar _MENU_ registros"
        sZeroRecords: "No se encontraron resultados",
        sEmptyTable: "Ningún dato disponible en esta tabla",
        sInfo: "Total _TOTAL_ registros", //Original "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros"
        sInfoEmpty: "Total 0", //Original "Mostrando registros del 0 al 0 de un total de 0 registros"
        sInfoFiltered: "de _MAX_ registros", //Original "(filtrado de un total de _MAX_ registros)"
        sInfoPostFix: "",
        sSearch: "Buscar:",
        sUrl: "",
        sInfoThousands: ",",
        sLoadingRecords: "Cargando...",
        oPaginate: {
            sFirst: "Primero",
            sLast: "Último",
            sNext: "Siguiente",
            sPrevious: "Anterior"
        },
        oAria: {
            sSortAscending: ": Activar para ordenar la columna de manera ascendente",
            sSortDescending: ": Activar para ordenar la columna de manera descendente"
        }
    },
    columns: [
        //{ title: "Id" },
        { title: "Empleado" },
        { title: "Posicion" },
        { title: "Oficina" },
        { title: "Extn." },
        { title: "Fec.Inicio", format: 'dd/mm/yyyy'}, //formato
        { title: "Sueldo" },
        { title: "Accion" }
    ],
    columnDefs: [
        {
            sortable: false,
            "class": "index",
            targets: 0 //la primer columna tendra un numero de registro o renglon rowid
        }, 
        {
            visible: false,
            targets: hiddenColsArray //arreglo de indice de columnas que seran afectadas
        },
        {
            targets: -1, //-1 es la ultima columna y 0 la primera
            data: null,
            defaultContent: '<div class="btn-group"> <button type="button" class="btn btn-info btn-xs dt-view" style="margin-right:16px;"><span class="glyphicon glyphicon-eye-open glyphicon-info-sign" aria-hidden="true"></span></button>  <button type="button" class="btn btn-primary btn-xs dt-edit" style="margin-right:16px;"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></button><button type="button" class="btn btn-danger btn-xs dt-delete"><span class="glyphicon glyphicon-remove glyphicon-trash" aria-hidden="true"></span></button></div>'
        },
        { orderable: false, searchable: false, targets: -1 } //Ultima columna no ordenable para botones
    ], 
    autoWidth: false,
    fixedHeader: true, //encabezados fijos o frozen, requiere dataTables.fixedHeader.min.js
    bLengthChange: true, //Mostrar cantidad filas por por pagina abajo que muestra
    //oSearch: {"sSearch": "frase buscada..."}, //valor default (no es placeholder)
    lengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "Todas"]], //cantidad de filas por pagina
    pagingType: "first_last_numbers", //"simple_numbers", first_last_numbers, full_numbers presenta overflow:auto
    pageLength: 5,
    dom: '<"html5buttons"B><"clear">Tfgtlpi', //inspinia ejemplo
    data: dataSet,
    order: [0, 'asc'],
    ordering: true,   
    keys: true, //permite navegar con keyboard pero requiere dataTables.keyTable.min.js
    decimal: ",", //coma separador decimal
    thousands: ".", //punto separador de miles
    deferRender: true,
    buttons: [
        {
            extend: "addButton",
            text: 'Nuevo',
            action: function ( e, dt, node, config ) {
                console.log( 'addButton activated' );
            }
        },
         { 
            extend: 'copyHtml5',
            text: 'Copiar'
         },
         { 
            extend: 'csvHtml5',
            text: 'CSV'
         },
         { 
            extend: 'excelHtml5',
            text: 'XLS'
         },
         { 
            extend: 'pdfHtml5',
            text: 'PDF'
         },
         { 
            extend: 'print',
            text: 'Imrimir',
            key: {
                key: 'p',
                altkey: true
            }
         },
      ]
});
`
