### ISSUE TITLE
Named event handlers for late initialization for Ajax support

### ISSUE THREAD

**Issue by KrishnaPG** [puikinsh/gentelella#295]
Currently all initialization of events is happening on `document.ready`, which is working fine when all content is statically loaded upfront.

This however, does not work when loading panels or widgets through ajax (since events are not attached).

Request to please have the initialization functions as `named methods` instead of the current anonymous methods, so that late initialization can take advantage of the code by calling the named methods on demand when necessary.

Created a pull request for your reference: https://github.com/puikinsh/gentelella/pull/294

In this PR,
-  the existing `document.ready()` event handlers are untouched, so any existing code will not be affected.
-  names (in the global scope of `window`) are associated with the events so that they can be used through out the app at any location
-  invoking the event handler initialization multiple times is made safe (for example, sidebar events could be initialized multiple times with multiple  `window.gentelella_sidebar_doc_ready()` calls, but only one event will be actively associated)

For example, this will make it possible to load a Panel or Accordion through ajax and call `window.gentelella_panel_doc_ready()`, `window.gentelella_accordion_doc_ready()` methods safely to initialize them - and this will not modify any existing panel or accodian controls already existing on the page.

**Comment by AndreiCN** [comment]
Hi there @KrishnaPG ,

We already took care of this point, we will release it in next update, thank you for the suggestion though :)

Best Regards,
Andrew.
