### ISSUE TITLE
Dynamic tables with buttons + ASP.NET Grid not working?

### ISSUE THREAD

**Issue by sem27** [puikinsh/gentelella#297]
Hello,

if I use a ASP.NET grid for the table and fill it with data, the buttons won't appear anymore. Why? I renamed the IDs, renamed the IDs in the function in the script too, but nothing new.

**Comment by ltfi** [comment]
You need activate thead for grid view, It si sth like that;
gvUsers.HeaderRow.TableSection = TableRowSection.TableHeader;

**Comment by sem27** [comment]
Still not working. :(

**Comment by sem27** [comment]
Yeaaaaaaaah, it´s working!!!!!!! Thank youuu!!!!!!!!!!!!!!!!!

**Comment by sem27** [comment]
In which script can I change the default number of records in the table? Now it´s 15, even if I set the PageSize="20" in the Grid.

**Comment by ltfi** [comment]
Np bro, 
I have no idea about your second question :(

**Comment by sem27** [comment]
But thank you anyway. I would never know this. Thanks!

**Comment by ltfi** [comment]
Maybe you can use jquery select option in page ready.

$("div.id_100 select").val("20");

**Comment by sem27** [comment]
On one page I have the table in HTML like in the template. But the HTML is generated from C# and inserted. It is in a update panel. I put the datatable buttons script in a function and calling it from behind before updating the panel, but the buttons don't appear :( :(

Any ideas??

**Comment by ltfi** [comment]
Add a photo pls, i did'nt understand clearly :(


________________________________
Gönderen: sem27 <notifications@github.com>
Gönderildi: 15 Kasım 2016 Salı 12:39
Kime: puikinsh/gentelella
Bilgi: ltfi; Comment
Konu: Re: [puikinsh/gentelella] Dynamic tables with buttons + ASP.NET Grid not working? (#297)


On one page I have the table in HTML like in the template. But the HTML is generated from C# and inserted. It is in a update panel. I put the datatable buttons script in a function and calling it from behind before updating the panel, but the buttons don't appear :( :(

Any ideas??

-

**Comment by sem27** [comment]
![image](https://cloud.githubusercontent.com/assets/22743838/20304617/8e828126-ab31-11e6-89e7-ea514f9400a3.png)
 This is how I dynamically create the table. Just a part of the code. I create the whole row div.

At the end, I do this in C#:
![image](https://cloud.githubusercontent.com/assets/22743838/20304674/d09b8cf6-ab31-11e6-89a8-0e2627a5c9d6.png)

(That commented line is what I used when I have a asp.net grid, then the buttons were working with it. Ignore that line now.)

And this is the function Starting() in Javascript:

` function Starting() {
            var handleDataTableButtons = function () {
                if ($("#datatablebuttons").length) {
                    $("#datatablebuttons").DataTable({
                        dom: "Bfrtip",
                        buttons: [
                          {
                              extend: "copy",
                              className: "btn-sm"
                          },
                          {
                              extend: "csv",
                              className: "btn-sm"
                          },
                          {
                              extend: "excel",
                              className: "btn-sm"
                          },
                          {
                              extend: "pdfHtml5",
                              className: "btn-sm"
                          },
                          {
                              extend: "print",
                              className: "btn-sm"
                          },
                        ],
                        responsive: true
                    });
                }
            };

            TableManageButtons = function () {
                "use strict";
                return {
                    init: function () {
                        handleDataTableButtons();
                    }
                };
            }();

            $('#datatable').dataTable();
            $('#datatable-keytable').DataTable({
                keys: true
            });

            $('#datatable-responsive').DataTable();

            $('#datatable-scroller').DataTable({
                ajax: "js/datatables/json/scroller-demo.json",
                deferRender: true,
                scrollY: 380,
                scrollCollapse: true,
                scroller: true
            });

            var table = $('#datatable-fixed-header').DataTable({
                fixedHeader: true
            });

            TableManageButtons.init();
        }`

**Comment by sem27** [comment]
When generating the table, the id is like in the function "datatablebuttons".

**Comment by ltfi** [comment]
Sorry bro, i have no solution for this problem :(


________________________________
Gönderen: sem27 <notifications@github.com>
Gönderildi: 15 Kasım 2016 Salı 14:54
Kime: puikinsh/gentelella
Bilgi: ltfi; Comment
Konu: Re: [puikinsh/gentelella] Dynamic tables with buttons + ASP.NET Grid not working? (#297)


When generating the table, the id is like in the function "datatablebuttons".

-

**Comment by sem27** [comment]
Why did you close my problem?

**Comment by AndreiCN** [comment]
Hi there @sem, unfortunately we can't cover every integration in every language however if you still have issues, datables are very well documented on the project's web page, here is some good information about reference and code samples for a better understanding of the script:
https://datatables.net/reference/index
https://datatables.net/examples/index

The project is opensource and can be found on GitHub, if you still have this issue or you encounter other problems they have a comprehensive list of fixes and solutions for their version:
https://github.com/DataTables/DataTables/issues

In case you have an older version don't forget to update to the latest version of DataTables available on their website.

Thank you for your feedback.

Regards,
Andrew.

**Comment by Irishm** [comment]
I am using the Responsive example table but I want to add the buttons of the Button example table, how can I add them without desapear my 'Show entries. select?

**Comment by William-H-M** [comment]
Hi, @Irishm for this you just need to use the buttons extension and add it to whatever possition yo want it, with the '[dom](https://datatables.net/reference/option/dom)' option, from datatables, they have on their page quite good documentation about it with examples, you can check it out here: https://datatables.net/extensions/buttons/

**Comment by Irishm** [comment]
Thanks William-H-M I will try.

**Comment by Irishm** [comment]
I did it! It works perfectly, thank you William-H-M
