### ISSUE TITLE
Dynamic table + custom pagination (page number)?

### ISSUE THREAD

**Issue by sem27** [puikinsh/gentelella#306]
I am using ASP.NET and a GridView for a table. Everything works well but I want to change the default page size of 15! Even if I try to set the GridView to PageSize="20", the website is showing always 15 results per Page. In which script is the secret?

**Comment by AndreiCN** [comment]
Hi @sem27 ,

You can take a look in vendors/datatables.net or even better here : https://www.datatables.net 

Regards,
Andrew.
