### ISSUE TITLE
How to pass all forms in the wizard as one array?

### ISSUE THREAD

**Issue by marlonbrand0** [puikinsh/gentelella#308]
I'm using this template in CodeIgniter and I found that using the wizard page it only passes step one to my controller. I tried to use AJAX serialize, but it breaks the wizard displaying all the steps at once with no buttons on the bottom. How can I make it so all the form tags in each step get passed as one array? Or is there a way to put all the steps into 1 form tag without breaking the format?

**Comment by AndreiCN** [comment]
Hi @marlonbrand0,

Please provide some sample code and any other information that could be helpfull to identify the issue.
