### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by wyklif** [puikinsh/gentelella#309]
i would like to add a height to the notifications dropdown so that it is scrollable

**Comment by omega-inspiron** [comment]
Simple to do.  Either apply an ID to your notification drop down container, or use the existing one from the demo, and then add the css below.  Change the height to the height you desire.

#menu1 {
  height     : 200px;
  overflow   : hidden;
  overflow-y : scroll;
}

**Comment by wyklif** [comment]
thanks
