### ISSUE TITLE
Is this still actively maintained?

### ISSUE THREAD

**Issue by christianesperar** [puikinsh/gentelella#31]
There are many issues and PR  that are not taken action by the owner. Is this actively maintained?

By the way, Nice themes!

**Comment by puikinsh** [comment]
It wasn't maintained at all until now. 

I took over this repo few days ago and will take cate for it.

**Comment by shinnlu** [comment]
so sad, i took some time to survey few admin package, when i do integrated work but finally find this package not actively maintained.

**Comment by puikinsh** [comment]
It is still maintained
