### ISSUE TITLE
Please are there some toast like notifications present.

### ISSUE THREAD

**Issue by AchoArnold** [puikinsh/gentelella#311]
I'm looking for a notification like this.

<img width="1920" alt="screenshot 2016-11-01 09 14 27" src="https://cloud.githubusercontent.com/assets/4196457/19883262/a387d4f0-a013-11e6-87ab-269cef8de4ec.png">

Are they present in this theme or something similar?

**Comment by krzysiekpiasecki** [comment]
See at general elements menu item unde notifications.

**Comment by AchoArnold** [comment]
Thanks Krzysztof 👍
