### ISSUE TITLE
iCheck tickbox cannot select all rows in a Datatable, if data is loaded over Ajax

### ISSUE THREAD

**Issue by cheburashka12** [puikinsh/gentelella#313]
I am loading my data into a Datatable using the "Plus Table Design" template.
Datatable provides a way to load data over Ajax instead of having the data be in HTML.

However when data is loaded this way, the top checkbox ('.bulk_action input#check-all') that is meant to select all rows stops working. It appears it no longer registers the .on('ifChecked') event, or the event becomes unbound.

**Comment by AndreiCN** [comment]
Hi there @cheburashka12 ,

My suggestion would be to check the datatable event and register again ifChecked if necessary. Here are the events documentation, hope will be helpful for you :)
[DataTables.net](http://m.datatables.net/reference/event/)

Best regards,
Andrew.
