### ISSUE TITLE
Dynamic tables with buttons + dynamic HTML from C# not working?

### ISSUE THREAD

**Issue by sem27** [puikinsh/gentelella#319]
The table is the same HTML like in the template, the only difference is that the HTML is being created in the C# and inserted via PlaceHolder control. It is in a update panel.. Before I update the panel, I call the script where the datatable buttons should create and initialize, but they don't appear. :(

Any ideas?

**Comment by connectnbs** [comment]
Any screen shots?

**Comment by sem27** [comment]
I did it. I had to include again the scripts and call again the functions. Now it is working.
