### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by ardent-qadeer** [puikinsh/gentelella#320]
If I minimize the sidebar and go the next page can the sidebar be in minimized?
Please help me out in this.

**Comment by funilrys** [comment]
Only if you put nav-sm on every page. Cause the page refresh everytime. I think the other technic is to create a JS script to do so ...

**Comment by AndreiCN** [comment]
Hi ardent,

Yes, can be done, with some custom work, are you still needing this ?

Cheers,
Andrew.
