### ISSUE TITLE
Need help in using gentelella from node_modules into my project files

### ISSUE THREAD

**Issue by srsprasad** [puikinsh/gentelella#322]
Hi,
My background is completely on Java since 10 years, but willing to learn AngularJS.

Was trying to use Awesome theme 'gentelella' using 'npm install gentelella' which created folder in node_modules/gentelella.
My very basic question is, how can I use from here. Sorry if it sounds very silly, but I can't stop myself from asking even stuppid questions If I don't understand it.

I scaffolded my app which includes: webpack, gulp babel and angularjs.

**Comment by AndreiCN** [comment]
Hi there @srsprasad ,

Well it depends how you want use it, but for instance if you are trying to open a HTML page you find it in gentelella/production/index.html (example) or gentelella/build/custom.js (if you want to open the main JS file).
