### ISSUE TITLE
Line Chart + ASP.NET dynamically binded data?

### ISSUE THREAD

**Issue by sem27** [puikinsh/gentelella#323]
Hello!

I tried to bind dynamically data and show the line chart in the Update panel, but it's not working. I created the datasets in the code behind, put them into a invisible textbox, in javascript I take that textbox value and set it to datasets in the javascript initializing chart function. But it's not working :(

Any ideas??

**Comment by AndreiCN** [comment]
Hi Sem,

Please provide some sample code and any other information that could be helpfull to identify the issue.
