### ISSUE TITLE
dataTables cell alignment

### ISSUE THREAD

**Issue by danyal14** [puikinsh/gentelella#324]
Hi,

I am using this admin theme and came to point to align cells to left for numeric.

used class="dt-right" but didn't work.

Any help?

**Comment by AndreiCN** [comment]
Hello danyal,

First of all we're glad that you're using our theme. Well from what i see cells are already aligned to the left but if you meant right, you can simply use a rule like : "text-align:right" or you can just use "text-center" class where you need to.
