### ISSUE TITLE
Text Area multi editor not working properly!!!!

### ISSUE THREAD

**Issue by socialinfotech1** [puikinsh/gentelella#325]
When i have use 5-6 Editor in same page its not working correctly its automatic select all editor component when we select one of those and only first editor is working others are not . so please suggest me to update those things

**Comment by AndreiCN** [comment]
Hi socialinfotech,

First of all, we're glad that you're using our theme and about editor we already took care of it so will be available in our feature update.

Regards,
Andrew.

**Comment by itroyal-de** [comment]
There´s an issue with the editor himself too, try to write any words, mark it and click A for coloring this word, and you will see, the menu for colors try to opening but its container ul is empty :( 

... only for your information

Greetz Sascha
