### ISSUE TITLE
button has incorrect margin on form inline

### ISSUE THREAD

**Issue by rafgugi** [puikinsh/gentelella#327]
Bootstrap enable form inline, which input and button and label are in a single line.
Meanwhile gentelella add `margin-bottom: 5px` on `.btn`, which makes button on form inline not equally straight with other elements (input and label). You can see on [gentelella example](https://colorlib.com/polygon/gentelella/form.html#ex3) too.

my solution on my project is
```
  .form-inline .btn {
    margin-bottom: 0;
  }
```

**Comment by AndreiCN** [comment]
Hi rafgugi,

Thanks for the tip, we will take care of it.

Regards,
Andrew.
