### ISSUE TITLE
Date Picker does not work on IE 11

### ISSUE THREAD

**Issue by marlonrsbr** [puikinsh/gentelella#33]
There are date pickers wich doesn´t work on IE 11, There is a solution or ideias to solve that?

when I click on the textbox the calendar does not show itself like on Chrome or Mozilla.

![git](https://cloud.githubusercontent.com/assets/11152914/11452855/c8217a92-95dc-11e5-9f90-fbfb5fccc959.PNG)

**Comment by christianesperar** [comment]
This is working on my end

**Comment by pdvbalaji** [comment]
Hi,
 This is working on my end ,but colors on not coming even I apply css also . Can u help me on that issue
