### ISSUE TITLE
Can you include the sidebar from a separate file without JS loading issues? 

### ISSUE THREAD

**Issue by jdmagic21** [puikinsh/gentelella#333]
Is there a way that I can make the sidebar independent from all the other content pages? I would like to include the sidebar by keeping this code in a separate file however, whenever this happens the Javascript in custom.js does not load properly and I am not able to expand/collapse the sidebar items.  I have noticed that when the sidebar is loaded it loads the content after the execution of the custom.js needed to properly format the sidebar data. 

I have included the sidebar using both Angularjs and JQuery without much luck using the code similar to the below: 

```
<script> 
$('#sidebar').load('includes/sidebar.html'); 
</script> 
```

`<div id="sidebar"></div> `

**Comment by jdmagic21** [comment]
This probably is not the best answer but I moved all of the custom.js code inside of a timeout function and loaded the jquery before this timeout to allow the execution of your code to run after HTML injection. 
```
$('#sidebar').load('includes/sidebar.html');
setTimeout(function(){
your code
}, 0);
```

**Comment by AndreiCN** [comment]
Hi there @jdmagic21 , 

If you want to make the sidebar independent, you can create a "sidebar.js" and move the initialization code there or you can create a "init_sidebar" function and initialize in document.ready.
