### ISSUE TITLE
Gentelella or Gentellela?

### ISSUE THREAD

**Issue by DanAtkinson** [puikinsh/gentelella#340]
This is a really confusing issue, and seems to be [prevalent](https://github.com/puikinsh/gentelella/search?utf8=%E2%9C%93&q=gentellela) across the entire codebase - including the [package.json](https://github.com/puikinsh/gentelella/blob/master/package.json)!

    {
      "name": "gentelella",
      "version": "1.3.0",
      "description": "Gentellela Admin is a free to use Bootstrap admin template",

It seems that the naming of the package can't be agreed upon by the committers.

I'd be happy to do a PR correcting the spelling errors, but I'd rather the package owner chip in and explain which one it should be. :)

Thanks, Dan

**Comment by AndreiCN** [comment]
Hi @DanAtkinson ,

The right package is "Gentelella" https://colorlib.com/polygon/gentelella/index.html , thank you for noticing that, will change it in the next update.

Regards,
Andrew.

**Comment by DanAtkinson** [comment]
Hi @AndreiCN,

The PR I submitted should resolve it.

Thanks, Dan

**Comment by AndreiCN** [comment]
Hi again @DanAtkinson,

Yes, that should do it , thank you !

Cheers,
Andrew.
