### ISSUE TITLE
echarts don't automatically resize

### ISSUE THREAD

**Issue by zbuc** [puikinsh/gentelella#342]
I noticed that on the demo site, the echarts examples don't automatically resize with the browser:

https://colorlib.com/polygon/gentelella/echarts.html

I was able to fix this for my use case by using the following code -- I'm not sure how you would want to integrate it in your demo page, so I am not submitting a pull request:

        var _ = function(chart){
          $(window).on('resize', function(){
            if(chart !== null && chart !== undefined){
                chart.resize();
            }
          });
        }(echartLine);

**Comment by nezaboravi** [comment]
project_detail.html as well

**Comment by AndreiCN** [comment]
Hi @zbuc ,

Those charts should be responsive indeed, will try to find a proper solution for it, thank you for reporting it !
