### ISSUE TITLE
Sumenu labels over footer buttons

### ISSUE THREAD

**Issue by Mubat** [puikinsh/gentelella#346]
When sub-menu expanded on navigation menu, dots of submenu items are over fotter buttons.

Check "settings" button
![](http://joxi.ru/vAWp5zqT5DMRrW.jpg)

**Comment by AndreiCN** [comment]
Hi there @Mubat,

Thank you for noticing that, we'll take care of it as soon as possible.

**Comment by Mubat** [comment]
You are welcome.
