### ISSUE TITLE
Left Menu Fixed issue

### ISSUE THREAD

**Issue by mihaip007** [puikinsh/gentelella#349]
Hello - I have a quick question. I added the class "menu_fixed" and the menu gets fix which is great. But I can't seem to scroll when I expand the menu. It scrolls only the main content. What am I doing wrong?

Thank you in advance

**Comment by AndreiCN** [comment]
Hi @mihaip007 ,

From what I understand "overflow-y:scroll" rule on your sidebar container should do the trick :)

Regards,
Andrew.
