### ISSUE TITLE
Custom.css - Line 14

### ISSUE THREAD

**Issue by bgougent** [puikinsh/gentelella#35]
.right_col{min-height: 1000px;}
What is the reason of this line. 
Needed to comment out or I had with 'Bootstrap-Table' (https://github.com/wenzhixin/bootstrap-table) issues. The problem resulted in a large white space after the footer.

![bootstrap-table](https://cloud.githubusercontent.com/assets/5254383/11615347/678052ac-9c5e-11e5-83d2-9d81612034eb.png)

**Comment by Alex-Nagy** [comment]
Hi,
It's just a break after the table. More so like a design preference. Feel free to adjust it to your needs, remove or decrease.

**Comment by christianesperar** [comment]
This will be fix on PR https://github.com/puikinsh/gentelella/pull/89
