### ISSUE TITLE
Top Fixed menu

### ISSUE THREAD

**Issue by mihaip007** [puikinsh/gentelella#350]
Is there a way to fix the top menu as well?
Thank you...

**Comment by AndreiCN** [comment]
Hi there @mihaip007 ,

For the moment we do not have a fixed top menu version but we have instead fixed footer, therefore you can take a look there and take it as example, should be helpful and easy to implement it.

Cheers,
Andrew.

**Comment by grid-100** [comment]
Try this:

```
.nav-sm .main_container .top_nav,
.nav-md .main_container .top_nav {
    position: fixed;
    right: 0;
    left: 0;
    z-index:4;
}

.nav-md .container.body .right_col,
.nav-sm .container.body .right_col {
    padding-top: 58px;
}
```

**Comment by AndreiCN** [comment]
@mihaip007 you can take this as a solution , @grid-100  thank you for your contribution !
