### ISSUE TITLE
nav bar problem responsive

### ISSUE THREAD

**Issue by mightz1986** [puikinsh/gentelella#352]
Hello,

I'm trying to adjust the `@grid-float-breakpoint:`, so that the `navbar` collapse for screens > 992px.

But unfortunately it doesn't work

I have tried to change the **..\vendors\bootstrap\less\variables.less** file from `sm` to `md` and `lg` or `50000px`:

 `//** Point at which the navbar becomes uncollapsed.`
`@grid-float-breakpoint: @screen-sm-min;`

But the nagivation bar will still be loaded uncollapsed on my iPad.

`body`-tag has the `md`- class:

`<body class="nav-md">`

If I change it manually to `sm` it loads the navbar collapsed everywhere. But I only need it collapsed on my tablet :(

I have used the demo version of the Gentelella Bootstrap, so there are no custom changes.

Could you help me with advice, what I'm doing wrong or what additionally have to be done to achieve this.

Thanks for any help!

Best Regards,

**Comment by AndreiCN** [comment]
Hi there @mightz1986 ,

From what I see your rule might be overwritten from somewhere else, so what you can try is to add a separate rule in your main CSS file (custom.min.css), something like this : @media (max-width: 992px) {
   --- your rule goes here ---
}

I hope it solves your problem,

Regards,
Andrew.

**Comment by AndreiCN** [comment]
Well create one then ( rule ) and force it to behave as yo wish  :)
