### ISSUE TITLE
span styling is too generic

### ISSUE THREAD

**Issue by KrishnaPG** [puikinsh/gentelella#356]
Currently many css rules are using `span` directive directly without any specification, for example:
````
td span {
  line-height: 28px; }

.dropdown-menu.msg_list span {
  white-space: normal; }

.widget_summary .w_right span {
  font-size: 20px; }
````
This is causing problem when using any `span` element for SEO marking purposes.

Please make these `span` based styling rules more specific, perhaps by using `classes` rather than directly the generic tags, such as:
````
td span.height28 {
  line-height: 28px; }

.dropdown-menu.msg_list span.ws {
  white-space: normal; }

.widget_summary .w_right span.fs20 {
  font-size: 20px; }
````

Making these style rules specific to the context (such as adding special classes for that purpose), will make it possible to reuse those tags in user code without having to worry about the baseline theme customization (that are currently creating unwanted side-effects).

**Comment by krzysiekpiasecki** [comment]
Add classes to elements and then your selector will be stronger.


Less strong css selector is - more easy to customize.

**Comment by KrishnaPG** [comment]
Well, unfortunately `span` is not only used for styling, but also for SEO. Consider the below:
````
<td><span itemprop="name">AuthorName</span></td>
````
Right now, the `td span` generic CSS rule is kicking in spoiling the look. Adding class or id, as you suggested, would not help in this case. Note that tags are used for more than styling in HTML, especially in web-components. 

This case is not about "making any selector strong or weak" - this is about "not worrying about the styles when there is no need" (such as the SEO). Your defined style choices are coming in the way of normal tag operations (when they should not be).

For example, your suggestion (adding id or class) works best, if the template were using "more specific selectors" than "generic ones" like it is doing now.

**Comment by AndreiCN** [comment]
Hi @KrishnaPG ,

Thank you for the suggestion, we will take that into consideration :)
