### ISSUE TITLE
How to re-initialize  $SIDEBAR_MENU = $('#sidebar-menu'), after ajax load?

### ISSUE THREAD

**Issue by probaner** [puikinsh/gentelella#357]
I am using ajax to load data into $SIDEBAR_MENU. The DOM is properly/ exactly built,  but $SIDEBAR_MENU does not work. I believe we need to re-initialize the $SIDEBAR_MENU. Can you suggest how to do that?

**Comment by AndreiCN** [comment]
Hi @probaner , 

What could you do there after you receive the data, you should initialize init_sidebar() again.

Best regards,
Andrew.
