### ISSUE TITLE
tables_dynamic overflow in mobile (responsiveness issue)

### ISSUE THREAD

**Issue by MedUnes** [puikinsh/gentelella#358]
There is a responsiveness issue at [this page](https://colorlib.com/polygon/gentelella/tables_dynamic.html)

As you can see in the screenshot below, the Datatables widget overflows the main content section
![image](https://cloud.githubusercontent.com/assets/8580094/21743703/096d35ac-d508-11e6-8cf7-99a9ed8fc164.png)

To reproduce this issue open [this link](https://colorlib.com/polygon/gentelella/tables_dynamic.html
) either in a mobile device or in google chrome and then simulate a mobile device in the inspector (F12)

**Comment by krzysiekpiasecki** [comment]
I have recreated.

**Comment by mahmoud-nb** [comment]
The width of a table can not be less than the width of its columns, so the width of a column can not be less than its contents.
so, In this case, no way to compress the table to take the width of the screen.
I suggest adding a scroll for the div that contains tables

Try to add the "scrollable" class to the div.row that contains a table

`.scrollable{ overflow:auto; }`

**Comment by krzysiekpiasecki** [comment]
Sometimes hiding a columns is also a resolution.

**Comment by MedUnes** [comment]
@mahmoud-nb 
```
#fart_datatable_wrapper > div:nth-child(2)
{
     overflow:auto;
}
```
solved the problem for me.
I guess you can make a pull request for this.

**Comment by MedUnes** [comment]
I hope this patch fixes the issue.
https://github.com/puikinsh/gentelella/compare/master...MedUnes:patch-1#diff-05d2ac1ccad2def099a3cbca60328191

**Comment by MedUnes** [comment]
This is a PR that should patch this issue.

https://github.com/puikinsh/gentelella/pull/359

**Comment by connectnbs** [comment]
You can simply add `style="overflow:auto;"` to solve this if you insist to keep all the rows. or check the resposive datatable in the Gentell Admin theme.

**Comment by AndreiCN** [comment]
Hello there, "overflow:atuo" will solve the problem yep, we'll add it in a future update.
