### ISSUE TITLE
cropping

### ISSUE THREAD

**Issue by Bkoech** [puikinsh/gentelella#36]
The profile page i have changed from html to php and want to upload an image in get an error Parse error. how can solve this?

**Comment by fusiondust** [comment]
Try creating a PHP file with the following contents and see if that works:
<?php
phpinfo();
?>

**Comment by Bkoech** [comment]
all my files are in php they work fine. The profile file works fine it displays all the content i just cant upload a cropped images to the server on upload i get a warning error "parse error"

**Comment by puikinsh** [comment]
Unfortunately, parse errors are not related to this template but your PHP code. 

Here is a great source on PHP parse errors and how you can resolve them: http://stackoverflow.com/questions/18050071/php-parse-syntax-errors-and-how-to-solve-them
