### ISSUE TITLE
RTL Vesion

### ISSUE THREAD

**Issue by softpeterkk** [puikinsh/gentelella#360]
Hi: Thank you for gentelalla, it's really really beautiful and amazing template, but I am really disappointed about RTL version. I hope you will release it soon. I have tried https://github.com/iPazooki/gentelella-RTL but it isn't responsive yet.

**Comment by AndreiCN** [comment]
Hi there @softpeterkk , 

We really appreciate that you like it and thank you for the suggestion, will take that into consideration :)

**Comment by mortezakarimi** [comment]
@softpeterkk Until the official RTL version release you can feel free to use this [Gentelella-rtl](https://github.com/mortezakarimi/gentelella-rtl)
