### ISSUE TITLE
font-awesome problem in firefox.

### ISSUE THREAD

**Issue by zhucui12345** [puikinsh/gentelella#361]
Hello,
gentelella is a great admin dashboard. I like it very much.
But there's one problem.
In firefox, font-awesome icons don't display.
So when I use from maxcdn, it works well.
Kindly solve these problem.(using font-awesome on local host)

Best Regards.
Zhu.

**Comment by AndreiCN** [comment]
Hi there @zhucui12345 , 

font-awesome possibly don't display because you mix the paths there somehow, best solution is to load it from local host, yep.
