### ISSUE TITLE
Two font-awesome folders in vendors folder

### ISSUE THREAD

**Issue by DanAtkinson** [puikinsh/gentelella#364]
I'm not quite sure why, but there are two different versions of font-awesome in the vendors directory.

[/vendors/fontawesome](https://github.com/puikinsh/gentelella/tree/master/vendors/fontawesome) - running 4.5.0
[/vendors/font-awesome](https://github.com/puikinsh/gentelella/tree/master/vendors/font-awesome) - running 4.6.3

It's not immediately clear which one is in use but I would suggest that the folder `fontawesome` is deleted and that `font-awesome` is retained.

Thanks, Dan

**Comment by AndreiCN** [comment]
Hi @DanAtkinson , the right folder is "font-awesome" , thank you for reporting it will delete the other one !

Regards,
Andrew.
