### ISSUE TITLE
How do I edit the CSS files if I want to upgrade SmartWizard to 4.1.2?

### ISSUE THREAD

**Issue by marlonbrand0** [puikinsh/gentelella#365]
Anyone know how I can accomplish this?

**Comment by AndreiCN** [comment]
Hi there @marlonbrand0 , I'm not quite sure what you want to accomplish there, but if you want to update your SmartWizard plugin , all you need to is to get the latest version and place in in your plugin folder and that's it :)

**Comment by marlonbrand0** [comment]
My problem is when I try, it breaks the formatting. Is there something I need to be doing in the custom.scss file?

**Comment by AndreiCN** [comment]
Is no need to make modifications in custom.scss file , can you provide a screenshot or something to see better what you want to accomplish there ?

**Comment by lolingz02** [comment]
@marlonbrand0 I think your problem was already addressed here -https://github.com/puikinsh/gentelella/issues/335. Unfortunately the author of https://github.com/mstratman/jQuery-Smart-Wizard hasn't responded to my problem yet. :(
