### ISSUE TITLE
validator 版本过低在chrome浏览器出现多个提示框bug

### ISSUE THREAD

**Issue by neilrencn** [puikinsh/gentelella#366]
validator的版本过低在chrome浏览器出现多个提示框的bug。
修正方法：下载最新版的[Validator v2.0.3](https://github.com/yairEO/validator)
具体使用方法参考Validator文档

修改custom.scss文件中的 item样式名字为field

**Comment by AndreiCN** [comment]
Hi there @neilrencn , 

English please ? :)

**Comment by neilrencn** [comment]
Hi @AndreiCN
english：
Low version of the validator will have a BUG in chrome
Need to update to the Validator v2.0.3
Need to edit the style name “item” to “field” of the  custom.scss file

**Comment by AndreiCN** [comment]
Hi again @neilrencn ,

Thank you for reporting it, we will take care of it in the next update !

Regards,
Andrew.
