### ISSUE TITLE
timePicker not working

### ISSUE THREAD

**Issue by frederic-loui** [puikinsh/gentelella#368]
Hi, I'm not sure if this has been added but time is not showing up in the "date field". (Only date is displayed) Time  is displayed in the datepicker though. I know this is a duplicate of issue #244. BUt i'm not sure about the outcome. The ticker says refer to PR#304 but i'm not sure if this has been integrated since then. Sorry in advance for the potential duplicate.

**Comment by AndreiCN** [comment]
Hi there @frederic-loui ,

For to moment we do not have a time picker , but we will take this into consideration, thank you !
