### ISSUE TITLE
Is the modal formatting supposed to break when you change the data-target?

### ISSUE THREAD

**Issue by marlonbrand0** [puikinsh/gentelella#369]
I'm trying to run a modal through a foreach loop like shown [in this post](https://laracasts.com/discuss/channels/laravel/load-data-in-foreach-loop-with-a-jquery-modal), but it's breaking my formatting for my head and body of the modal.
![without change](https://cloud.githubusercontent.com/assets/23091844/22156911/4dd5fe5a-df70-11e6-9a06-04116f045ef2.png)
![with change](https://cloud.githubusercontent.com/assets/23091844/22156913/4e3f6b7e-df70-11e6-8bfd-c4432df75178.png)

**Comment by AndreiCN** [comment]
Hi there @marlonbrand0 ,

The example shown by you is used in a different way comparing to this one used be bootstrap and also us. If you want to implement it like that , take a closer look and take it step by step :)

**Comment by marlonbrand0** [comment]
`<div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel2">
                    <div class="alert alert-danger">DELETING THIS AFFECTS <br/>CLIENT PROFILES </br>WITH THIS SELECTION</div>
                </h4>
            </div>
            <div class="modal-body">
                <h4>Are you sure?</h4>
                <p>Deleting this will remove this entry from all client profiles with this selected</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                <a href="<?=base_url() ."/medIss/delete/".$med_issue['med_id']; ?>" class="btn btn-danger" role="button">Delete</a>
            </div>
        </div>
    </div>
</div>`

All posts I see implement using a different modal id. Is it alright if you tell me which part is not implementing it the bootstrap way?

**Comment by AndreiCN** [comment]
First thing would be that uses inline JS, try to use it exactly by default changing just texts if you want to run like our example, you find it in general_components.html page,

**Comment by marlonbrand0** [comment]
I updated my code. Forgot to include the top div hahaha
