### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by krzysiekpiasecki** [puikinsh/gentelella#370]
What are the release plans? Are there any roadmap or something similar? @christianesperar released last tag on Jun 1, 2016

PS @AndreiCN Don't close the ticket without reasonable answer.

**Comment by AndreiCN** [comment]
Hi there @krzysiekpiasecki ,

I know it took a while since the last update was released, but actually we are working on a new one, will be ready quite soon ([Development](https://github.com/puikinsh/gentelella/pulls) branch - fixes & improvements committed) , thank you !

Best wishes,
Andrew.
