### ISSUE TITLE
This template is compatilble with jquery 3?

### ISSUE THREAD

**Issue by hugogoncalves** [puikinsh/gentelella#379]

**Comment by krzysiekpiasecki** [comment]
Currently it resolves to "v2.2.4" so it's not compatible.

**Comment by GWSB** [comment]
Any chance of an upgrade coming?

**Comment by AndreiCN** [comment]
Hi there @GWSB , 

We will take it into consideration, thank you !

**Comment by krzysiekpiasecki** [comment]
@hugogoncalves, please close the ticket If you don't have any further questions.
