### ISSUE TITLE
Dropdowns don't work

### ISSUE THREAD

**Issue by ylecuyer** [puikinsh/gentelella#381]
Go to [https://colorlib.com/polygon/gentelella/form_buttons.html](https://colorlib.com/polygon/gentelella/form_buttons.html)

The Button Dropdown example doesn't work

**Comment by krzysiekpiasecki** [comment]
I'm able to reproduce at 1.4.

**Comment by AndreiCN** [comment]
That issue was solved some time ago and since nobody had nothing to add on this we will just close it for now.
