### ISSUE TITLE
How can I make it working with sails ? ( or can I ?)

### ISSUE THREAD

**Issue by orhanozdemir** [puikinsh/gentelella#385]
Normally, I'm an iOS developer but i need an admin panel for my mobile app and i want to use this template. Unfortunately I'm not so comfortable with JS. I have a working web service with sails.js. I just need to use this template as views of my web service. Any guidance appreciated.

**Comment by AndreiCN** [comment]
Hi @orhanozdemir , 

Do you still encounter this issue , if you do, can you please provide us more details about it in order to help you ?

**Comment by AndreiCN** [comment]
Well, we will close this for now but feel free to reopen it if you need to, sharing some more details about it in order to try solve this out.
