### ISSUE TITLE
gentelella production html generation question

### ISSUE THREAD

**Issue by mwisneski** [puikinsh/gentelella#387]
Hi,

Apologies if this is a newbie question. Are the html files located in dir "production" generated from source files containing partial html? E.g. the left menu html which is included in /production/*.html

If so, then are the source html files available for use? How do you generate the html? (gulp?) 

I would like to generate a static web site for the purpose of a quick demo/feedback for an idea.

**Comment by krzysiekpiasecki** [comment]
I'm sure that the pages ares static because pull requests are merged directly into html files.

**Comment by krzysiekpiasecki** [comment]
@mwisneski, please close the ticket If you don't have any further questions.
