### ISSUE TITLE
Problem with Multilevel Menus

### ISSUE THREAD

**Issue by JuniorZancan** [puikinsh/gentelella#388]
There's an onclick event conflict on the submenus.

How to reproduce:

1. Collapse the sidebar (clicking on the upper icon)
2. One click on "Multilevel Menu"
3. One click on the second "Level One" (the one with the submenu)

The entire menu close itself instead of ignore the click event.

**Comment by krzysiekpiasecki** [comment]
Reproduced.

**Comment by AndreiCN** [comment]
Hi @JuniorZancan ,

Thank you for reporting this, we will take care of it !

Cheers.
