### ISSUE TITLE
input submit button is removed in request when using validator

### ISSUE THREAD

**Issue by andMat** [puikinsh/gentelella#389]
If more then one button/input is used in a form it is not possible to use the validator.js

`<input type="submit" class="btn btn-success" name="update" value="Button1"/>
<input type="submit" class="btn btn-danger" name="delete" value="Button2"/>`

The following "update" and "delete" will never be passed to the request in a servlet when using validator.js script. This must be disable in order to pass the values to request context.

**Comment by AndreiCN** [comment]
Hi there @andMat ,

A form should have just one "sumbit" button, it makes no sense to have more of them.
Cancel button has "submit" type on it and that should not be there, it's there in the production version too, we'll solve that as soon as possible.

Best regards !
