### ISSUE TITLE
Second problem with Multilevel Menus

### ISSUE THREAD

**Issue by JuniorZancan** [puikinsh/gentelella#391]
There's another problem with the Multilevel Menus.

**How to reproduce:**

1. With the side-bar at full size, select (and open) a Multilevel Menu;
2. Collapse the side-bar clicking on the top button;
3. Uncollapse the side-bar;

All the sub-menus from the Multilevel Menu will be open.

**Comment by AndreiCN** [comment]
Hi again @JuniorZancan ,

Thank you for reporting that one too, we will find a solution also for this one, cheers.
