### ISSUE TITLE
Sidebar-menu does not display

### ISSUE THREAD

**Issue by markceron** [puikinsh/gentelella#392]
When creating a multilevel menu, do not display the child menu

I have reviewed the custom file, and apparently everything is fine.

The project is being developed in MVC ASP.NET

Help me
![slide menu](https://cloud.githubusercontent.com/assets/1226168/22515209/52b2cab6-e867-11e6-9109-759a6ee81ed4.png)

**Comment by AndreiCN** [comment]
Hi there @markceron ,

From my point of view it seems to be a structure problem there, can you provide your structure here to see exactly what's happening ?

**Comment by markceron** [comment]
I already did it, what I did was change the statements.

 $('#sidebar-menu').find('a').on('click', function (ev) {
        var $li = $(this).parent();

        if ($li.is('.active')) {
            $li.removeClass('active active-sm');
            $('ul:first', $li).slideUp(function () {
                setContentHeight();
            });
        } else {
            // prevent closing menu if we are on child menu
            if (!$li.parent().is('.child_menu')) {
                $('#sidebar-menu').find('li').removeClass('active active-sm');
                $('#sidebar-menu').find('li ul').slideUp();
            }

            $li.addClass('active');

            $('ul:first', $li).slideDown(function () {
                setContentHeight();
            });
        }
    });

    // toggle small or large menu
    $('#menu_toggle').on('click', function () {
        if ($('body').hasClass('nav-md')) {
            $('#sidebar-menu').find('li.active ul').hide();
            $('#sidebar-menu').find('li.active').addClass('active-sm').removeClass('active');
        } else {
            $('#sidebar-menu').find('li.active-sm ul').show();
            $('#sidebar-menu').find('li.active-sm').addClass('active').removeClass('active-sm');
        }

        $BODY.toggleClass('nav-md nav-sm');

        setContentHeight();
    });
