### ISSUE TITLE
Sidebar sits on top of modal (wrong z-index)

### ISSUE THREAD

**Issue by sfeher-paymentus** [puikinsh/gentelella#393]
see attached screenshot.

![image](https://cloud.githubusercontent.com/assets/25514560/22565763/402f6156-e957-11e6-8266-c6ab133c2614.png)

**Comment by AndreiCN** [comment]
Hi @sfeher-paymentus ,

Thank you for reporting this issue, we will handle it as soon as possible !

Regards,
Andrew.
