### ISSUE TITLE
required

### ISSUE THREAD

**Issue by Tithus** [puikinsh/gentelella#394]
class required not found and more class is not found

**Comment by AndreiCN** [comment]
Hi there @Tithus ,

Can you please be more precise ? :)

**Comment by Tithus** [comment]
These and other classes do not exist.

![class-no-exist](https://cloud.githubusercontent.com/assets/25514772/22865503/c471f832-f133-11e6-86e6-5896c1dcf6a1.png)
![class-no-exist-2](https://cloud.githubusercontent.com/assets/25514772/22865504/c4747e9a-f133-11e6-89ac-3a16a3aa2b9f.png)

**Comment by AndreiCN** [comment]
Hi again @Tithus ,

Both classes ( column-title, required ) are used in javascript.
