### ISSUE TITLE
Issue on Demo Template

### ISSUE THREAD

**Issue by lxnx0** [puikinsh/gentelella#396]
Hi all,

I just want to report on the finding of merging HEAD on demo site, form page. 

Following is the screenshot 

<img width="1436" alt="screen shot 2017-02-04 at 00 26 13" src="https://cloud.githubusercontent.com/assets/17823404/22599127/b3a478f0-ea70-11e6-8bfe-6e763a34344d.png">

**Comment by KhanMaytok** [comment]
Form page is broken too. Don't initialize any plugin

https://colorlib.com/polygon/gentelella/form.html

**Comment by AndreiCN** [comment]
Hi @lxnx0 ,

We just must to update the live version too, if you look in the downloaded package, you'll see that form page it's working just fine.

**Comment by AndreiCN** [comment]
Hi there @KhanMaytok ,

I don't know where are you loading it, but form page it's working just fine, all of them (plugins) are initialized. Here's a quick example :

![2017-02-06_104047](https://cloud.githubusercontent.com/assets/20791686/22639858/c5d50456-ec58-11e6-8e08-3e4dc1be267e.jpg)

**Comment by KhanMaytok** [comment]
Look the select2 items. They are not initialized on the page
