### ISSUE TITLE
Bug at dynamic table (production)

### ISSUE THREAD

**Issue by NelsonPRSousa** [puikinsh/gentelella#397]
Hi guys,

Take a look at: https://colorlib.com/polygon/gentelella/tables_dynamic.html

"Plus Table Design" ->There is a DataTable where you can select all rows... That doesn't work. No rows are selected.

Also, there are some of them that do not have the same 'style' for the checkbox.

![image](https://cloud.githubusercontent.com/assets/8364345/22644555/fdb47120-ec5a-11e6-91dd-45a26c10e544.png)

Thank you for your work

[EDIT] I tested on Chrome, IE9 and Edge.

**Comment by NelsonPRSousa** [comment]
@AndreiCN What that label means? I've read github's docs and didn't get it right.
Thank you for your work!

**Comment by funilrys** [comment]
@NelsonPRSousa It's generally used to categorize issue so it's simple to track/implement them but maybe @AndreiCN and his team have another use of them so please correct me if I'm false :smile:

**Comment by NelsonPRSousa** [comment]
@funilrys & @AndreiCN 
I know it's used to categorize, just don't know what that label means here :)
Thank you!

**Comment by AndreiCN** [comment]
@NelsonPRSousa we used "enhancement" label to mark tickets that are actual suggestions concerning our current code or tickets marking improvements/solving problems.

**Comment by NelsonPRSousa** [comment]
@AndreiCN Okay, thank you. I thought this was a bug...

**Comment by funilrys** [comment]
@AndreiCN Please close this

**Comment by AndreiCN** [comment]
Closed.
