### ISSUE TITLE
Demo with conflictions.

### ISSUE THREAD

**Issue by projects-logiciel** [puikinsh/gentelella#402]
Remove confliction from the demo template.
https://colorlib.com/polygon/gentelella/form.html
<<<<<<< HEAD ======= >>>>>>> refs/remotes/puikinsh/Development

**Comment by kennell** [comment]
LGTM, was about to submit the same PR

**Comment by funilrys** [comment]
@kennell Good question, 
I don't really know if @AndreiCN and his team take care of the PR ... It's just a line of code :sweat_smile:
