### ISSUE TITLE
Problem with datepicker range

### ISSUE THREAD

**Issue by royrfc** [puikinsh/gentelella#403]
when i try the datepickerrange,  works fine.
but when you scale the resolutions to mobile, or try to use it from a mobile (i use Samsung s7), the calendar get one up and one below. but the one up does not work, you can not clic in any button
jut work the calendar below.

i also try in google chrom from my developing machine, using the developer tools and put the resolution for am iPhone and do the same.
the first calendar does not work.

![image](https://cloud.githubusercontent.com/assets/25751566/22897520/58e52e6e-f1fa-11e6-910e-22c29846c1da.png)

thanxs

**Comment by AndreiCN** [comment]
Hi,

Thank you for pointing this out, I will investigate this and get back with a solution.

**Comment by juliolopezbarajas** [comment]
Hi, thanks in advance for your support.

I don't know what did i do wrong, but when i changed the name of the data range picker it stop working. It's name in the file "form_advanced.html" is reservation, when i used in my files it stop working, so i thought that i made a mistake, and after many tries without success, i changed the name in the "form_advanced.html" file and it stop working too!.

I'm wondering why i cannot change the name of this item?

Thank you!

**Comment by BenderR000** [comment]
How do I initialise the daterangepicker so that it starts with NO dates selected please? I have tried value="" and value ="-". 

Please advise.

Thanks.

**Comment by AndreiCN** [comment]
related to #663 , just approved a PR with it.

**Comment by BenderR000** [comment]
So this has been done? What files do i need to get to get this functionality and how do i set the daterangepicker so that it starts with NO dates selected please?
