### ISSUE TITLE
Angular.js Integration with NgRoute

### ISSUE THREAD

**Issue by hrizvi** [puikinsh/gentelella#405]
Hi,
I am using your template for my project... when I try integrate Angular.js Routing then UI css behaves strange, it works perfectly if i remove ngRoute but in my application I need to use ngRoute. you can see the result in screen short which I took.. plus signUp page doesn't even appear too 
![1](https://cloud.githubusercontent.com/assets/1534450/22929542/ed92edb0-f2c4-11e6-9d54-53bce6080087.JPG)

**Comment by hrizvi** [comment]
Hi, 

I just came to know about the problem but couldn't figure out how to solve it..... 
The issue is that when I try to use ngRoute of Angular so my login Template behaves as a div and and the class login doesn't works in the div as body class overrides it. I have the screen shot to show you more clearly 
![2](https://cloud.githubusercontent.com/assets/1534450/22968117/d8044d38-f371-11e6-9c73-83f101f57584.JPG)

**Comment by atais** [comment]
http://stackoverflow.com/questions/20943820/angularjs-changing-body-class-using-global-variable

**Comment by AndreiCN** [comment]
Unfortunately we do not have a AngularJS version for this and since you got some guidance we will close this ticket for now.
