### ISSUE TITLE
where is code for init_cropper ? 

### ISSUE THREAD

**Issue by jayjlawrence** [puikinsh/gentelella#409]
Hi there

I found a tiny bug in the init_cropper function but cannot locate the source to submit a pull request.

And on a related note, its not really clear how to 'build' the custom.* assets - how do you build these? gulp?

Thanks
Jay

**Comment by AndreiCN** [comment]
Hi there @jayjlawrence ,

Can you please be more precise on that bug on init_cropper ? 
Yep, we use gulp, you have it in the package (gulpfile.js)
