### ISSUE TITLE
What is the relationship with inspinia admin?

### ISSUE THREAD

**Issue by yokas** [puikinsh/gentelella#41]
https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S

It's very similar. is inspinia admin based on gentelella? or the opposite?

Is it ok to use gentelella in commercial site?

**Comment by puikinsh** [comment]
Color scheme for both ar similar but thats where the similarities ends. INspinia is far more advanced with dozens of libraries included and also they have angular, ruby on rails verisons and much more. This is a plain HTML template and a very simple one. If simplicity is the thing you are looking for then go with this. If Angular and other owesome thins is for you then go with Inspinia.

Now that I have taken over development for this template you can finally expect new library introduction, bug fixes and other updates.

**Comment by yokas** [comment]
Thank you very much. Seems Inspinia is not free, although I can find a MIT licensed Inspinia in github, it confuses me. 
And gentelella is also MIT license. As long as there's no license issue, i will go with gentelella.
Thanks for your efforts :)

**Comment by puikinsh** [comment]
Templates can be licensed under MIT and sold, that's no a problem at all. Because support is what you get when going for a paid version.
