### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by LouisOuellet** [puikinsh/gentelella#410]
Hi,
I am new to bootstrap and found your theme which I have to say looks amazing for my needs. The only issue I have is when I try the demo page (once douwnloaded) all the icons are not showing. I looked around on the online demo and it seems that the icons are loaded from a wordpress backend. I would like to use my own backend, therefor is there a way to load those icons without wordpress ?

**Comment by draecko** [comment]
All icons are either glyphicons which are included in the bootstrap css, or Font-Awesome icons which are in their own font-awesome css. I don't see any icons using static images, so be sure to include all the required css files in your html.

**Comment by LouisOuellet** [comment]
Thanks for the reply, I actually found my issue later, forgot to right it down here. But I was initially running the pages directly in the browser. Once I put all the code on a LAMP server, the icons appeared. As I am new to bootstrap and themes coded like this, I wonder if putting all those codes in a parent folder wouldn't break the site once I modify apache to display the project folder directly instead of the entire parent directory. I'll have a look at this later and post the results. Unless someone has the answer already :P
