### ISSUE TITLE
Datetime picker

### ISSUE THREAD

**Issue by zarulizham** [puikinsh/gentelella#411]
Is there any chance I can get datetime picker? Not only date picker.

**Comment by AndreiCN** [comment]
We will take this in consideration, thank you !

**Comment by William-H-M** [comment]
Hi, @AndreiCN I've been using this library for a while for myself and the DateTimePicker I'm using is the one of [eonasfdan](https://github.com/Eonasdan/bootstrap-datetimepicker) and it fit quite well for this template

**Comment by AndreiCN** [comment]
Hi @William-H-M ,

Sounds really good, would you make a PR for this ?

**Comment by zarulizham** [comment]
Thank you 💞
