### ISSUE TITLE
Datapicker Format

### ISSUE THREAD

**Issue by nicktric** [puikinsh/gentelella#412]
Can i change the date format to dd/MM/yyyy instead of MM/dd/yyyy ?

**Comment by pearlus** [comment]
locale: {format: "MM-DD-YYYY"}

**Comment by nicktric** [comment]
HI

            Is this js or css file setting ?

Thanks
Nick

**Comment by pearlus** [comment]
http://lmgtfy.com/?q=daterangepicker+locale

**Comment by nicktric** [comment]
HI

                Yes! It's work . Thank You so much !

Thanks
Nick

**Comment by AndreiCN** [comment]
Hello there,

Since you already have a solution for this, we will just close this ticket for now :)
