### ISSUE TITLE
Sidebar can't be click and chart not appear after implement AngularJS

### ISSUE THREAD

**Issue by faizfizy** [puikinsh/gentelella#413]
I'm starting a new AngularJS project using this template. However, after implement ngView & ngInclude, the sidebar and chart on index.html is not working.

What am I missing?

More info: http://stackoverflow.com/questions/42501688/nginclude-not-loading-script-from-index-html-angularjs

**Comment by mlynariev** [comment]
@faizfizy Did you find the answer?

**Comment by AndreiCN** [comment]
Well unfortunately we do not have a AngularJS version for this and since nobody came with a solution until now we will close this for now.
