### ISSUE TITLE
validator for form submit - integrate with AngularJs

### ISSUE THREAD

**Issue by huatoanduong** [puikinsh/gentelella#416]
Dear Mr,

I very love your work about this admin template, it help me alot.

But I just found one small problem about integrate with AngularJs:
Form always submit even with angular ng-submit. After hours testing over and over again, I found out that there is one method in custom.js, function init_validator ():

      $('form').submit(function(e) {
        e.preventDefault();
        var submit = true;

        // evaluate the form using generic validaing
        if (!validator.checkAll($(this))) {
          submit = false;
        }

        if (submit)
          this.submit();

        return false;
		});
	  
	  };

This code cause form unexpectedly submit after developer handle it with ng-submit.
Can you have any idea about that to integrate with angularjs?

Thanks,

**Comment by SamMousa** [comment]
It seems this library is used for form validation. 
https://github.com/yairEO/validator
Check their docs to find out if / how to integrate it with Angular.

**Comment by AndreiCN** [comment]
Since you have a solution we will close this issue just for now, you can reopen it anytime though :)
