### ISSUE TITLE
[Question] Why my left side menu has some `<li>` opened and other closed ?

### ISSUE THREAD

**Issue by JeromeVi** [puikinsh/gentelella#419]
Hi, 
first thank you for your work ! 

I have used your template and I'm wondering why I have this behaviour:
<img width="282" alt="capture d ecran 2017-03-08 a 10 57 40" src="https://cloud.githubusercontent.com/assets/22610050/23699053/1480a612-03ee-11e7-9956-cbd89ef2f5d5.png">

By default when I do a refresh this 2 menu items are opened... Where is it make ? In `custom.js` I guess but I don't find anything that could make this behaviour

Thank you for your help

**Comment by sabueso** [comment]
@JeromeVi  Maybe you cloned the first "li", rename it, and both were with "active" class?

**Comment by JeromeVi** [comment]
@sabueso  yes they had the "active" class, I try to rename the `<li>`

**Comment by JeromeVi** [comment]
It's because I do " `href="/"` " oh no :'( 

Do you have an idea how could I modify this ? Because when I click on the 2 buttons I want to go the the home page who is "/"

**Comment by AndreiCN** [comment]
Hi @JeromeVi,

Still have that issue ? If you do, from what I see you must write your path there ( href="index.html" )

**Comment by JeromeVi** [comment]
@AndreiCN  no I don't have this issue but yes that was the solution I used
