### ISSUE TITLE
How to select a daterangepicker design?

### ISSUE THREAD

**Issue by dawivan** [puikinsh/gentelella#423]
How can I select the design I want to use from daterange picker?

I am trying this:

$('.datepicker').daterangepicker({
            singleDatePicker: true,
            singleClasses: 'picker_2'
        });

But this dont work...

**Comment by AndreiCN** [comment]
You must use a mix o options there, [this](http://www.daterangepicker.com/) might help you out, good luck !

**Comment by AndreiCN** [comment]
We will close this ticket for the moment but feel free to reopen it whenever you want :)
