### ISSUE TITLE
div named stepContainer appears out of nowhere

### ISSUE THREAD

**Issue by SehgalDivij** [puikinsh/gentelella#426]
I am using the smart wizard and I have a single form throughout the steps, after which I submit the form when the finish button is pressed.

In each step, an extra div named stepContainer appears out of nowhere which I cannot track the origins of.

I am using this along with Angularjs for the SPA architecture, but this doesn't seem like an angular-induced bug.

While we are at it, what would be a nice WYSIWYG editor apart from the one present in theme. One which allows me to view the source as well as WYSIWYG presentation of content along with more styling available for content.

**Comment by AndreiCN** [comment]
Hi there @SehgalDivij,

Do you still have that issue ? If you d, can you please provide some screenshots, maybe som code samples in order to help you out ?

Also thank you for the sugestion we will take that into consideration.

**Comment by SehgalDivij** [comment]
Hi.
Sorry I didn't see your mail.
That issue was worked around.
Thanks though :)

On 01-Jun-2017 12:45 AM, "AndreiCN" <notifications@github.com> wrote:

Hi there @SehgalDivij <https://github.com/sehgaldivij>,

Do you still have that issue ? If you d, can you please provide some
screenshots, maybe som code samples in order to help you out ?

Also thank you for the sugestion we will take that into consideration.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/puikinsh/gentelella/issues/426#issuecomment-305288537>,
or mute the thread

**Comment by AndreiCN** [comment]
Happy to hear that :)
