### ISSUE TITLE
Version 1.4.0 not available on npm 

### ISSUE THREAD

**Issue by ptournem** [puikinsh/gentelella#427]
Hi, 

I'm trying to use gentelella with npm and webpack but when I installed it and then tried to compile it, I had problems with the file custom.scss which contains references to images which are not in the repository. 

It looks like the version 1.4.0 fixed that problems. But I can't install it with npm. 

When I force the gentelella version to 1.4.0 in my package.json, npm says this version doesn't exist.

Could you add this version so that I can install it with npm ? 

Thanks,

Paul

**Comment by c5creative** [comment]
Indeed, this would be great. Much obliged!

**Comment by nicolaspayot** [comment]
Hi, you can also directly fetch v1.4.0 from github via npm by specifying the release commit: 
`npm install --save puikinsh/gentelella#3448fdfdf16a41707d6e2a8154d592a88d85c41c`
