### ISSUE TITLE
Problem with fixed side bar in small devices

### ISSUE THREAD

**Issue by sunnysharma03** [puikinsh/gentelella#430]
![image](https://cloud.githubusercontent.com/assets/22542019/24049688/ca4d6a46-0b52-11e7-8704-2eb7badb1053.png)

The multilevel menus are getting out of the window screen when I'm using it with fixed sidebar and I am not able to scroll and select option , so can u please give a solution for this problem.

**Comment by AndreiCN** [comment]
Hi there @sunnysharma03 ,

Can you provide a sample from your code ?

**Comment by sunnysharma03** [comment]
<body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col menu_fixed">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.php" class="site_title"><i class="fa fa-circle-o-notch"></i> <span>DigiLock RJIT !</span></a>
            </div>
This is my body section where I fixed the side bar and this is my menu in sidebar

<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>Menu</h3>
                <ul class="nav side-menu">
                  <li><a href="index.php"><i class="fa fa-home"></i> Home </a></li>
                  <li><a><i class="fa fa-edit"></i> Details <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                       <li><a href="details.php">General Detail</a></li>
                      <li><a href="edit_details.php">Edit Detail</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-envelope-open"></i> Email <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                    	<li><a>Student<span class="fa fa-chevron-down"></span></a>
                          <ul class="nav child_menu">
                      		<li><a href="single_email.php">Single</a></li>
                      		<li><a href="batch_email.php">Batch</a></li>
                      		<li><a href="select&send_mail.php">Select & Send</a></li>
                      		<li><a href="filter_mail.php">Query</a></li>
                    	  </ul>
                  		</li>
                        <li><a>Professor<span class="fa fa-chevron-down"></span></a>
                          <ul class="nav child_menu">
                      		<li><a href="single_email_professor.php">Single</a></li>
                      		<li><a href="batch_email_professor.php">Batch</a></li>
                      		<li><a href="select&send_mail_professor.php">Select & Send</a></li>
                    	  </ul>
                  		</li>
                        <li><a href="single_email_principal.php">Principal</a></li>
                      	<li><a href="single_email_views.php">Other Departments</a></li>
                        <li><a href="single_email_head.php">H.O.D's</a></li>
                     </ul>
                   </li>
                  <li><a><i class="fa fa-commenting"></i> SMS <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                    	<li><a>Student<span class="fa fa-chevron-down"></span></a>
                          <ul class="nav child_menu">
                      		<li><a href="single_sms.php">Single</a></li>
                      		<li><a href="batch_sms.php">Batch</a></li>
                      		<li><a href="select&send_sms.php">Select & Send</a></li>
                      		<li><a href="filter_sms.php">Query</a></li>
                          </ul>
                       </li>
                       <li><a>Professor<span class="fa fa-chevron-down"></span></a>
                          <ul class="nav child_menu">
                      		<li><a href="single_sms_professor.php">Single</a></li>
                      		<li><a href="batch_sms_professor.php">Batch</a></li>
                      		<li><a href="select&send_sms_professor.php">Select & Send</a></li>
                    	  </ul>
                  	   </li>
                       <li><a href="single_sms_principal.php">Principal</a></li>
                       <li><a href="single_sms_views.php">Other Departments</a></li>
                       <li><a href="single_sms_head.php">H.O.D's</a></li>
                    </ul>
                  </li>
                  <li><a href="qr_section.php"><i class="fa fa-qrcode"></i> QR Code </a></li>
                  <li><a><i class="fa fa-gitlab"></i> Profiles<span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                    	<li><a href="profiles_students.php">Students</a></li>
                    	<li><a href="profiles_heads.php">Professor's & head's</a></li>
                    </ul>
                  </li>
             <li><a><i class="fa fa-address-book-o"></i> Contact | Data <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      	<li><a>Student<span class="fa fa-chevron-down"></span></a>
                          <ul class="nav child_menu">
                          	<li><a>Graduate<span class="fa fa-chevron-down"></span></a>
                          		<ul class="nav child_menu">
                            		<li class="sub_menu"><a href="contact_student_single_grad.php">Single</a>
                            		</li>
                            		<li><a href="contact_student_batch_grad.php">Batch</a>
                            		</li>
                            		<li><a href="contact_student_semester_grad.php">Semester</a>
                            		</li>
                            		<li><a href="contact_student_query_grad.php">Query</a>
                            		</li>
                                 </ul>
                              </li>
                              <li><a>Post Graduate<span class="fa fa-chevron-down"></span></a>
                          		<ul class="nav child_menu">
                            		<li class="sub_menu"><a href="contact_student_single_pg.php">Single</a>
                            		</li>
                            		<li><a href="contact_student_batch_pg.php">Batch</a>
                            		</li>
                            		<li><a href="contact_student_semester_pg.php">Semester</a>
                            		</li>
                            		<li><a href="contact_student_query_pg.php">Query</a>
                            		</li>
                                 </ul>
                              </li>
                          </ul>
                        </li>
        
                      <li><a>Professor<span class="fa fa-chevron-down"></span></a>
                      	<ul class="nav child_menu">
                          <li class="sub_menu"><a href="contact_professor_single.php">Single</a>
                          </li>
                          <li><a href="contact_professor_batch.php">Batch</a>
                          </li>
                          <li><a href="contact_professor_query.php">Query</a>
                          </li>
                      	</ul>
                      </li>
                      <li><a href="contact_hod.php">Head of Department's</a></li>
                      <li><a href="contact_developers.php">Developer</a></li>
                    </ul>
                  </li>
                  
                </ul>
              </div>
            </div>

**Comment by AndreiCN** [comment]
Unfortunately your URL it doesn't work..

**Comment by sunnysharma03** [comment]
I edited my last comment !

**Comment by AndreiCN** [comment]
You're using a wrong structure, look over sidebar ( HTML structure first ) and take that as example, it's quite simple.

**Comment by sunnysharma03** [comment]
but I have used the code from your site:
https://colorlib.com/polygon/gentelella/fixed_sidebar.html

**Comment by AndreiCN** [comment]
Well from what I see the sidebar it's working just fine ( live version ), you certainly doing something wrong there. Like a debugging solution, try to look again an take the the same code from the main package and remove/add as you need.
