### ISSUE TITLE
Demo issue

### ISSUE THREAD

**Issue by umpirsky** [puikinsh/gentelella#431]
There is `<<<<<<< HEAD ======= >>>>>>> refs/remotes/puikinsh/Development ` on https://colorlib.com/polygon/gentelella/form.html

![screenshot from 2017-03-18 09-11-17](https://cloud.githubusercontent.com/assets/208957/24070307/f27cdffc-0bba-11e7-9b15-312ec9b967dc.png)

**Comment by funilrys** [comment]
Fixed with #404

**Comment by funilrys** [comment]
@puikinsh Time to merge to the website :wink:

**Comment by krzysiekpiasecki** [comment]
#404 merged ...

**Comment by AndreiCN** [comment]
Was already merged, we also need to update the live version.
