### ISSUE TITLE
tile-stats + nav ul visualization issue

### ISSUE THREAD

**Issue by rosencruetz** [puikinsh/gentelella#432]
Hello to everyone, I have 2 problems into the navbar of gentelella admin theme.
The issue is concerning dashboard n. 2
1) icon into tile-stats visualization.

![issue1](https://cloud.githubusercontent.com/assets/10851810/24082730/a7d46ca2-0cca-11e7-8c05-987d0e8ef44b.png)

2)  ul list into nav tag, the message box li in particular.
![issue2](https://cloud.githubusercontent.com/assets/10851810/24082756/e1a316f4-0cca-11e7-8e5d-00d998a21892.png)

1) why does chevron icon is so large and outside the box??
2) why does msg box li is less tall then user one

Code for 1st issue:
```
<div class='row top_tiles'>
	<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
		<div class="tile-stats">
			<div class="icon"><i class="fa fa-chevron-left"></i>
			</div>
			<div class="count">15</div>
			<h3>Subscriptions</h3>
			<p>Number of users</p>
		</div>
	</div>
</div>
```

Code for 2nd issue:
```
<ul class="nav navbar-nav navbar-right">
    <li id='menu_li' class="">
        <a id='menu_a' class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
	    <img src="images/user.jpg" alt="no_user">myuser
            <span class=" fa fa-angle-down"></span>
	</a>
	<ul class="dropdown-menu dropdown-usermenu pull-right">
	    <li><a href=""> Profile</a></li>
	    <li><a href=""><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
	</ul>
    </li>
    <li id='exp1' role='presentation' class='dropdown'>
	<a id='exp2' class='dropdown-toggle info-number' data-toggle='dropdown' aria-expanded='false'>
		<i class='fa fa-envelope-o'></i>
		<span id='badge_num' class='badge bg-green'>
		</span>
	</a>
	<ul id='menu1' class='dropdown-menu list-unstyled msg_list' role='menu'>
            <!-- php <li> generation code here -->
	</ul>
    </li>
</ul>

```

Thanks

**Comment by AndreiCN** [comment]
Hi there @rosencruetz,

We will take those one by one : 

1. It seems to me that's a CSS problem there, try to investigate with some tool like firebug where that size come from.

2. check the height of that message block and make it auto.

**Comment by AndreiCN** [comment]
We will close this ticket for now, but feel free to reopen it whenever you want :)
