### ISSUE TITLE
nested x_panel's colapse problem

### ISSUE THREAD

**Issue by StribogKonsult** [puikinsh/gentelella#436]
Where there are nested "x_panel" ,and main xpanel's "x_content" have "collapse" class - when you toggle  main (that contain others) - All child x_panel's - becomes "collapsed".
This is caused by : " $BOX_CONTENT " in :
$('.collapse-link').on('click', function() {
        var $BOX_PANEL = $(this).closest('.x_panel'),
            $ICON = $(this).find('i'),
            $BOX_CONTENT = $BOX_PANEL.find('.x_content');
.....

My fix is: 
$BOX_CONTENT = $BOX_PANEL.find('.x_content').eq(0);

**Comment by AndreiCN** [comment]
Thank you @StribogKonsult for pointing this out, we will certainly take this into consideration in a future update.
