### ISSUE TITLE
issue on bootstrap modals

### ISSUE THREAD

**Issue by JoaoOxOc** [puikinsh/gentelella#441]
When multiple bootstrap modals are open dynamically, it is shrinking the layout horizontally due to the rendering of multiple overflow-y of the multiple bootstrap modals.

solutions:
1º add this CSS style to the custom.css:
body.modal-open-noscroll {
  margin-right: 0!important;
  overflow: hidden;
}
.modal-open-noscroll .navbar-fixed-top, .modal-open .navbar-fixed-bottom {
  margin-right: 0!important;
}

2º add this JQuery code to custom.js:
$().ready(function() {
    /**
     * Solution for multiple bootstrap modals
     * 
	 * Webpage without this code shrinks horizontally when multiple bootstrap are opened dynamically
     **/
    $('.modal').on('show.bs.modal', function () {
      if ($(document).height() > $(window).height()) {
        // no-scroll
        $('body').addClass("modal-open-noscroll");
      }
      else { 
        $('body').removeClass("modal-open-noscroll");
      }
    })
    $('.modal').on('hide.bs.modal', function () {
        $('body').removeClass("modal-open-noscroll");
    })
});

**Comment by AndreiCN** [comment]
Thank you @JoaoOxOc , we will take this into consideration in a future update :)
