### ISSUE TITLE
User Interface broke

### ISSUE THREAD

**Issue by jpavanaryan** [puikinsh/gentelella#442]
I copied all the source files (css and js) in to ServiceNow application and tried to reproduce the page. After importing the necessary files, UI 
![screen shot 2017-04-06 at 2 59 48 pm](https://cloud.githubusercontent.com/assets/17564080/24771016/085e0f98-1ada-11e7-8c01-d81c81403ef8.png)
![screen shot 2017-04-06 at 2 59 54 pm](https://cloud.githubusercontent.com/assets/17564080/24771015/08592a1e-1ada-11e7-91b2-a27bbc11d5bb.png)

broke and looks ugly. Attached screenshots for the reference.

**Comment by jpavanaryan** [comment]
Browser console shows fonts can not be found.

**Comment by AndreiCN** [comment]
We didn't try it with ServiceNow until now but for a full experience of the product itself we suggest you to use it by default :)
