### ISSUE TITLE
How to remove PLUS datatable Button?

### ISSUE THREAD

**Issue by taishjason** [puikinsh/gentelella#443]
![image](https://cloud.githubusercontent.com/assets/7345594/24790725/056da976-1baa-11e7-9a63-022513ef04fd.png)

Help!!! How to remove the highlighted Blue color and Red color button?

**Comment by ydalley** [comment]
That's the Datatables.net "responsive" extension. Remove "responsive" from the Table class

**Comment by AndreiCN** [comment]
Since you have a solution for this we will close this just for now, if it doesn't work for you though, just reopen the issue.

**Comment by macleash90** [comment]
Changing responsive class didn't work for me
I had to comment out the `responsive:true` in the javascript code
Eg. 
```
...
.DataTable({
 dom: 'Bfrtip',
 scrollX: true,
 //responsive: true,  <-- Comment this line
})
...
```
