### ISSUE TITLE
I wish that we have this template for vue js

### ISSUE THREAD

**Issue by abdallahridhamohamed** [puikinsh/gentelella#448]

**Comment by arandilopez** [comment]
i wish that too... 🤔 maybe it'd be possible...

**Comment by jlugao** [comment]
Maybe we could team up and port this to vue

**Comment by DevinWatson** [comment]
Actually working on this now for work. Will see if I can make a template for it.

**Comment by abdallahridhamohamed** [comment]
Good Luck

**Comment by abdallahridhamohamed** [comment]
I hope i can join for it but i'am web developper JEE PHP Javascript and their framwork 
i have little idea about css

**Comment by AndreiCN** [comment]
Hope will see this working guys, will merge this if something good comes out , good luck !
