### ISSUE TITLE
Left nav menu toggle broken in Chrome

### ISSUE THREAD

**Issue by jedgalbraith** [puikinsh/gentelella#449]
The left nav menu toggle button is broken in Chrome Version 57.0.2987.133. It will no longer show/hide the left nav. No JS errors in the console.

![screen shot 2017-04-13 at 4 18 42 pm](https://cloud.githubusercontent.com/assets/313947/25026701/0454f700-2065-11e7-91ff-af5073917989.png)

I'm running macOS 10.12.4. I tested with Safari 10.1 & Firefox 52.0 and it's working fine in both, so seems to just be an issue with Chrome.

**Comment by SamMousa** [comment]
@jedgalbraith Do you still get this? For me it works fine on Chrome 54.

**Comment by jedgalbraith** [comment]
Yes. I'm still getting it. It's only broken with newer versions of Chrome. Around 57+. I'm now on 58.0.3029.110 and it's still broken.

**Comment by AndreiCN** [comment]
Also on chrome 58 and it's working just fine, anyone else with this issue ?
