### ISSUE TITLE
Small sidebar or navigation (nav-sm) as default. 

### ISSUE THREAD

**Issue by rnaby** [puikinsh/gentelella#45]
I need to make the sidebar small (body class nav-sm) for default. I tried some of the tricks, but didn't worked out. Can you tell me anything on it ?

**Comment by fdcchief** [comment]
Does anyone have a solution for this? I'm looking to do the same thing as well. Thanks for any input

**Comment by christianesperar** [comment]
@fdcchief is right but I think it will still show expanded sidebar footer. This is fix on this pr https://github.com/puikinsh/gentelella/pull/93

**Comment by sonuparmar39** [comment]
How can i set <body class="nav-md"> for mobile and <body class="nav-sm"> for laptop pls help me... thanks

**Comment by sonuparmar39** [comment]
How can i set class="nav-md" for mobile and class="nav-sm" for laptop pls help me... thanks
