### ISSUE TITLE
problem with checkbox on DataTable not being styled and all checked 

### ISSUE THREAD

**Issue by Faresbrahem** [puikinsh/gentelella#451]
![issue](https://cloud.githubusercontent.com/assets/25418730/25042616/d2ddaa9a-2119-11e7-847f-c449ecc1db34.PNG)
 is there a fix for this problem ? i really need this table

**Comment by Faresbrahem** [comment]
@AndreiCN please check this

**Comment by jesseg34** [comment]
I am having the same problem. Has anyone found a solution?

**Comment by jesseg34** [comment]
I resolved the problem by making the following change to the iCheck call in the custom.js file:

Changed:
`$datatable.on('draw.dt', function() {
				  $('checkbox input').iCheck({
					checkboxClass: 'icheckbox_flat-green'
				  });
				});`

To:
`$datatable.on('draw.dt', function() {
				  $('input[type=checkbox]').iCheck({
					checkboxClass: 'icheckbox_flat-green'
				  });
				});`

**Comment by AndreiCN** [comment]
First of all thank you for reporting it guys and @jesseg34 can you please make a pull request with it ?

**Comment by AndreiCN** [comment]
Fixed.
