### ISSUE TITLE
facing issue with the custom js

### ISSUE THREAD

**Issue by JinnaBalu** [puikinsh/gentelella#452]
Uncaught TypeError: Cannot read property 'Constructor' of undefined
    at custom.min.js

**Comment by cwyark** [comment]
Same issue here

**Comment by AndreiCN** [comment]
Can you please share when you have this problem ? A screenshot or so would really help.

**Comment by AndreiCN** [comment]
We'll just close this ticket for the moment, but if you still have this issue you can come anytime with some details and reopen it :)

**Comment by grzegorzociepka** [comment]
@JinnaBalu how did you fixed it?
I have the same issue :(
