### ISSUE TITLE
DateJS Folder Size is to big

### ISSUE THREAD

**Issue by AbdullahAlimam** [puikinsh/gentelella#453]
Hi
Why that  DateJS Folder "vendors\DateJS" Size is 32 MB.
If I need to remove the Unneeded files from it. what can I delete?

**Comment by AndreiCN** [comment]
Why you want to remove it ? It's a library, that's the the reason it takes so much.
We will close this one for now but if you have further questions you can reopen it whenever you want, or create another one of course.

**Comment by AbdullahAlimam** [comment]
many files are just repeated over and over for just a very small change for some cultures.
is there another lib or we should stick with this. or I can remove all cultures that I will not use in my application.

**Comment by SamMousa** [comment]
Doesn't the `moment` library do about the same thing??

**Comment by AbdullahAlimam** [comment]
it's fantastic it's just a few KB .. https://momentjs.com/
![image](https://user-images.githubusercontent.com/13034482/29840266-15b7f3d2-8d0a-11e7-82ca-8f0d4aed20e3.png)

**Comment by florentingarnier** [comment]
Why vendors file is versioned?
