### ISSUE TITLE
Fixed navbar

### ISSUE THREAD

**Issue by alexrmg** [puikinsh/gentelella#456]
Is there any way to fix the navbar the same way as the footer? 

Thanks

**Comment by mortel** [comment]
According to the example, you have to add the class "left_col menu_fixed" to 

`<div class="col-md-3 left_col" >`

so you have the line:

`<div class="col-md-3 left_col menu_fixed">`

Best,

**Comment by AndreiCN** [comment]
Will close this issue for the moment since you have a solution for it, it doesn't work for you just reopen it.

**Comment by alexrmg** [comment]
Thanks for your suggestion. It doesn't work out for me.. What i want is fixing the Navbar, such over the header, no the sidebar.

I would appreciate if you have any suggestion about this fixing.. 

thanks.
