### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by kezern** [puikinsh/gentelella#457]
I would like to know how to protect the admin panel with a password.
I can see there is a login.html file but I can't find where the password is processed.
Must I build all the validation for the password?

**Comment by krzysiekpiasecki** [comment]
Yes, you must implement this functionality. Here is an example based on PHP & Symfony: [Gentelella](https://github.com/krzysiekpiasecki/Gentelella)



__If you have no more questions, please close this ticket__.

**Comment by AndreiCN** [comment]
Since this issue has been openes a while ago and you already have a solution we will close it for now but if you have more questions about it , just reopen it , good luck !
