### ISSUE TITLE
Default WYSIWYG form post empty data

### ISSUE THREAD

**Issue by vijayrana-me** [puikinsh/gentelella#458]
First of all thank you for the great template and making it free. I have successfully integrated the theme on my website. I have an issue with wysiwyg editor. I have integrated the editor(default one which is in the template). Every thing works but during form submit, the data of wysiwyg is empty(null). What could be the possible solution. Thank You

**Comment by AndreiCN** [comment]
Hi there,

I think [this](https://github.com/steveathon/bootstrap-wysiwyg) will help you :)

**Comment by vijayrana-me** [comment]
Thanks for I already solved the issue. I had to wite few js code

**Comment by cristianraiber** [comment]
Could you please post your solution here @vijayrana-me so we can add it to the base code of Gentelella & others might benefit from it?

**Comment by bluesh55** [comment]
I solved this by writing some js code too.

```js
// https://github.com/puikinsh/gentelella/blob/master/build/js/custom.js#L1109

$('.editor-wrapper').each(function(){
  var id = $(this).attr('id');	//editor-one

  $(this).wysiwyg({
    toolbarSelector: '[data-target="#' + id + '"]',
    fileUploadError: showErrorAlert
  });

  // Write this
  $(this).bind("DOMSubtreeModified",function(){
    $('textarea[data-target=' + id +']').html(
      $(this).html()
    );
  });

});
```

And you must set data-target attribute in textarea tag.

```html
... wysiwyg codes ...

<div id="editor-one" class="editor-wrapper"></div>
<textarea name="descr" id="descr" data-target="editor-one"></textarea>
```
