### ISSUE TITLE
About the SIDEBAR_MENU  add Class("current-page") when CURRENT_URL include a[href][url]

### ISSUE THREAD

**Issue by Moruso** [puikinsh/gentelella#463]
Hi, 
when i use the template, 
I have a question.
I find "$SIDEBAR_MENU.find('a[href="' + CURRENT_URL + '"]').parent("li").addClass("current-page")" in costom.js
My understanding is that when the CURRENT_URL = = SIDEBAR_MENU [a] [href]   add Class()
But I want CURRENT_URL contains SIDEBAR_MENU [a] [href]  to  add Class() 
How to modify?

**Comment by AndreiCN** [comment]
Hi there Moruse,

What you want to achieve in terms of functionality ?

**Comment by WhiteRavenProject** [comment]
Maybe changing `$SIDEBAR_MENU.find('a[href="' + CURRENT_URL + '"]').parent("li").addClass("current-page")` to `$SIDEBAR_MENU.find('a[href="' + CURRENT_URL + *'"]').parent("li").addClass("current-page")` can solve your issue.

**Comment by AndreiCN** [comment]
We will close this for now but of course you can reopen anytime if you need to.
