### ISSUE TITLE
How to avoid dropdown to be closed and open on click list inside it?

### ISSUE THREAD

**Issue by ammydon** [puikinsh/gentelella#465]
First of all thanks to create this theme its very useful and nice design you created.
I have just issue with your dropdown menu. If i click any list inside main main ul then main ul will closed immediately and opens too. i dont want to close my ul when i click on any of the list inside it. I used 
```
$(".child_menu").click(function(event) {
    event.stopPropagation();
});
```
to overcome my issue but nothing happens. please help me with the same bro. how to remove that function of slideUp and slideDown on list.

**Comment by Crouxie** [comment]
This piece of code is responsible for menu sliding:
`$SIDEBAR_MENU.find('a').filter(function () {
		return this.href == CURRENT_URL;
	}).parent('li').addClass('current-page').parents('ul').slideDown(function() {
		setContentHeight();
	}).parent().addClass('active');`

**Comment by AndreiCN** [comment]
We already pointed this issue, seems like it's a common one, are some duplicated tickets about it.
We will take care of ti as soon as possible, thank you !
