### ISSUE TITLE
RTL layout

### ISSUE THREAD

**Issue by EngBadr** [puikinsh/gentelella#467]
Hi , 
Is there any plan to add RTL layout this would increase usage of this awesome template.

Personally I tried use `<html dir="rtl" lang="ar">` I also used this package 
https://github.com/RTLCSS/bootstrap but I did not success I think I need to play with custom.css if some one try this please advise .

**Comment by AndreiCN** [comment]
Hi ,

Unfortunately it isn't so simple to make it RTL. Would be so simple with one line of code :)
Not just CSS, JS and HTML too. it's a hole process, you're not the only one that wants it. we will certainly release a RTL version into the future, thank you !

**Comment by mortezakarimi** [comment]
Hi @EngBadr 
I working on RTL version of this template but this under construction
You can test and feedback me to improve
https://github.com/mortezakarimi/gentelella-multidirectional/

**Comment by EngBadr** [comment]
Thank you for all 
Well this is good hear about releasing of RTL version it will help a lot of developer.
Brother Mortaza thank you very much of your answer and I will use your template until the new official RTL version released. but I wondering about the jQuery version is it update because the official version still use older version.

**Comment by AndreiCN** [comment]
done it.
