### ISSUE TITLE
3º level menu not working on mobile

### ISSUE THREAD

**Issue by jonasreichel** [puikinsh/gentelella#471]
Hello.

The 3º level of menu is not working on mobile.
Its's closing.

**Comment by kevingogomez** [comment]
I really don't know why that is happening. Should be it's a problem when you have the reduced sidebar. And the class "sub-menu" doesn't exists for the template on mobile devices...

**Comment by AndreiCN** [comment]
Thank you for pointing this out , will investigate this and come with a solution as soon as possible.

**Comment by SumonT2** [comment]
Hi I have fixed the issue. :)
