### ISSUE TITLE
Active tab after postback

### ISSUE THREAD

**Issue by EngBadr** [puikinsh/gentelella#474]
Is there any good method to use form control inside the tab with postback 
 for example 
I use 4 tabs and placed a form elements inside them 
my issue is how to remain the active tab selected after doing postbak. 
I use diffrenet solution in stackoverflow community but I did not success
here is an example

[check here](http://mrbadr-001-site1.itempurl.com/backend/setting/SystemSetting)

**Comment by AndreiCN** [comment]
Hello @EngBadr , still facing this issue ?

**Comment by AndreiCN** [comment]
We will close this for now but you can reopen it anytime if you need to.
