### ISSUE TITLE
Left navbar visual design problem (general title to close to avatar)

### ISSUE THREAD

**Issue by taime** [puikinsh/gentelella#476]
There is caption general at left menu under user picture. It's to close to each other. 
It looks like general is username, but it's not. It should looks like navigation bar caption.

Here is screenshot: <img width="492" alt="image 2017-05-16 at 3 37 21 am public" src="https://cloud.githubusercontent.com/assets/1723871/26085062/f9ceb80e-39e9-11e7-8a38-35429024f503.png">

Just adding 
`.main_menu_side {margin-top: 100px;}`
will fix the problem

And looks much better: 
<img width="432" alt="screen shot 2017-05-16 at 03 45 08" src="https://cloud.githubusercontent.com/assets/1723871/26085081/19f98884-39ea-11e7-9977-3f45aff09484.png">

**Comment by AndreiCN** [comment]
Hi there @taime , 

I think you're not using the latest version , because in the latest one that space it's already there, nevertheless some small changes can be made there so I will add enhancement level to this one, thank you !
