### ISSUE TITLE
JavaScript runtime error: Unable to get property 'getContext' of undefined or null reference    var myDoughnut = new Chart(document.getElementById("canvas1").getContext("2d")).Doughnut(doughnutData);

### ISSUE THREAD

**Issue by RazackS** [puikinsh/gentelella#48]
Hi,

Following error occur when i am using this open source,what is that?

this.ctx=this.canvas.getContext("2d")
JavaScript runtime error: Unable to get property 'getContext' of undefined or null reference

gauge.min.js

var myDoughnut = new Chart(document.getElementById("canvas1").getContext("2d")).Doughnut(doughnutData);

**Comment by christianesperar** [comment]
Do you have an id "canvas1"? This is happen when you trying to execute chart on a non existing id

**Comment by RazackS** [comment]
Hi,
Now it's working fine,the problem is firt html code loaded and then js functions loaded sequences.

thanks.

**Comment by christianesperar** [comment]
Fixes included on https://github.com/puikinsh/gentelella/pull/54
