### ISSUE TITLE
 Problems opening the menu when it has submenus

### ISSUE THREAD

**Issue by clamp2x** [puikinsh/gentelella#480]
When the primary menu has submenus and the primary menu contains links(href), the submenus are not expanded when the corresponding primary menu is selected.

I think I need to modify the custom.js file. Which line should I modify?

**Comment by AndreiCN** [comment]
Hi,

I'm not quite sure if this is a bug or a custom implementation, can you please share more details about it ? A screenshot or something will help a lot.

**Comment by clamp2x** [comment]
I think it should be improved.
For example, if the Home menu itself contains a link, the sub-menus - Dashboard, Dashboard2, and Dashboard3 do not appear.
In order to reproduce, it can add a link to the first menu.

**Comment by AndreiCN** [comment]
Ok, thank you for pointing this out, we will mark this as enhancement :)

**Comment by AndreiCN** [comment]
fixed.
