### ISSUE TITLE
Input Tags not passed in POST

### ISSUE THREAD

**Issue by SynAckPwn23** [puikinsh/gentelella#481]
The Input Tags seems not working, the tags are not passed in POST request.

**Comment by AndreiCN** [comment]
Hello there, 

Can you please provide more details about this issue?  Because I'm not quite sure where's the problem there, also a screenshot would help a lot to identify the issue :)

**Comment by SynAckPwn23** [comment]
Hi,
sorry my mistake, everithing it works

Daniele

2017-06-06 12:40 GMT+02:00 AndreiCN <notifications@github.com>:

**Comment by AndreiCN** [comment]
Glad to hear that :)
