### ISSUE TITLE
jQuery .load() depreciated

### ISSUE THREAD

**Issue by NicksonYap** [puikinsh/gentelella#482]
In:
https://github.com/puikinsh/gentelella/blob/master/src/js/custom.js#L243

instead of ` $(window).load(function () {`

it should be `$(window).on('load',function() { `

I am using jQuery 3.2.1.
Otherwise the loading bar never stops and cannot interact with the page.

**Comment by NicksonYap** [comment]
#483

**Comment by SamMousa** [comment]
This can be closed since the PR was merged?

**Comment by NicksonYap** [comment]
Not sure since i don't see the final js (custom.js) file being rebuilt.
Plus, there seems to have extra functions prefixed with "init_" added after building. 
Seems to be used for the examples in the production page. 

I have built and used it in my application.
Works fine and I don't see the "init_" functions in the final js file. 

How should we deal with this? 
Probably the "init_" functions should be separated in a static js file?

**Comment by AndreiCN** [comment]
It was already merged.
