### ISSUE TITLE
putting class="flat" to input type="radio" let the onchange function stop working 

### ISSUE THREAD

**Issue by AbdullahAlimam** [puikinsh/gentelella#485]
how to fixt this problem please?

```
<script type="text/javascript">
    function aa(v)
    {
        alert(v);
    }
</script>

<input type="radio" class="flat" name="group" runat="server" id="radTest1" onchange="aa(1);" />
<input type="radio" name="group" runat="server" id="radTest2" onchange="aa(2);" />
```

when I add the class "flat" the function aa is not triggered .. Why?

**Comment by AndreiCN** [comment]
Can you show me the error or something ?

**Comment by AndreiCN** [comment]
We will close this issue for now but you can reopen it whenever you want providing some more details :)

**Comment by jqlinux** [comment]
I met the same question，How do we solve that

**Comment by dsyenket** [comment]
How to solve this issue?

**Comment by JhonnatanPanoch** [comment]
Why this issue was closed? I'm facing the same error and I dont know how to solve it.

**Comment by JhonnatanPanoch** [comment]
> How to solve this issue? There’s no error, just there’s the INS tag blocking the whole thing and the onclick event doesn’t fire if you put class “flat” in the input radio

You need to use icheck like this:
`$('input:radio[name=myradio]').on('ifClicked', function (event) {}`
