### ISSUE TITLE
Indent between <div class = "right_col" role = "main"> and <footer>

### ISSUE THREAD

**Issue by Churakovmike** [puikinsh/gentelella#488]
Indent between `<div class = "right_col" role = "main">` and `<footer>` in the browsers of the opera, chrome, and11. In firefox, everything is fine.
I use Yii2 last version and yii2-gentelella.
Scrennshot from Opera - [there](http://savepic.ru/14136195.jpg)
Screnshot from Firefox - [there](http://savepic.ru/14119811.png)

**Comment by AndreiCN** [comment]
Hi there @Churakovmike ,

Well this is a front-end product and we're dealing with front-end only.
