### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Norwegiant** [puikinsh/gentelella#49]
I install Gentellela Admin at /wp-admin/plugins.phpbut, but i get file issue. not supported. 
Need help for installation.

**Comment by puikinsh** [comment]
This is not a WordPress theme. It is a standalone HTML template made using Bootstrap frontend framework. If you are looking for WordPress dashboard themes and plugins you might want to check this list: https://colorlib.com/wp/wordpress-admin-dashboard-themes-plugins/
