### ISSUE TITLE
compact menu, third level fail to open

### ISSUE THREAD

**Issue by Giambapisasale** [puikinsh/gentelella#490]
Hi, after click to compacting side menu, I cannot open a third level menu because on click to second level it collapse
image
In the image you can see, if I click on "level one" the menu collapse instaed of open the third level
![ge52a7b148-413c-11e7-8003-ff626a7150e8](https://cloud.githubusercontent.com/assets/8735065/26540554/367c5a0a-4452-11e7-90dc-a2612ba44239.png)

thanks

**Comment by AndreiCN** [comment]
Hi @Giambapisasale,

Thank you for pointing this out, we will take it into consideration in a future update.

**Comment by john871** [comment]
Having the same problem, did anyone found a temporally fix until the devs fix it?

**Comment by SumonT2** [comment]
Hi I have fixed the issue. :)

use code below

```
 $SIDEBAR_MENU.find('a').on('click', function(ev) {
		var $li = $(this).parent();
		if ($li.is('.active')) {
			$li.removeClass('active active-sm');
			$('ul:first', $li).slideUp(function() {
				setContentHeight();
			});
		}
		else
		{
			// prevent closing menu if we are on child menu
			if (!$li.parent().is('.child_menu')) {
				$SIDEBAR_MENU.find('li').removeClass('active active-sm');
				$SIDEBAR_MENU.find('li ul').slideUp();
			}else
			{
				if ( $BODY.is( ".nav-sm" ) )
				{
					if (!$li.parent().is('.child_menu')) {
						$SIDEBAR_MENU.find('li').removeClass('active active-sm');
						$SIDEBAR_MENU.find('li ul').slideUp();
					}
				}
			}
			$li.addClass('active');

			$('ul:first', $li).slideDown(function() {
				
			});
		}
	});



```

**Comment by john871** [comment]
Sumon i have placed your code on my footer, but now it is automatically closing the menu, even if its not sub_menu on click (shows and hides constantly)

**Comment by john871** [comment]
SumonT2 thanks a lot! Just a small clarification to everyone watching this issue.
Here are the steps you need to do:

1) Open build/js/custom.js
2) Find the similar code above (should be around row #72), delete it, and paste the code above.
3) Go to your footer file (or at the bottom of your page if kept the same source code of this project) and change the script src from custom.min.js to custom.js

**Comment by AndreiCN** [comment]
Thank you for your contribution @SumonT2 !

**Comment by Giambapisasale** [comment]
Thankyou very much!
I've modified the original custom.js under src/js directory, then I run `gulp scripts`

**Comment by SumonT2** [comment]
Ha ha ha . WC to all ;)

**Comment by jamiesonbecker** [comment]
Another possible fix here: https://github.com/puikinsh/gentelella/issues/415#issuecomment-340182975

**Comment by jahstation** [comment]
I cannot understand where to put this code for making the collapsed menu works... ive a gentellela over laravel 5.
I analized the file:
custum.js inside vendor->bower_component-->src-->js
or
gentelella.min.js (unmin) inside -> public->js

but both do not show me anything similar to the function posted above! I can find an "function init_sidebar() "
inside the second js file, but inside for example there is no "sethieght()" function or "function(ev)"
and around the "72" line

how can I fix this? thank you so much

**Comment by DarkFrostnight** [comment]
> Thank you very much!
> why `fa-chevron-down` icon not appear? i have try in localhost.
> Refer to picture above > Multilevel menu > Level One (Second), fa-chevron-down icon not appear

try whit this 

.nav.child_menu span.fa{
        display: block;
      }
