### ISSUE TITLE
SideBar menu does not stay active with query string

### ISSUE THREAD

**Issue by BFronz** [puikinsh/gentelella#492]
When a  url with query string is added to the side bar child menu, the clicked menu link does not stay active. I tested on the latest gentelella-master  version:

             <ul class="nav side-menu">     
            <li><a href="index.html?id=123">Dashboard I</a></li>
             <li><a href="index2.html?id=345">Dashboard II</a></li>
            <li><a href="index3.html?id=678">Dashboard III</a></li>

**Comment by AndreiCN** [comment]
Thank you @BFronz for reporting this, we will take care of it.

**Comment by iorien** [comment]
In my actual configuration I solved this problem replacing the line :
`var CURRENT_URL = window.location.href.split('#')[0].split('?')[0],`
by this one:
`var CURRENT_URL = window.location.href,`
in file /build/js/custom.js

Maybe it can cause problems with other configurations

**Comment by AndreiCN** [comment]
Thank you @iorien for your contribution  👍

**Comment by BFronz** [comment]
Thank You.

Bob

**Comment by vahidalvandi** [comment]
do it solve?
