### ISSUE TITLE
Uncaught InvalidArgumentException: The "framework.trusted_proxies" configuration key 

### ISSUE THREAD

**Issue by dr-matt-smith** [puikinsh/gentelella#493]
Fatal error: Uncaught InvalidArgumentException: The "framework.trusted_proxies" configuration key has been removed in Symfony 3.3. Use the Request::setTrustedProxies() method in your front controller instead. 

I get this error when running `composer  update` 

.. matt ..

**Comment by krzysiekpiasecki** [comment]
@dr-matt-smith It's not a Symfony project.

**Comment by krzysiekpiasecki** [comment]
@dr-matt-smith 

If you mean this repository https://github.com/krzysiekpiasecki/Gentelella,  currently correct dependencies comes directly from composer.lock.

Thanks for the issue.  We can safely close your ticket on this repository.

**Comment by dr-matt-smith** [comment]
yes, the symfony fork - thanks .. matt ..
