### ISSUE TITLE
Left Nav Bar Multi-Level Menu Collapse Issue

### ISSUE THREAD

**Issue by satbir90** [puikinsh/gentelella#494]
Steps to regenerate Issue

1. Click on Menu Toggle (menu_toggle) Nav needs to be 'nav-sm'
2. Click on Multilevel Menu
3. Click on 2nd Level One menu item
4. The Whole Menu collapses before opening the level two (Problem)

**Comment by AndreiCN** [comment]
Thank you @satbir90 for pointing this out, we are already aware of this issue  and we will solve it as soon as possible.
