### ISSUE TITLE
echart_pie color

### ISSUE THREAD

**Issue by ItalDaskal** [puikinsh/gentelella#495]
Hi, i cant cange thr color of echart_pie.
where do you define this?

**Comment by AndreiCN** [comment]
Hi there,

Well to change the color you need to go to build/js/custom.cs , fiind echart pie options ( search for echart ) and modify chart options.

**Comment by AndreiCN** [comment]
We will close this issue for now, but you can reopen it whenever you want.

**Comment by ItalDaskal** [comment]
Hi, i'm trying put echart_scatter in bootstrap popup ( class="modal fade" )
And for some reason it does not happen.
I do not get an error. It just does not appear in pop-up.

```

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 id="modalTitle" > </h2>

            </div>
                <div class="row col-md-12 col-lg-12 col-xs-12">
                    <div id="echart_scatter" style="height:400px;" ></div>
                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

```

Thanks, 
Ital

**Comment by AndreiCN** [comment]
Can you provide a screenshot with to see what's happening in the browser @ItalDaskal ?

**Comment by ItalDaskal** [comment]
@AndreiCN 
![example](https://user-images.githubusercontent.com/15198459/27181764-a0d238ce-51e1-11e7-842f-05a1f9331dfc.png)

**Comment by AndreiCN** [comment]
Well it seems that you're not loading it on a server. Make sure you do and the JS error will come :)

**Comment by ItalDaskal** [comment]
@AndreiCN 
i upload the code to the server, still, no error.

[server](https://phobvr.herokuapp.com/patient/3)
(you need to click on table tr for open the popup)
[git](https://github.com/ItalDaskal/finalProjectShenkar/blob/master/views/layoutPatient.ejs)

**Comment by ItalDaskal** [comment]
Hi, is it an option to put at custom.js data like this,
`data:  [
                    document.getElementById("echart_scatter").getAttribute('data-HRdata')
 ],`

i can't write it hardcoded. i bring the data from mongodb so i clean the data so 
it will show like the hardcoded

> [0.36382627487182617,98],[0.9335603713989258,98],[1.625218391418457,97],[2.2069201469421387,97],[2.8324804306030273,97],[3.4345455169677734,97],[4.2060136795043945,95],[4.95449161529541,94],[5.735302925109863,91],[6.416640281677246,90],[7.062828063964844,89],[7.745919227600098,89],[8.33752155303955,89],[8.98659896850586,88],[9.689132690429688,87],[10.405364990234375,86],[11.073719024658203,87],[11.754981994628906,88],[12.392019271850586,90],[12.995019912719727,91],[13.619476318359375,91],[14.210777282714844,92]
