### ISSUE TITLE
Main contain (min-height) out of view

### ISSUE THREAD

**Issue by john871** [puikinsh/gentelella#496]
Hello, first of all i would like to place my appreciation on your project, it is amazing.

The bug i have found is on the main container it is auto adjusting the min-height value depending on the contents. But if the contents are less than a whole page (lets say a few lines that you do not need to scroll down), the footer its below the front page (so you need to scroll down a bit either way, even if the contents are few lines). I checked the latest version but it still not fixed.

(See attached picture)

![untitled](https://cloud.githubusercontent.com/assets/29197393/26780480/a7e39a6e-49f2-11e7-882a-486ddc1dc31e.png)

thank you.

**Comment by AndreiCN** [comment]
Hello,

Yes indeed, seems like something happens in there, I will investigate this and solve it as soon as possible, thank you !

**Comment by eglyecyriaco** [comment]
@john871 were you able to fix this?
It is on our modify list...

**Comment by AndreiCN** [comment]
related to #499

**Comment by marcelogarbin** [comment]
@eglyecyriaco @john871 Have you been able to fix this? thank's
