### ISSUE TITLE
top_nav menu user profile stuck 

### ISSUE THREAD

**Issue by almayahi** [puikinsh/gentelella#497]
Hello 
I am using the dashboard on my MVC Core project, everything is working in the perfect way except the top_nav menu, the user-profile and the notification badge, the dropdown is not functioning, when I click on any it is not opening the menu. while as HTML is working. 

![image](https://cloud.githubusercontent.com/assets/15112440/26806653/c0897706-4a5a-11e7-8612-37cd9c70a2cb.png)

any idea? 
is there any file in the project can be found that list all CSS and js file for including them in the main layout instead of looking for them in each any every HTML file? 

Thanks

**Comment by AndreiCN** [comment]
Hello there,

From what I see it a JS problem there, make sure you have no errors when the template is loaded.

**Comment by mariapaulinar** [comment]
Same  here :(
