### ISSUE TITLE
Links with Internet Explorer 11

### ISSUE THREAD

**Issue by int0therain** [puikinsh/gentelella#5]
Hi, this template is simply amazing !.
Congratulation.

I just found something strange when using Internet Explorer 11 (32 bits) 11.0.9600.16428.

Sometimes when i click links, it doesn't change the page.
I have record a video for you

http://mbf.me/Gsb9nw

Hope that's helps :-)
Bests regards !

**Comment by christianesperar** [comment]
This pr #30 also fix this bug
