### ISSUE TITLE
Synchronous XMLHttpRequest error

### ISSUE THREAD

**Issue by Geovanek** [puikinsh/gentelella#501]
Today this error began to appear.

_Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience._

Any button that I click refreshes the page, I have looked in several places and found no solution.
Any idea?

**Comment by AndreiCN** [comment]
Hi there @Geovanek ,

That's a jQuery issue for sure and [this](https://stackoverflow.com/questions/27736186/jquery-has-deprecated-synchronous-xmlhttprequest/27736383) should help get through this :)

**Comment by AndreiCN** [comment]
We will close this for now but feel free to reopen it when you want.
