### ISSUE TITLE
Gender buttons doesn't switch

### ISSUE THREAD

**Issue by lordspace** [puikinsh/gentelella#507]
https://colorlib.com/polygon/gentelella/form_wizards.html

**Comment by krzysiekpiasecki** [comment]
It's not a formal bug. There is no source code to handle this switch.

Male button has a class ```btn-primary``` which is incorrect. The submit button has such a class too. They share the same color. 

I'll propose removing class replacing class ```btn-primary``` with ```btn-default``` and removing abstraction classes like ```data-toggle-passive-class```. After this visual marker will be class 'active' which is bootstrap default class.


If it's ok I can handle a PR. The same in form.html

**Comment by AndreiCN** [comment]
Buttons are switching but because of the background-color you cannot say exactly which is which in terms of selection , I will make this better , thank you @lordspace for reporting this.

**Comment by lordspace** [comment]
Cool
