### ISSUE TITLE
How fixing navbar-header

### ISSUE THREAD

**Issue by alexrmg** [puikinsh/gentelella#508]
Thanks for your suggestion on issue #456. It doesn't work out for me.. What i want is fixing the Navbar, that on the header, no the sidebar.

I would appreciate if you have any suggestion about this fixing..

thanks.

**Comment by AndreiCN** [comment]
If you're using bootstrap "menu_fixed" will help, if it doesn't, you're doing something wrong.

**Comment by w4r0** [comment]
I tried "menu_fixed" on both "top_nav" and "nav_menu" from the plain zip file I download from Github and it doesn't work.

I also tried bootstrap own's "navbar-fixed-top", it'll make a fixed nav but hide the class "below" it ("right_col" class).

**Comment by alexrmg** [comment]
It happens exactly the same as you w4r0. It doesn´t work...

**Comment by mortel** [comment]
I would love to help you guys, but right know I don't get your problem - or to be more specific - what you mean with header. Maybe you can add a screenshot and mark the area you want to have fixed?

This is what I mean: http://imgur.com/a/vsNuX

**Comment by mortel** [comment]
Or do you want this: http://imgur.com/a/6CrTh 
For this, you have to add navbar-fixed-top to the div with class="top_nav".
`<div class="top_nav top_nav_fixed">`

**Comment by alexrmg** [comment]
MORTEL, that is the real solution... i am very grateful.... issue closed to me..

regards..

**Comment by mbasirati** [comment]
@mortel Please edit your answer! 
You have to use dash instead of underline in html code:
`<div class="top_nav top-nav-fixed">`

**Comment by mbasirati** [comment]
@mortel When I add "navbar-fixed-top", it'll make a fixed nav but hide the `page-title` div!

**Comment by w4r0** [comment]
I ended up using <div class="top_nav navbar-fixed-top">, but I have to add a margin-top to .page-title class:

    .page-title {
    width: 100%;
    height: 65px;
    padding: 10px 0;
    margin-top: 45px;}

I know it's a hack, but it works, until someone make it a fix.

**Comment by ShedrackGodson** [comment]
none of these helped me.
