### ISSUE TITLE
Fixed top_nav

### ISSUE THREAD

**Issue by w4r0** [puikinsh/gentelella#509]
Is there any way to fix the top_nav the same way as the footer or sidebar?

I tried using .menu_fixed but nothing happened.
And I also tried using .navbar-fixed-top but it hid .page-title below the top_nav.

Thanks

**Comment by William-H-M** [comment]
Hi, this is a duplicate of #508 continue the issue there, please avoid open the same issue twice, thanks.

@AndreiCN please close this as a duplicate.
