### ISSUE TITLE
Sub_menu on devices not working

### ISSUE THREAD

**Issue by john871** [puikinsh/gentelella#511]
Hello,

I have a sub_menu in my navigation that works fine on my computer. But on my mobile device, when i click the sub menu (e.x Home->Users-> edit/new etc) it show it for few milliseconds  and then disappears.

thanks you.

**Comment by cristianraiber** [comment]
@john871 - did you manage to fix this?

**Comment by john871** [comment]
I Closed my ticket because i saw there already 2 open for the exact bug.

**Comment by john871** [comment]
https://github.com/puikinsh/gentelella/issues/490
