### ISSUE TITLE
Dynamic Table bug

### ISSUE THREAD

**Issue by zarulizham** [puikinsh/gentelella#513]
Hi, the template very good until I found a bug which layout is okay on HTML but when on PHP, it have excess long spaces after the table. (Maybe the height of table did not recalculated?). 

I have tried:
1. Open with Mozilla Firefox and Google Chrome but return same result **not working**
2. Clear cache **not working**
3. Resize browser window (larger or smaller) **the white space removed automatically** 👍 

![alt text][logo]

[logo]: http://i.imgur.com/7UbTR8P.png "Long white space"

**Comment by AndreiCN** [comment]
Unfortunately this is a HTML template and since is ok there we're gonna close this for now but feel free to open another one whenever you want with a HTML/CSS/JS issue/help etc.
