### ISSUE TITLE
DataTable function cannot be called

### ISSUE THREAD

**Issue by jywu90** [puikinsh/gentelella#514]
Thanks a lot for the wonderful template. I have a quick question. My dataTable function cannot b called when add the following script in the html file.
```
$(document).ready(function() {
    $('#example').DataTable();
} );
```

Anyone has suggestions? Thanks a lot!

**Comment by jywu90** [comment]
I have change the name "example" to the ID name of my table.

**Comment by William-H-M** [comment]
This looks like it's solved, right? If it is can you please close the ticket? thanks

**Comment by jywu90** [comment]
Oh, sorry for the confuse, it's not solved. I changed it, but it's still not working....

**Comment by William-H-M** [comment]
Hi, does it throws any console error or can you show me the structure of the table and the script you're using:
just as a reminder for the plugin to work must have the structure of 
<thead>
<tr>
<th>
...
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
...
</td>
</tr>
</tbody>

**Comment by AndreiCN** [comment]
We're gonna close this for now @jywu90  but feel free to reopen it or create another one whenever you want.
