### ISSUE TITLE
Autocomplete Demo Not Working

### ISSUE THREAD

**Issue by hiteshyalamanchili** [puikinsh/gentelella#515]
The autocomplete feature doesn't seem to be working on the demo page. When I just type in 'A', I don't see any countries being displayed in a dropdown.

![image](https://user-images.githubusercontent.com/4751931/27512529-85ee5f56-5911-11e7-8ffc-5910199e3988.png)

**Comment by William-H-M** [comment]
Hi, can you local test the files I added a while ago from my repo and tell me if does give you any problem, thanks.

**Comment by hiteshyalamanchili** [comment]
@William-H-M This did indeed fix the problem locally. Thank you for the fix. Hopefully this will be resolved in the next update.

**Comment by William-H-M** [comment]
Hi, glad to know is fixed for now, and is seems to be solved, can we close this as be itself the "bug" was solved? Thanks, have a nice day :D

**Comment by dESourcesra** [comment]
This issue still exists.

**Comment by William-H-M** [comment]
@dESourcesra Did you downloaded the current version? or the one of my branch because until I remember this was fix on #627

**Comment by dESourcesra** [comment]
@William-H-M my bad, I just tried the demo. I just downloaded the new version it's working there. I have the previous version implemented, should I just replace "devbridge-autocomplete" library? thanks,
