### ISSUE TITLE
Datables Issue

### ISSUE THREAD

**Issue by Bkoech** [puikinsh/gentelella#52]
I am using this template and i like it.
I am having a problem displaying a single record from mysql table using php i get dummy data i don't know where from.
It works well in more than one records.
![datatbles](https://cloud.githubusercontent.com/assets/8352751/13663117/60b80630-e6b0-11e5-8161-aa534375c64f.PNG)

 
For the two records this is how it looks
![datatables2](https://cloud.githubusercontent.com/assets/8352751/13663222/127d0cbc-e6b1-11e5-873a-d49a3548ed8d.PNG)

**Comment by puikinsh** [comment]
We have completely redone this section. Could you please check if it is working now?

**Comment by Bkoech** [comment]
Ok how about in my project what should i update exactly for the new changes to pick up

**Comment by puikinsh** [comment]
It really depends on how you have coded the rest of it as this is just a plain HTML version with no database or anything behind it.

**Comment by Bkoech** [comment]
I have coded with php so all of my files are in php so should i update the data tables java script files?

**Comment by puikinsh** [comment]
You should update both JavaScript and CSS files on that section as we completely redid structure of those files and also added new features such as responsive tables and excel style tables.
