### ISSUE TITLE
custom.js is change!

### ISSUE THREAD

**Issue by laozhizi** [puikinsh/gentelella#520]
when I add one-line comment on src/js/custom.js, gulp runs "gulp.task('default', ['browser-sync', 'watch']);".
The file build/js/custom.min.js is change to much smaller than before.
who can answer me why? 3q！

**Comment by AndreiCN** [comment]
It's absolutely fine because it's a minified version.

**Comment by laozhizi** [comment]
I know the file build/js/custom.min.js is a minified version.
My question is build/js/custom.min.js is change to much smaller than before change custom.js
src/js/custom.js has less content than build/js/custom.js, Could you answer me?

**Comment by AndreiCN** [comment]
src/js/custom.js it not the complete one and also it's not declared in the HTML, if you look closely you'll see that we're including just build/custom js file so the complete and right file is build/custom.js
