### ISSUE TITLE
Change the languaje a region settings

### ISSUE THREAD

**Issue by juliolopezbarajas** [puikinsh/gentelella#522]
Hi, thanks a lot for your support

I'm wondering how can i change the languaje and region settings for this template?, it includes the idiom of the messages, buttons, date format, etc.

Do i have to translate some javascript files? if this is the case, i can contribuite with the translation of the template to Spanish Mexico.

Thank you so much!

**Comment by AndreiCN** [comment]
Hi, I think a good solution for this would be to modify what you need by hand in HTML , buttons , messages etc..

**Comment by juliolopezbarajas** [comment]
Thanks AndreiCN, but the problem is that when there is no data on the dynamic tables i get a message "No data available in table", after that there is a nav section at the bottom right of the table with buttons "previous 1 2 3 4 5 ... next" and at the left a massage "Showing 1 to 20 of N entries". The other problem is the format of the date, we use dd/mm/yyyy and al the date pickers and date range pickers use mm/dd/yyyy, and most of the buttons that comes with these controls get their buttons from javascript files.

I tried to change and custom some javascript files but it didn't work!.

Any other suggestion?

Thanks a lot

**Comment by William-H-M** [comment]
Hi, @juliolopezbarajas this is not something of the template itself this is something of the different plugins given by example [DataTables](https://colorlib.com/polygon/gentelella/tables_dynamic.html) it has his own way to localize the strings [here](https://datatables.net/reference/option/language)

Most of DatePicker use Moment JS as has their formats pretty well [documented.](http://momentjs.com/docs/#/displaying/format/)
