### ISSUE TITLE
NPM - module not found

### ISSUE THREAD

**Issue by MartinaAnt** [puikinsh/gentelella#523]
I am trying to bundle Gentelella as a module in my webpack.config.js. Even when gentelella is installed in node_modules folder (I can reach files with the absolute path), the webpack reports "Module not found: Error: Can't resolve 'gentelella'".
Similar problem occurs using require() - it could be seen at https://npm.runkit.com/ as well (run only: `var test = require("gentelella")`).

**Comment by AndreiCN** [comment]
Hi there,

Do you get some reference to build/images directory? It may that missing folder cause the problem.

**Comment by MartinaAnt** [comment]
Hi,
webpack creates build directory with [name].build.js files - it works with other node modules, but not with gentelella.

Specifically,
in package.json  -  `"dependencies": {... "@fancyapps/fancybox": "^3.0.48", "gentelella": "1.3.0",...}`
in webpack.config.js - ```
entry: {'app':  __dirname + "/www/backend/js/main.js",
        'datagrid': __dirname + "/www/backend/js/datagrid.js",
        'gen': 'gentelella', 
        'fancybox': '@fancyapps/fancybox', 
        }, 
output: {
        path: path.join(__dirname, "www/build"),
        filename: "[name].bundle.js"
    },
```
new files in www/build/: app.bundle.js, datagrid.bundle.js, fancybox.bundle.js.

**Comment by keload** [comment]
I don't have build/images folder, and the custom.css in /build/ have a blue backgound color :)

**Comment by AndreiCN** [comment]
Unfortunately we can only help you with Gulp assitance since this is what we're using for Gentelella, didn't tested with Webpack until now so we are gonna close this ticket for now but feel free to open another one of course whenever you need to.
