### ISSUE TITLE
npm install installs 1.3 instead of 1.4

### ISSUE THREAD

**Issue by pdrosos** [puikinsh/gentelella#524]
`npm install` installs version 1.3 instead of the latest 1.4.
Could you please update it?
Thanks!

**Comment by AndreiCN** [comment]
Yep, thank you !

**Comment by r-brown** [comment]
Hi guys, do you have any updates on the same?
npm got [1.3.0](https://www.npmjs.com/package/gentelella) only; 1.4.0 would be great or even 1.5.0

**Comment by DanAtkinson** [comment]
This is actually causing us a problem right now as we're looking to migrate away from Bower to just using npm. Unfortunately Bower uses 1.4.0, so I'm stuck until npm's Gentelella is updated.

**Comment by nixis** [comment]
+1 Please update to 1.4.0

**Comment by AndreiCN** [comment]
We are working on that, thanks.

**Comment by AndreiCN** [comment]
Done.
