### ISSUE TITLE
Click child menu will scroll  up parent menu first ,then scroll  down parent menu ?

### ISSUE THREAD

**Issue by geekwolf** [puikinsh/gentelella#526]
Click child menu will scroll  up parent menu first ,then scroll  down parent menu ? This is a bug?

![1](https://user-images.githubusercontent.com/3125615/27940499-963ec0f8-62fd-11e7-8a00-564e6977b068.jpg)
![2](https://user-images.githubusercontent.com/3125615/27940506-99a9ed58-62fd-11e7-928e-6fb8aa79422c.jpg)
![3](https://user-images.githubusercontent.com/3125615/27940510-9c5514e2-62fd-11e7-9642-3f2d2c74f8d5.jpg)

**Comment by William-H-M** [comment]
Hi, this by default as there's a script that identifies in which location the menu should, as it take the href attribute and look for it on the menu itself and add the respective classes, so basically is not a bug is characteristic of the template.
