### ISSUE TITLE
Production demos import issues with moment path and chart.js version

### ISSUE THREAD

**Issue by mbfrydman** [puikinsh/gentelella#53]
Working with the production demo there are 2 issues (index.html 1-3 and others) :

```
  <!-- daterangepicker -->
  <script type="text/javascript" src="js/moment.min.js"></script>
```

Seemingly moment was moved to its own folder
FIX:
`  <script type="text/javascript" src="js/moment/moment.min.js"></script>`

Also included chart.js version 2.0.0-beta2 gives error with the Doughnut function
Reverting to 1.0.1-beta.4 is a temporary fix

**Comment by christianesperar** [comment]
Fixes included on https://github.com/puikinsh/gentelella/pull/54
