### ISSUE TITLE
sidebar menu cant open

### ISSUE THREAD

**Issue by mynameisbams** [puikinsh/gentelella#533]
when i click the menu, it open then close again... what happen?

**Comment by William-H-M** [comment]
Hi, does this happen on a specific page or overall? and can you give us the browser in which the problem appears? as for me on firefox 54.0.1 has currently no problems

**Comment by mynameisbams** [comment]
sorry its my bad :)... now its work properly

**Comment by William-H-M** [comment]
Hi, great it's solved, as now there's no more issue can you please close this ticket? Thanks, have a nice day :)
