### ISSUE TITLE
Need to show daterangepicker before clicking the input element

### ISSUE THREAD

**Issue by Irishm** [puikinsh/gentelella#534]
Hi! I relocate the daterangepicker at the left menu and I'd like to show it when the page is load (not until I click the input element) and that remains there until the menu collapses for smaller screens and can be hide, but it gets almost imposible with css for all those functions envolved.
 
this.element.is("input")?this.element.on({
				"click.daterangepicker":i.proxy(this.show,this),
				"focus.daterangepicker":i.proxy(this.show,this),
				"keyup.daterangepicker":i.proxy(this.updateFromControl,this)
			})

![captura de pantalla 2017-07-17 14 37 05](https://user-images.githubusercontent.com/29817337/28286634-75efc636-6afe-11e7-939d-e142b7fd91de.png)

**Comment by AndreiCN** [comment]
Hi,

Do you get errors or something ?

**Comment by Irishm** [comment]
No, no errors
