### ISSUE TITLE
How to use different daterangepicker design??

### ISSUE THREAD

**Issue by bayuiravvan** [puikinsh/gentelella#535]
Based on `function init_daterangepicker_single_call()` on build\js\custom.js, I used this code to change daterangepicker style:

    $('input.js-daterangepicker').daterangepicker({
        singleDatePicker: true,
            locale: {
                format: 'YYYY/MM/DD'
            },
        singleClasses: 'picker_1'
    });

But the daterangepicker always use the default style. How do I use different style?

**Comment by AndreiCN** [comment]
What we have in our template it's just a sample, for more examples of usage you can check [this](http://www.daterangepicker.com/#examples).
