### ISSUE TITLE
Problem With datatable-buttons

### ISSUE THREAD

**Issue by salehinRafi** [puikinsh/gentelella#536]
Hello Guys, When I'm trying to use **datatable-buttons**, a problem occurs when viewing in mobile view. or shrink the browser (to check the responsive view).  Search Box and data in the table will display even outside the layout it should be. You can try by viewing in mobile view on [table_dynamic.html](https://colorlib.com/polygon/gentelella/tables_dynamic.html) on Button Example part . Thank you.

**Comment by AndreiCN** [comment]
What you mean by "datatable-buttons" , can you provide a screenshot please ?

**Comment by salehinRafi** [comment]
"datatable-buttons" I'm referring to is a **id** for the data table for Button Example example itself. Problems occur as what I stated above. Here is the preview when I resize the browser window:- 

<img width="251" alt="capture" src="https://user-images.githubusercontent.com/20961380/28346410-91cbb566-6c63-11e7-94ba-5ede7f7bb2bc.PNG">

The same thing happens when viewing in mobile but only **Search box** does not display properly. 
Also, I found when I try to write/echo long string such as an address. The problem persists as the perusal image above.

**Comment by William-H-M** [comment]
Hi, if not wrong this should be related to #400 if you want you can use the fix I left there, or you can wait until next major release. (maybe as I'm not collaborator of the project so I'm just saying random things)

**Comment by salehinRafi** [comment]
Hi, Thank you for pointing out your solution @William-H-M . Will try your solution for the mean time. Regards.

**Comment by AndreiCN** [comment]
Yep this is a related one , already done.
