### ISSUE TITLE
Need to change parent element of one out of 3 calenders

### ISSUE THREAD

**Issue by Irishm** [puikinsh/gentelella#537]
Hi! I need to change de parent element just for the left bar single calender (this.parentEl="body", instead of 'body' I need 'li.cal_side' but just for one), but in the js file, just let me change the parent for all of them. I still don't know how to stablish a difference between them. Any help is very welcome. BTW the issue is mine, nothing wrong with the template.

![captura de pantalla 2017-07-20 13 37 23](https://user-images.githubusercontent.com/29817337/28433421-1d040c58-6d51-11e7-8ee6-36844fa8fa94.png)
![captura de pantalla 2017-07-20 13 36 51](https://user-images.githubusercontent.com/29817337/28433425-235517c8-6d51-11e7-8ed8-c10b5bcfbf50.png)

**Comment by AndreiCN** [comment]
Still encounter this issue @Irishm ?
