### ISSUE TITLE
Support for PHP

### ISSUE THREAD

**Issue by rokrapoorv** [puikinsh/gentelella#538]
How to migrate the Front End of the website to native PHP project.

**Comment by Raikia** [comment]
Are you joking

**Comment by omega-inspiron** [comment]
He must be joking.  There's nothing to migrate.

**Comment by ccoltman** [comment]
Step 1: Learn PHP

**Comment by QAQTOT** [comment]
Step 2:Copy to Project

**Comment by rokrapoorv** [comment]
Apologies, should not have asked here.

**Comment by krzysiekpiasecki** [comment]
@rokrapoorv The example is [here](https://github.com/krzysiekpiasecki/Gentelella). Read also project README section "Gentelella for other platforms and frameworks".
