### ISSUE TITLE
CSS Gradient uses old style

### ISSUE THREAD

**Issue by micksp** [puikinsh/gentelella#540]
When incorperating Gentelella stylesheet into my Laravel 5.4 project, I got this error when building the scss: 

> (Emitted value instead of an instance of Error) autoprefixer: ...../node_modules/gentelella/src/scss/custom.scss:3644:2: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
When i change the scss on the mentioned places the error goes away. e.g.: 
`background: linear-gradient(top, rgba(247, 249, 250, 1) 0%, rgba(240, 240, 240, 1) 100%);`
changed to
`background: linear-gradient(to bottom, rgba(247, 249, 250, 1) 0%, rgba(240, 240, 240, 1) 100%);`

These are the lines this occurs (v. 1.3.0): 
gentelella/src/scss/custom.scss:3619:2
gentelella/src/scss/custom.scss:3628:2
gentelella/src/scss/custom.scss:3644:2:
gentelella/src/scss/custom.scss:3653:2
gentelella/src/scss/custom.scss:3715:2

Is this something I did wrong or do we need a fix?

**Comment by William-H-M** [comment]
Hi, for the last release this has been solved on the commit of #330 you can see there all that was updated.
