### ISSUE TITLE
Added menu_fixed to the sidebar, but scroll doesn't work / show up. I can't scroll through the sidebar.

### ISSUE THREAD

**Issue by kensixx** [puikinsh/gentelella#542]
As the title says. 

I just added an external style="overflow:auto;" in the sidebar div class just to make the scroll "work" but it looks untidy. 

menu_fixed doesn't work. Please help! Thank you! =)

**Comment by AndreiCN** [comment]
A screenshot please ?

**Comment by AndreiCN** [comment]
We assume you solved this one on your own after all so we will close this one for now.
