### ISSUE TITLE
Merge text is visible

### ISSUE THREAD

**Issue by Talha5** [puikinsh/gentelella#543]
If you go to [this](https://colorlib.com/polygon/gentelella/form.html?country=&optionsRadios=option1&iCheck=on) link, you'll see git ref on top left corner of the page.

**Comment by William-H-M** [comment]
Hi, this is only for the live version that hasn't been upload, on the project on git this is not a problem.
related to #433

**Comment by AndreiCN** [comment]
Yes, this one was already solved, we will update the live version also.
