### ISSUE TITLE
CSS file are not consistent.

### ISSUE THREAD

**Issue by holmescn** [puikinsh/gentelella#544]
I am trying to re-architecting the css file. I added some visual regression tests with PhantomCSS. But when I change the css files which generated by the gulp script, or use the non-minified css versionin `build/css`, both are cause the result changed.

Some which file should I rely on?

![index-left_col fail](https://user-images.githubusercontent.com/548039/28764819-22c2f3d2-75fa-11e7-9828-ba73b849ced2.png)

**Comment by AndreiCN** [comment]
The best solution would be to start from our default version and remove what you don't need and from what I see it seems like it's something wrong with paths there ( build/custom.min.css )
