### ISSUE TITLE
Running the app

### ISSUE THREAD

**Issue by girlintech1** [puikinsh/gentelella#546]
Please how can I run the web application ? Should I use node.js, php or JEE ?

**Comment by William-H-M** [comment]
Hi, I really don't understand what you're asking, this is an HTML template you just copy and then adapt your application to the style of the template, you don't need server languages.

More exactly what were you asking? Or in what you need help?

**Comment by AndreiCN** [comment]
It's been a while since we didn't hear from you so we will close this for now assuming you solved this one on your own.
