### ISSUE TITLE
Lenght range

### ISSUE THREAD

**Issue by robertocapannelli** [puikinsh/gentelella#547]
data-validate-lengthRange (like the example) doesn't work, I am trying to get the minimum value. I've tried also data-validate-length-range as suggested in documentation but It doesn't work neither.
What about this mismatch? Which Should I use? Other suggestions? Thanks in advance

**Comment by William-H-M** [comment]
Hi, looks like @yairEO fixed this on his lastest commit, I'll checkout the example here and do a PR later.

For now I think this could be close, Thanks.

https://github.com/yairEO/validator/issues/46

**Comment by William-H-M** [comment]
Hi, @AndreiCN there's no feedback about this. should be closed? And wait till got some answer as it's looks like @yairEO solved this on his side.
