### ISSUE TITLE
Unable to host this on Heroku

### ISSUE THREAD

**Issue by pvrao80** [puikinsh/gentelella#548]
I have a huge challenge to host this Gulp.js Bootstrap website on Heroku. Can i know if anyone has set it up on Heroku. Can i know if anyone could help me with the process steps ?

**Comment by AndreiCN** [comment]
Unfortunately we didn't test it on Heroku and also nobody else seems to react on it in this amount of time so we will close this for know, hope that you solved it after all.

**Comment by pvrao80** [comment]
Thanks Andrei. I have not solved it, working on it. Thank you.

Thanks & regards,
Pradeep Vamana
