### ISSUE TITLE
Datatable don't have bottom scroll on mobile view

### ISSUE THREAD

**Issue by Codingba** [puikinsh/gentelella#553]
Hello, 
my datatable isn't full responsive. Use default dynamic table. On my table don't show scroll on bootom. 
Regards.

**Comment by AndreiCN** [comment]
Can you please provide a screenshot ?

**Comment by girish2477** [comment]
Hi, I am also noticing that table is not fully responsive to iPhone screen. Attaching screenshot as requested.
![table not adjusting to width of device](https://user-images.githubusercontent.com/13156925/33355287-dec37b2c-d484-11e7-96c7-8cd5b0dc86e4.PNG)

**Comment by William-H-M** [comment]
@girish2477  Hi, that's because that is the basic example with no [responsive extension](https://datatables.net/extensions/responsive/examples/styling/bootstrap.html)

**Comment by girish2477** [comment]
William - thanks. Your suggestion made it workable for iPhone.

I noticed another issue which not related to responsiveness but data load. If I add 25000 rows to data table its takes very long to load the data and apply pagination and search to the page.

**Comment by William-H-M** [comment]
@girish2477 That you're doing WHAT 0_0?  Please don't do that! For very large data please don't load it into the DOM! Maybe some newer PC will be able to handle it, but you know clients almost never have a PC with Intel core last generation with 16GB of RAM! _[At least not in my country!]_ (And don't tell me about it with a SmartPhone...)

For those case please use [Server-side processing](https://datatables.net/examples/data_sources/server_side.html)

Here there was some kind of [conversation ](https://datatables.net/forums/discussion/8789/tips-for-using-datatables-with-very-large-data-sets)with some manager [_I guess_] that will help you understand a few things.

If you need more example Server-side processing you'll need to take a look at either StackOverflow or some other page.

> There are many ways to get your data into DataTables, and if you are working with seriously large databases, you might want to consider using the server-side options that DataTables provides. With server-side processing enabled, all paging, searching, ordering actions that DataTables performs are handed off to a server where an SQL engine (or similar) can perform these actions on the large data set (after all, that's what the database engine is designed for!).

From: https://datatables.net/examples/server_side/


Good luck!

**Comment by girish2477** [comment]
William - TFLMK :)
I was just playing around with the template to ensure it fits the requirement and hence created mock data in HTML itself. Thanks for your advice and links to server-side processing.
