### ISSUE TITLE
Login page invisible components 

### ISSUE THREAD

**Issue by rexwangcc** [puikinsh/gentelella#556]
Hi, this template is so nice I start to use it for our new project, but when I use the login page there was an issue about invisible components. When you click the create account and jump to register form, it seems the login form is still there but just invisible, it is annoying cuz the `button`/`link` still works..

I'm wondering if there is a way to solve this without removing the animation and use two pages instead?

* To reproduce the issue: https://colorlib.com/polygon/gentelella/login.html#signup

![gentellabug](https://user-images.githubusercontent.com/14366016/29723284-fa098680-8991-11e7-8f81-cb83cc435a81.png)

**Comment by AndreiCN** [comment]
Actually this is a bug, thank you @rexwangcc for reporting this !

**Comment by rexwangcc** [comment]
@AndreiCN  Thanks for your prompt reply on this issue! Looking forward to the next update :)

**Comment by emanuel-campos** [comment]
#595

**Comment by emanuel-campos** [comment]
this issue has been resolved in the pull request below.
#595

**Comment by AndreiCN** [comment]
solved it.
