### ISSUE TITLE
Conflict Message is visible on form.html in Template Demo

### ISSUE THREAD

**Issue by erickueen** [puikinsh/gentelella#557]
When you access to https://colorlib.com/polygon/gentelella/form.html you can see on the top of the page the following message:
<<<<<<< HEAD ======= >>>>>>> refs/remotes/puikinsh/Development

**Comment by William-H-M** [comment]
Hi this isa duplicate of 
#402 
#543 
#552 <-- just 5 issue ago....

as this is a duplcate please close it as this will be solved on live for next release:

> We already took care of that, will be available with the next update.

@AndreiCN
