### ISSUE TITLE
左边菜单栏展开与合并的问题?

### ISSUE THREAD

**Issue by jqlinux** [puikinsh/gentelella#558]
例如:
点击"用户中心------>用户"  访问地址: http://127.0.0.1:8000/user/,
然后如果点击"用户中心------>用户" 页面中的另外一个链接:http://127.0.0.1:8000/user/create
菜单栏就合并了,并不是展开并指向用户

**Comment by AndreiCN** [comment]
English please ?

**Comment by jqlinux** [comment]
Such as:
Click on the "user center" -- -- -- -- -- - > user access address: http://127.0.0.1:8000/user/,
Then if you click on "user center -- -- -- -- -- - > user" another link in the page: http://127.0.0.1:8000/user/create
The menu bar is merged, not to expand and point to the user

**Comment by AndreiCN** [comment]
Please provide a screenshot, your server si a local one, it doesn't work for us.

**Comment by jqlinux** [comment]
![Uploading 微信截图_20170901160226.png…]()
![Uploading 微信截图_20170901160314.png…]()

**Comment by jqlinux** [comment]
![_20170901160226](https://user-images.githubusercontent.com/14269139/29960761-8bef9268-8f2f-11e7-8681-2185373441d0.png)
![_20170901160314](https://user-images.githubusercontent.com/14269139/29960754-88f5288e-8f2f-11e7-8c32-c7c346fef799.png)

**Comment by AndreiCN** [comment]
Ok ok, I'm not quite sure how could we help you here :)

**Comment by William-H-M** [comment]
@AndreiCN I think he's talking about, you know the dynamic links on the adress bar, related to #492

**Comment by AndreiCN** [comment]
Well I get it now, thank you @William-H-M.

@jqlinux you already have the solution, we will close this ticket for now, good luck !
