### ISSUE TITLE
Using another version of datatables makes things not working anymore

### ISSUE THREAD

**Issue by starcraft04** [puikinsh/gentelella#559]
Hi,

I tried to include my own version of datatables by including in my page the link to the css and js file from the new datatables I just downloaded and now gentellela is not working anymore, I get the following error:
custom.min.js:1 Uncaught TypeError: $(...).smartresize is not a function
    at init_sidebar (custom.min.js:1)
    at HTMLDocument.<anonymous> (custom.min.js:3)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)

I tried to remove the init_datatables() function in the custom.min.js that I use but still same issue.

**Comment by AndreiCN** [comment]
Since is another version of it ( datatables ) your errors comes from initialization. Make sure you create another function that doesn't creates any conflict or you can use our version by default.
