### ISSUE TITLE
Custom.css and Custom.min.css not aligned

### ISSUE THREAD

**Issue by zbubric** [puikinsh/gentelella#563]
It seems that CSS content of custom.css and custom.min.css ('unminified') is different.
I accidentally noticed that some of my H2 tags start behaving wierd and, after all troubleshooting I noticed that there was a PR merge few days ago. When I tried to switch to min version, everything work as expected.
I 'unminified' file and compare it to original and notice some difference.
Well, i'm not a css expert so sorry if this issue is a misslead...

**Comment by AndreiCN** [comment]
We will check into that thank you for reporting this.

**Comment by Miosss** [comment]
+1

**Comment by itayB** [comment]
+1

**Comment by jetchirag** [comment]
This issue seems to be bugging again. Noticed difference (size of typography tags) when custom.css is used.

**Comment by funilrys** [comment]
Look at https://github.com/puikinsh/gentelella/commit/558cd90192274dbff1e3dee9eb0cefbf27491b17 and enjoy the view ...

If you build `custom.scss` well, no luck everything is gone ...

Again, it's related to https://github.com/puikinsh/gentelella/issues/406#issuecomment-360045680 : Changes should be made into the scss not into the css ...
