### ISSUE TITLE
Form validation bug

### ISSUE THREAD

**Issue by jacksbox** [puikinsh/gentelella#564]
There is a bug in the validation.js version you are using.
Should you use data-validate-words on an field, all other validations on that field are ignored.
Example: https://colorlib.com/polygon/gentelella/form_validation.html
Field Name has data-validate-words=2 and data-validate-length-range=6, but, "is is" gets accepted (2 words, but only 5 characters)
The version of the plugin is super old, 1.1 - its currently on 3.x - maybe an update would be appropriate?

**Comment by AndreiCN** [comment]
We will update this to the latest version, thank you !

**Comment by AndreiCN** [comment]
Form validation bug - updated to the latest version ( form validation plugin )
