### ISSUE TITLE
a copy of this being sold?

### ISSUE THREAD

**Issue by ckozler** [puikinsh/gentelella#565]
Came across this

https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S

Not sure if its yours or repackaged or what but figured I'd post it. It'd be a shame if someone is ripping off your great work

**Comment by krzysiekpiasecki** [comment]
Read https://github.com/puikinsh/gentelella/blob/master/LICENSE.txt and then close this issue.

**Comment by William-H-M** [comment]
Hi this is under a MIT license so basically you can do whatever you want with it as soon as you include the notice, and yes that include sell the product. Or at leat that's what I understand.

https://github.com/puikinsh/gentelella/blob/master/LICENSE.txt

This could be closed

**Comment by AndreiCN** [comment]
Answered and closed.
