### ISSUE TITLE
MultiLevel Menu not working on minified sidebar

### ISSUE THREAD

**Issue by marcosguerrini** [puikinsh/gentelella#566]
(Sorry for my bad english)
When you try to open the second level of a menu in the minified sidebar the menu automatically closes.

**Comment by AndreiCN** [comment]
Already fixed that, will be available with the next update.

**Comment by antonioaltamura** [comment]
In the meantime could we have the snippet to solve this bug?

**Comment by AndreiCN** [comment]
@antonioaltamura take a look at #492 ticket, will solve your issue.

**Comment by antonioaltamura** [comment]
nop, it doesn't solved.
This is my menu
```
<ul class="nav side-menu">
	<li><a href="home.html"><i class="fa fa-home"></i> Home</a></li>
	<li><a a href="javascript:void(0)"> item1 <span class="fa fa-chevron-down"></span></a>
		<ul class="nav child_menu">
			<li><a href="javascript:void(0)">subitem <span class="fa fa-chevron-down"></span></a>
				<ul class="nav child_menu">
					<li><a href="subitem1.html">subsubitem1 </a></li>
				</ul>
			</li>
		</ul>
	</li>

</ul>
```

**Comment by William-H-M** [comment]
Hi, @antonioaltamura Andrei referenced wrong issue is the #490 not the 492.
The fix is this: https://github.com/puikinsh/gentelella/issues/490#issuecomment-310226241

**Comment by AndreiCN** [comment]
Ah that's right, thank you @William-H-M and @antonioaltamura #490 will solve your issue this time :)

**Comment by antonioaltamura** [comment]
thanks
