### ISSUE TITLE
i can't use a favicon

### ISSUE THREAD

**Issue by BorregaXD** [puikinsh/gentelella#570]
i can't use a favicon 
![captura de pantalla de 2017-09-11 11 26 14](https://user-images.githubusercontent.com/31866739/30297628-fbfbd7de-970d-11e7-877e-7d30033d90ff.png)
![captura de pantalla de 2017-09-11 11 27 12](https://user-images.githubusercontent.com/31866739/30297653-18dc55fe-970e-11e7-9445-bad28c2b74fb.png)

**Comment by William-H-M** [comment]
Hi, sorry but could yo be more specific on your problem? I don't understand with that you can't use a favicon.

Did you try something like:
`<link rel='shortcut icon' type='image/x-icon' href='/favicon.ico' />`

**Comment by BorregaXD** [comment]
i try to use in mozilla and midori and it's the same result, and i cleaned the cache and nating... sorry for mi english

**Comment by funilrys** [comment]
It'll be better to get the output of the developer console (Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac)) ... We can't help you with the few information we have ...

**Comment by AndreiCN** [comment]
Please come bag with more details about issue and will reopen this.
