### ISSUE TITLE
bulk_action doesnt work

### ISSUE THREAD

**Issue by aladdinfyp** [puikinsh/gentelella#571]
Hi, firstly thank u for the open source template!
I have used your template for my project and is facing some issues currently. 

I have imported every js and css into my project however i cant seem to see the bulk_action table work. The checkbox cant be seen on the table at all. 

May i know whats the issue?
![img](https://user-images.githubusercontent.com/29227309/30379127-0b9cf720-98c8-11e7-919e-0c922668aa96.PNG)

**Comment by AndreiCN** [comment]
Hard to tell, make sure you have the right paths in ( there css/js ) and also that your checkboxes does exist in your html file.
