### ISSUE TITLE
Errors when integrating table into project

### ISSUE THREAD

**Issue by aladdinfyp** [puikinsh/gentelella#572]
![image](https://user-images.githubusercontent.com/29227309/30389043-590ed944-98e4-11e7-8e17-b81c9f768632.png)

I see these errors when i run my project. May i know how to solve it ?

THank u

**Comment by William-H-M** [comment]
Hi, I see that you have JQuery 3.2.1 could it be that you're loading two different versions of jquery?, could you try using the defined JQuery version of the template only 2.2.4.

Does mobileAnalyticDashboard.jsp loads another library ?

**Comment by aladdinfyp** [comment]
Hi William, 
I have these js scripts in mobileAnalyticDashboard.jsp

       <script src="../assets/js/jquery.min.js" type="text/javascript"></script>   
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src=" https://cdn.jsdelivr.net/npm/parsleyjs@2.7.2/dist/parsley.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js" type="text/javascript"></script>
        <script src="../assets/js/echarts-all.js" type="text/javascript"></script>
        <script src="../assets/js/custom.js" type="text/javascript"></script>
        <script src="../assets/js/jquery-1.11.1.min.js" type="text/javascript"></script>
        <script src="../assets/js/icheck.min.js" type="text/javascript"></script>
        <script src="../assets/js/green.js" type="text/javascript"></script>

The bulk_action table seems to be working only when I remove  <script src="../assets/js/jquery-1.11.1.min.js" type="text/javascript"></script>. But my graphs would not display correctly. 

Do you happen to know why is this so?

Thank you.

**Comment by William-H-M** [comment]
Hi, the problem is that you're including two version of Jquery and they're conflicting, you should choose to either update the scripts of the chart and that way make it that works with JQuery 2.2.4, that is the version that this template use, or don't use the version.

I guess that you're using this library https://github.com/chartjs/Chart.js that0s currently on V 2.7.0
