### ISSUE TITLE
Finish button on smart wizzard issues

### ISSUE THREAD

**Issue by nicoativo** [puikinsh/gentelella#573]
Im not very good at jquery or other scripts so I find myself having a hard time to understand the functionality of the script 

I used the template gentelella alella and one of its features. The smart wizard. Can someone please help me overcome my problem. So here it is

I want to make the finish button to function like an submit button inside a form. But i dont know how to make the "finish" button triggers my form to submit all the input data in the other page. Please help me how could I edit the script to make finish button to function as submit button.

**Comment by AndreiCN** [comment]
This could help you, maybe someone else had the same issue before.

**Comment by William-H-M** [comment]
@AndreiCN I'll leave here the general solution and in case someone else need it will be here for record:
on init smartWizard add this config option
```
  $('#wizard').smartWizard({
            onFinish:onFinishCallback
  });
```
Then we create that function with which we'll submit our form

```
  function onFinishCallback(objs, context) {
     $('form').submit();
   }
```
Done.

**Comment by AndreiCN** [comment]
Ok @William-H-M, thank you for your contribution !
