### ISSUE TITLE
Datepicker issue. can't select  year 1991 by one click 

### ISSUE THREAD

**Issue by aMpujari** [puikinsh/gentelella#574]
I can't select year by using date picker. I have to click previous arrow ten time to go on 2007 year calendar.

**Comment by William-H-M** [comment]
Hi, of which picker are you talking about as per the files we have two pickers
http://eonasdan.github.io/bootstrap-datetimepicker/
and
http://www.daterangepicker.com/
if it's the one of eonasdan then
you can set the format to only picker years
`format: 'YYYY'`
other ways is using that will start the view with the years selection
`viewMode: 'years'` or decades 

if the second one then this could help you more http://www.daterangepicker.com/#ex3

**Comment by aMpujari** [comment]
Even i can't change ID of datepicker! whenever i change its id from single2cal2 to DateOfBirth. it stopped functioning ! Is there any other date picker available which first select year then month and finally days! please help!

**Comment by William-H-M** [comment]
@aMpujari sorry but, as I said before at least you tell me which picker you're using It'll be impossible for us just to guess what's going on, could you at least please show the code you're using or maybe a screenshot that way we will know which you're using and try to see if your console is throwing some error.

**Comment by aMpujari** [comment]
<div class="form-group"> 
                   <label class="control-label col-md-2 col-sm-3 col-xs-12" for="currentDate">Date Of Birth <span class="required">*</span>
                        </label>     
                  <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                  
                    <div class="col-md-12 xdisplay_inputx form-group has-feedback">
                                <input type="text" class="form-control has-feedback-left" id="single_cal1" placeholder="Current Date" aria-describedby="inputSuccess2Status2" >  
 <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                                <span id="inputSuccess2Status2" class="sr-only">(success)</span>
                  </div>                    
                  </div>
                  </div>
above is html tag and following is screen shot! 
![datepicker](https://user-images.githubusercontent.com/32033126/30587341-6baa8880-9d50-11e7-88b1-d3b7ff687bef.JPG)
I want user can select year by clicking on year and then select month and date respectively!

**Comment by William-H-M** [comment]
Hi, now I see which picker you're using http://www.daterangepicker.com not totally sure but with that picker that option is not possible, I'll recomend you to use http://eonasdan.github.io/bootstrap-datetimepicker
which is included on this project on #504 and use [viewMode ](http://eonasdan.github.io/bootstrap-datetimepicker/#view-mode)option with the parameter 'decades'
which will help you with your needs

**Comment by aMpujari** [comment]
Thank you sir,
I am using this datetimepicker from above mention site
<script type="text/javascript">
  $(function () {
      $('#datetimepicker1').datetimepicker({
          viewMode: 'years',
          format: 'MM/YYYY' // going to change format as DD/MM/YYYY
      });
  });

and 

 <div class="col-md-12 xdisplay_inputx form-group has-feedback">
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                      <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                                <span id="inputSuccess2Status2" class="sr-only">(success)</span>
                </div>
                       </div> 

The question is I just want dd/mm/yyyy format date , i does not want time !  How do i do this ?
i also wnat js and css file of above date-picker 
, i am newbie in github and i does not know how to download and install bower and other things , is there any downloadable link for css and js file ?

**Comment by William-H-M** [comment]
Hi, on this [fiddle ]( https://jsfiddle.net/William_/20oywuno/)you can play with the picker on the `format` option just add your format i the same place. on the left side where says External reosurce you can download the files if need it.

You can always follow this: http://eonasdan.github.io/bootstrap-datetimepicker/Installing/#manual

if you have bootstrap  no need to use collapse.js and tansitions.js and you can just download the picker from it's own repo https://github.com/Eonasdan/bootstrap-datetimepicker
The need it files are on the build folder

As this been solved please close this issue thanks.

**Comment by aMpujari** [comment]
I am using datetimepicker and also include mentioned moment.js , bootstrap-datetimepicker.min.js and bootstrap-datetimepicker.css file but it does not work, Here is snapshot of the problem:
![issue1](https://user-images.githubusercontent.com/32033126/30631283-52efabde-9e01-11e7-9490-6222ca491e66.jpg)
![issue2](https://user-images.githubusercontent.com/32033126/30631290-58dfc1b4-9e01-11e7-9e66-cf9c0a6acaae.jpg)

**Comment by William-H-M** [comment]
Hi, @aMpujari sorry but with just an image I can't guess what's going on I need more info like if it does have a console error or something, please try to follow the example of the fiddle I gave before https://jsfiddle.net/William_/20oywuno/ like the template and the order of the scripts, always first moment and the datepicker min.

Now as this is not an error of this template this "ticket" should be closed.

here are some SO answer
https://stackoverflow.com/questions/34728490/bootstrap-date-time-picker-is-not-working
https://stackoverflow.com/questions/41236574/bootstrap-datetimepicker-not-working-with-the-jquery-3

**Comment by AndreiCN** [comment]
Hope you handled this @aMpujari after all, we will close this one for now.
