### ISSUE TITLE
Modal buttons are not aligned

### ISSUE THREAD

**Issue by shaohui-wang** [puikinsh/gentelella#575]
In the latest edition,modal buttons are not aligned
![tim 20170919134339](https://user-images.githubusercontent.com/30097401/30577398-8fcc94c0-9d40-11e7-8cea-ee8155c4fe75.png)

**Comment by AndreiCN** [comment]
Thank you @shaohui-wang for reporting this, we will take care of it.

**Comment by AndreiCN** [comment]
I checked into it and it seems like is no such issue there, please check your CSS. Issue closed.

**Comment by shaohui-wang** [comment]
Thank you! I use the "npm install gentelella --save" download code,It has this problem, But I downloaded the latest code from github is no problem, maybe npm is not up to date(I'm not a professional web engineer,if I have  said something wrong,don't mind please).

**Comment by AndreiCN** [comment]
npm it's not up to date indeed, we'll solve that too, thank you !
