### ISSUE TITLE
Input type number not showing correctly

### ISSUE THREAD

**Issue by TAiS46** [puikinsh/gentelella#58]
I don't know how to fix this. Maybe it is also a third party tool which we need to fix!

First input is text second one is number.

![Image of Yaktocat]
(http://i.imgur.com/39cQqG0.png)

**Comment by christianesperar** [comment]
I think there is nothing wrong with the example. This form just show different type of input you can do with gentella. If you want phone number you can easily add it to your own form.

**Comment by TAiS46** [comment]
There is. The number field (11) has a padding inside the input. You can see that the number inside the input is near the bottom of the input field

**Comment by christianesperar** [comment]
Ok saw it. Thanks for detailed response.

PR: https://github.com/puikinsh/gentelella/pull/60
