### ISSUE TITLE
[Q] Fixed side menu?

### ISSUE THREAD

**Issue by phrfpeixoto** [puikinsh/gentelella#581]
Hello there,

I'm not a frontend developer at all. I've been using bootstrap to get by so far.
Just got to know Gentella and I love the look and feel. Thank you for your work on this.

My question is about a fixed side menu. I looked around the examples and did not find any. Is there a simple way to fixate the side menu and scroll only the main content area?

Thanks!

**Comment by William-H-M** [comment]
Hi, please follow the template given on: https://colorlib.com/polygon/gentelella/fixed_sidebar.html
here where is the file: https://github.com/puikinsh/gentelella/blob/master/production/fixed_sidebar.html

**Comment by AndreiCN** [comment]
Hi there @phrfpeixoto, we will close this for now since you got an answer, good luck !

**Comment by phrfpeixoto** [comment]
Thank you!
