### ISSUE TITLE
How to Use Select2 ?

### ISSUE THREAD

**Issue by karan4364** [puikinsh/gentelella#585]
Hi,
I want to use select2.js. 
like this Screenshot. How Can I Implement?
![screen shot 2017-10-05 at 6 12 46 pm](https://user-images.githubusercontent.com/25763562/31227805-dc14306c-a9f8-11e7-9889-f8d514a78ffc.png)

**Comment by William-H-M** [comment]
Hi, a simple look up on google throw this....
https://select2.org/getting-started/basic-usage
@AndreiCN  please close this as a low quality ticket...
