### ISSUE TITLE
Release gentenella in npm to 1.4.0 version

### ISSUE THREAD

**Issue by v-rudkovskiy** [puikinsh/gentelella#586]
Please can you release gentenella 1.4.0 version in npm

**Comment by cristianraiber** [comment]
@v-rudkovskiy - We are working on that.

**Comment by William-H-M** [comment]
@cristianraiber shouldn't this be a 
Duplicate of #524 ?

**Comment by cristianraiber** [comment]
@William-H-M - yep, it is.
