### ISSUE TITLE
fullcalendar.js and custom.min.js clash

### ISSUE THREAD

**Issue by Lucifer0601** [puikinsh/gentelella#587]
Hi,

we using gentelella admin template in project, and normal work without fullcalendar.js.

But now there is new reqirement,and need to add the fullcalendar.js into project, but fullcalendar.js and custtom.min.js clash, the fullcalendar event (dayClick & eventClick) unable work, how to fix? pls kindly advice, 
![qq 20171010095232](https://user-images.githubusercontent.com/19774550/31365912-d78fc01e-ada0-11e7-8dfd-f17a2c95ff9d.png)
![qq 20171010095337](https://user-images.githubusercontent.com/19774550/31365937-ffc93fec-ada0-11e7-9ba8-f58f115659a7.png)

tks.

**Comment by William-H-M** [comment]
Hi can you show us the console error, do you know if the fullcalendar include his own version of JQuery?

**Comment by AndreiCN** [comment]
@Lucifer0601 you still have this issue ? If you do please provide that screenshot or close the ticket if you don't.

**Comment by Lucifer0601** [comment]
@AndreiCN  the issue also exist, now web loaded,but only show the header,like below screenshot, when we manual click the button, the calendar can show.

And the dayClick and eventClick unable work. can you help to remote our PC，and we can provide the teamviewer to you.

**Comment by Lucifer0601** [comment]
![qq 20171012151859](https://user-images.githubusercontent.com/19774550/31483976-fdbe5f40-af60-11e7-9030-95ea2b7745b2.png)
