### ISSUE TITLE
How to work with charts?

### ISSUE THREAD

**Issue by gesquivelob** [puikinsh/gentelella#588]
Hi! How I can work and generate my own charts?

Thanks!

**Comment by AndreiCN** [comment]
What type of chart do you want to generate ?

**Comment by jcohenho** [comment]
I'd like to generate line charts just like in the demo for "Network Activities". Any examples for how to set this up?

**Comment by gesquivelob** [comment]
Any used in Gentelella template: http://admin.tragos.mx/

Just need one example of how this charts works, and I can asume the rest :)

**Comment by AndreiCN** [comment]
Your link it doesn't work , for examples take a look on js/custom.js , you'll see in there how they are used.
