### ISSUE TITLE
Bootstrap Modal how to auto render the fullcalendar?

### ISSUE THREAD

**Issue by Lucifer0601** [puikinsh/gentelella#589]
Hi all,

There is one project to use bootstrap modal to render the fullcalendar, when the modal show, but the fullcalendar cannot auto to render, and need manual to click the button text，pls kindly how to set up the fullcalendar auto to render once the modal show, thks.

**Comment by Lucifer0601** [comment]
below is screenshot.

![review1](https://user-images.githubusercontent.com/19774550/31536591-d6c07fd2-b031-11e7-9796-2b3ffa4ed7dc.png)

**Comment by Lucifer0601** [comment]
![review2](https://user-images.githubusercontent.com/19774550/31536609-e3623e6a-b031-11e7-83af-4cc6888799e6.png)

**Comment by Lucifer0601** [comment]
![review3](https://user-images.githubusercontent.com/19774550/31536632-efd8c15a-b031-11e7-9ddd-4f150aa46d9c.png)

**Comment by EmersonGarrido** [comment]
full callendar is ok man :+1:

**Comment by AndreiCN** [comment]
[This](https://github.com/fullcalendar/fullcalendar) could help you.

**Comment by AndreiCN** [comment]
@Lucifer0601 you still have that issue ? If you resolved it or if you have no further questions please close the ticket.
