### ISSUE TITLE
change label of DataTable buttons

### ISSUE THREAD

**Issue by alfaquinog** [puikinsh/gentelella#590]
Hello,

I need to change the DataTable text box Search label to Buscar
how can I do it?

**Comment by AndreiCN** [comment]
Go to tables_dynamic.html page , find "Search" label and just replace it with what you need to.

**Comment by William-H-M** [comment]
Hi, @AndreiCN  you can close this I'll copy paste what I wrote on the other issue:

> 
> @alfaquinog This is not something related to this template (Is not a bug, that's what I mean), but if you search at [DataTables](https://datatables.net/) official page this is the result https://datatables.net/reference/option/language
> For those kinds of question please use google, is not that hard.

**Comment by alfaquinog** [comment]
thank you very much.
I have another question, does not appear the button to export to excel only the rest of buttons like CSV, PRINT and Copy appear, but EXCEL does not appear.
