### ISSUE TITLE
Unwanted text on general form page

### ISSUE THREAD

**Issue by LeonardoVelarde** [puikinsh/gentelella#591]
I was browsing for templates and realized you have "<<<<<<< HEAD ======= >>>>>>> refs/remotes/puikinsh/Development" on the top.

Here's the screenshot just in case.
![gentellaheadmsg](https://user-images.githubusercontent.com/9455973/31742980-79015ba6-b427-11e7-8785-0ff295cceba3.png)

**Comment by William-H-M** [comment]
Hi... This has been solved
Duplicate of #435 
Duplicate of #543
Duplicate of #552
Duplicate of #557 

@AndreiCN you can close this please, and should be added an issue template that had a message "If the issue is about the text on general form... this has been fixed don't worry, but thanks :)"
