### ISSUE TITLE
Editing the Chart

### ISSUE THREAD

**Issue by bosssaurav** [puikinsh/gentelella#593]
How to I edit the chart in  index.html based upon my use....like how to pass parameters to this chart ???
 the given chart is demo!!!
This one:
<div id="chart_plot_01" class="demo-placeholder"></div>

Any help is highly appreciated!! :)
![chart](https://user-images.githubusercontent.com/22428191/31849411-59c33acc-b65f-11e7-98ec-880fd2e0db60.png)

**Comment by AndreiCN** [comment]
Hi @bosssaurav , you have [here](http://www.chartjs.org/samples/latest/) some samples, hope this will help you !
