### ISSUE TITLE
Problem in datatable-buttons

### ISSUE THREAD

**Issue by alfaquinog** [puikinsh/gentelella#594]
Hello,
I have another question, does not appear the button to export to excel only the rest of buttons like CSV, PRINT and Copy appear, but EXCEL does not appear.
Help me please.

**Comment by William-H-M** [comment]
Hi, can you please show us the code of what are you trying? We can't guess what's going on without at least seeing some code, just post here the most important code: 
 - HTML table.
- Scripts you're including. 
- How you init the plugin.

Without those we can't help.

**Comment by alfaquinog** [comment]
**ok, I work whith YII2 Framework, in the view my code is the following:**
<?php
use yii\helpers\Html;
use yii\grid\GridView;
?>
        <div class="x_panel">          
          <div class="x_content">          
                <?=
                \yiister\gentelella\widgets\grid\GridView::widget(
                    [                        
                        'dataProvider' => $dataProvider,                                              
                        'id'=>'proyecto-grid',
                        'columns' => [
                        'ID',
                        'NOMBRE',
                        'ESTADO',                        
                            ['class' => 'yii\grid\ActionColumn', 'template'=>'{update}{delete}',],
                        ],
                        'hover' => true,
                        'tableOptions' => [
                          'id' => 'datatable-buttons',
                          'class' => 'table table-striped table-bordered'],
                    ]
                );
                ?>                       
          </div>
        </div>


**My code in the controller is:**

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Proyecto::find()->where('ESTADO != :id',['id'=>2]),
            'pagination' => false, 
            'sort' => false, 
            
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }


**also in some computers yes the button is seen and in others it does not**

**Comment by alfaquinog** [comment]
I see that the excel button is the only one made in flash

**Comment by alfaquinog** [comment]
I already solved it thanks, was to remove all restrictions to the flash in my browser.

**Comment by alfaquinog** [comment]
I just wanted to know if the exported file can be given a custom name.

**Comment by alfaquinog** [comment]
**Please,

I need to know how to rename the files to be exported**

      $(document).ready(function() {
        var handleDataTableButtons = function() {
          if ($("#datatable-buttons").length) {
            $("#datatable-buttons").DataTable({
              dom: "Bfrtip",
              buttons: [
                {
                  extend: "copy",
                  className: "btn-sm"
                },
                {
                  extend: "csv",
                  className: "btn-sm"
                },
                {
                  extend: "excel",
                  className: "btn-sm"
                },
                {
                  extend: "pdfHtml5",
                  className: "btn-sm"
                },
                {
                  extend: "print",
                  className: "btn-sm"
                },
              ],
              responsive: true
            });
          }
        };

**Comment by selimgnaoui** [comment]
Hi all, 
After analysing the code and got familiar with it we might figured out a way to solve this issue. As you know when you apply Datatables on a HTML Table, all configurations will be set as Default (such as this case, the FileName of the exported file will be standard) , if you want to set a personalized Name to your file, you should prevent the default behaviour (configuration should not be set by Default). The   
solution would be wrinting a customized function using the appropriate Hooks. 
How does it look like to you? 

We'd be happy to hear a feedback or any suggestion from you! If not , we would like to start implementing the new soultion and provide you with details. ^^

**Comment by William-H-M** [comment]
Ok I think this should be closed now, this is not an error of the template and this can be found on DataTables documents [here ](https://datatables.net/extensions/buttons/examples/flash/filename.html)and [here](https://datatables.net/extensions/buttons/examples/html5/filename.html)

But just for the record here how you do it:

```
{
  extend: "excel",
  className: "btn-sm",
  filename: "The name that you want"
},

```

@AndreiCN this could be closed now
