### ISSUE TITLE
change name export files

### ISSUE THREAD

**Issue by alfaquinog** [puikinsh/gentelella#596]
**Please,

I need to know how to rename the files to be exported for example myfile.xlsx**

  $(document).ready(function() {
    var handleDataTableButtons = function() {
      if ($("#datatable-buttons").length) {
        $("#datatable-buttons").DataTable({
          dom: "Bfrtip",
          buttons: [
            {
              extend: "copy",
              className: "btn-sm"
            },
            {
              extend: "csv",
              className: "btn-sm"
            },
            {
              extend: "excel",
              className: "btn-sm"
            },
            {
              extend: "pdfHtml5",
              className: "btn-sm"
            },
            {
              extend: "print",
              className: "btn-sm"
            },
          ],
          responsive: true
        });
      }
    };

**Comment by Regi98** [comment]
<title>DataTables | Gentelella</title>

Try changing this code on your page.
