### ISSUE TITLE
Incorrect dropdown arrow

### ISSUE THREAD

**Issue by herusdianto** [puikinsh/gentelella#6]
Hi, awesome template!

In my browser, the placement of drop down arrow is strange. I'm using chrome v43.0.2357.65. Here is my screenshot:
![incorrect dropdown arrow](https://cloud.githubusercontent.com/assets/8720866/7875452/b61e63f8-05e7-11e5-9d73-89c1ba48a4a6.png)

Thank you.

**Comment by christianesperar** [comment]
Just remove arrow on this pr https://github.com/puikinsh/gentelella/pull/70

**Comment by christianesperar** [comment]
Can we close this?
