### ISSUE TITLE
Datatable functions not working when appending data

### ISSUE THREAD

**Issue by Regi98** [puikinsh/gentelella#600]
First of all, this theme is very well done thanks for sharing :)

Im having a bit of problem on the datatable buttons when I append some data in the table using firebase.js and jQuery. Here is what it looks like when I append the data, it creates another table on the bottom instead of filling in the table. So when I use its functionalities, such as saving as csv, printing and sorting, the table returns 0 data. 

Initial view:
![1](https://user-images.githubusercontent.com/26320821/32089419-79c42f90-bb1c-11e7-8fe4-96f9e6f892f0.PNG)

After clicking on the sort/search and all other datatable functionalities:
![capture](https://user-images.githubusercontent.com/26320821/32129462-1a236486-bbba-11e7-8348-bda6bd9e6833.PNG)

Here is what my code looks like:
![2](https://user-images.githubusercontent.com/26320821/32089474-c2e18ccc-bb1c-11e7-9cf7-c1646459f90e.PNG)
![3](https://user-images.githubusercontent.com/26320821/32089580-630a4a86-bb1d-11e7-8ae7-5a925721e609.PNG)

But when I input table data manually using html and without appending and using jQuery, the table works fine. Any help would be much appreciated. I really need it for our capstone. I think the datatable button functionality will be really useful in this project and any response would be nice

**Comment by tdtgit** [comment]
Is it a dataTable table? Did you try `add` function?

Demo: https://colorlib.com/polygon/gentelella/tables_dynamic.html

Working append row code:
```
$("#datatable").DataTable().row.add(['Name', 'Position', 'Office', '99', '1999/12/12', '999999']).draw();
```

More detail: https://datatables.net/examples/api/add_row.html

**Comment by Regi98** [comment]
Yes thats seems to be my error. Thanks tdtgit! 😄 👍

**Comment by Eve000017** [comment]
HI,
I meet the same issue where the append() table didnt function with the DataTable().
What can I do with the add function? Add instead of append?
Thank you.

**Comment by Eve000017** [comment]
Thank you for giving the suggestion above and I finally find the way to use DataTable() for firebase data. 
Is it possible for the search function to search two rows in one search type? like search user and filter the users in two rows.
Thanks again.
