### ISSUE TITLE
tutorials on how to integrate gentelella to a wordpress website?

### ISSUE THREAD

**Issue by Euclid1989** [puikinsh/gentelella#602]
Hi!
I'm currently working on a school project where we have to design a  peer-to-peer dashboard for a website. I have developed the website but now I wanted to integrate gentelella admin to the site and it has been giving me a hard time. Do you have any tutorial I might follow where I can learn more about this subject?

**Comment by AndreiCN** [comment]
Hi there,

Unfortunately we do not have any guide for it, you need back-end skills. This is a HTML ( front-end ) project only.
