### ISSUE TITLE
Export CSV

### ISSUE THREAD

**Issue by alfaquinog** [puikinsh/gentelella#603]
HELLO,

PLEASE HELP ME,

EXPORTING CSV DOES NOT DISPLAY TILDES AND Ñ
FOR EXAMPLE

Ã¯Â»Â¿"ID","Nombre","Estado","Â "

HOW DO I SOLVE IT?

**Comment by alfaquinog** [comment]
I AM USING GENTELELLA PLUGIN FOR YII2.0

**Comment by AndreiCN** [comment]
Can you provide a screenshot or so? Would be really helpful and also can you please write that again ?
