### ISSUE TITLE
Alternat Default Sort Setting on datatable-keytable

### ISSUE THREAD

**Issue by BFronz** [puikinsh/gentelella#604]
For  datatable-keytable how can you set the default sort to sort another column besides the first column and make it descending? So in this example sort would be on age so Garrett Winters would be in the first row.

 <table id="datatable-keytable" class="table table-striped table-bordered">
                            <thead>
                              <tr>
                                <th>Name</th>
                                <th>Position</th>
                                <th>Office</th>
                                <th>Age</th>
                                <th>Start date</th>
                                <th>Salary</th>
                              </tr>
                            <tbody>
                              <tr>
                                <td>Tiger Nixon</td>
                                <td>System Architect</td>
                                <td>Edinburgh</td>
                                <td>61</td>
                                <td>2011/04/25</td>
                                <td>$320,800</td>
                              </tr>
                              <tr>
                                <td>Garrett Winters</td>
                                <td>Accountant</td>
                                <td>Tokyo</td>
                                <td>63</td>
                                <td>2011/07/25</td>
                                <td>$170,750</td>
                              </tr>
  </tbody>
                          </table>

**Comment by William-H-M** [comment]
For that you most set up your options using [`order`](https://datatables.net/reference/option/order)  when initing DataTables like 

```
let direction = 'desc';
let index = 3;
$(element).DataTable({ 
  order: [
    [index, direction]
  ]
})
```
Where `index` is the position of your row in this case is 3 and `direction` is the ordering `asc` or `desc`

**Comment by eptastro** [comment]
where do I put that script? I also wish to sort the table by date which has got this format %d/%m/%Y. In datatables you've got this "sType": "date-uk". How can I implement it in this case?

**Comment by William-H-M** [comment]
Hi, you have to do that when you init your datatables inside a `<script></script>` tag there's basically no difference on how you're initializing any script.

> I also wish to sort the table by date which has got this format %d/%m/%Y. In datatables you've got this "sType": "date-uk". How can I implement it in this case?

For that you're gonna need some little quirk as [JavaScript and Dates are quite a hell](http://blog.dygraphs.com/2012/03/javascript-and-dates-what-mess.html) and for that we're gonna use [`column.type`](https://datatables.net/reference/option/columns.type) and as DataTable official doc said:

> Date / time values. Note that DataTables' built in date parsing uses Javascript's Date.parse() method which supports only a very limited subset of dates. Additional date format support can be added through the use of plug-ins. 

So we need to implement that plugin for sort Uk dates:

We need to extent the function of DataTable that does the sorting with this code:

## **Credits to [Bhushan Kawadkar](https://stackoverflow.com/users/649504/bhushan-kawadkar) who made the extension on this [SO Answer](https://stackoverflow.com/a/26013942/8538799)**

```
  $.extend($.fn.dataTableExt.oSort, {
    "date-uk-pre": function(a) {
      var ukDatea = a.split('/');
      return (ukDatea[2] + ukDatea[1] + ukDatea[0]) * 1;
    },

    "date-uk-asc": function(a, b) {
      return ((a < b) ? -1 : ((a > b) ? 1 : 0));
    },

    "date-uk-desc": function(a, b) {
      return ((a < b) ? 1 : ((a > b) ? -1 : 0));
    }
  });
```
Do you know what going up there? Do you understand? No? Ok. Keep going and don't touch it!

Then we Init our DataTable:

```
  $('#example').DataTable({
    order: [     
        [4, 'desc'] //The position of your column and the order  
    ],
    columnDefs: [{
      "type": "date-uk", //The sorting for Uk dates
      "targets": 4 //Again the position of your column which has dates
    }],
  });
```
**NOTE:** You can basically sort for just one column on the initial run choose which one do you prefer either at start with Age column or Date column index 3 and 4 respectively.

**NOTE 2:** The extions script you should make it globally on a different file that you include always that need DataTable that way avoid copying again and again the same.

> Where can/should I put it?

That's something you and your developer team should have to deal with.

**Comment by eptastro** [comment]
Hi, thanks for your reply, I've worked with datatables before and I always put the script before the </body> tag. I've tried to do the same in this case but it doesn't seem to work.

 

                    <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                      <thead>

                        <tr>

                          <th>Ημ/νία Έναρξης</th>

                          <th>Ημ/νία Λήξης</th>

                                                 <th>Τμήμα</th>

                          <th>Διοργάνωση</th>                                                                                         

                          <th>Κολυμβητήριο</th>   

                          <th><i class="fa fa-wrench"></i></th>                                                                                         

                        </tr>

                      </thead>

                      <tbody>

<?                                           

$dateTime = date_create('now', timezone_open('Europe/Athens'));

$currdate = date_format($dateTime, 'd/m/Y'); 

                

$result = mysql_query("SELECT t.id,DATE_FORMAT(t.tournament_from_date,'%d/%m/%Y'),if(CURDATE() > t.tournament_from_date,1,0),DATE_FORMAT(t.tournament_to_date,'%d/%m/%Y'),t.event,p.pool_name,t.level FROM tournaments AS t LEFT JOIN pools AS p ON p.id=t.pool ") or die(mysql_error());                                                                                                                                

// loop through results of database query, displaying them in the table

$i=1;      

while(list($id,$tournament_from_date,$date_checker,$tournament_to_date,$event,$pool_name,$level) = mysql_fetch_row($result)) {

if ($date_checker == 1) $textcolor='#e5e5e5'; else $textcolor='';                               

if ($level==1) $leveldisp = "ΠΡΟΑΓΩΝΙΣΤΙΚΟ 9-10-11-12";

                                                      echo "<tr>

                          <td style='background-color:$textcolor'>$tournament_from_date</td>

                          <td>$tournament_to_date</td>

                                                                                                  <td>$leveldisp</td>

                                                                                                  <td>$event</td>

                                                                                                  <td>$pool_name</td>

                          <td><a href='edit-tournament.php?tid=$id' role='button' title='Διόρθωση'><i class='fa fa-pencil-square-o'></i></a> <a href='#'><i class='fa fa-trash-o'></i></a></td>

                        </tr>\n";     

$i++;                                                      

}              

echo "\n";

?>           

                      </div>

                    </div>

                  </div>

                  

                      </tbody>

                    </table>

                  </div>

                </div>

              </div>

            </div>

          </div>

        </div>

        

 

        

        <?php include("includes/footer.html"); ?>

                                

      </div>

    </div>

                

    

    <script src="../vendors/jquery/dist/jquery.min.js"></script>

    

    <script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>

    

    <script src="../vendors/fastclick/lib/fastclick.js"></script>

    

    <script src="../vendors/datatables.net/js/jquery.dataTables.min.js"></script>

    <script src="../vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <script src="../vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>

    <script src="../vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>

    <script src="../vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>

    <script src="../vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>

    <script src="../vendors/datatables.net-buttons/js/buttons.print.min.js"></script>

    <script src="../vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>

    <script src="../vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>

    <script src="../vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>

    <script src="../vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>

    <script src="../vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>

    <script src="../vendors/jszip/dist/jszip.min.js"></script>

    <script src="../vendors/pdfmake/build/pdfmake.min.js"></script>

    <script src="../vendors/pdfmake/build/vfs_fonts.js"></script>

 

    

    <script src="../build/js/custom.min.js"></script>         

                

                <script type="text/javascript" charset="utf-8">                

    $.extend($.fn.dataTableExt.oSort, {

    "date-uk-pre": function(a) {

      var ukDatea = a.split('/');

      return (ukDatea[2] + ukDatea[1] + ukDatea[0]) * 1;

    },

 

    "date-uk-asc": function(a, b) {

      return ((a < b) ? -1 : ((a > b) ? 1 : 0));

    },

 

    "date-uk-desc": function(a, b) {

      return ((a < b) ? 1 : ((a > b) ? -1 : 0));

    }

    });

                </script>              

                

    

    <script type="text/javascript" charset="utf-8">

      $(document).ready(function() {

      $('#datatable-responsive').dataTable( {

        order: [     

          [1, 'desc'] //The position of your column and the order  

        ],

        columnDefs: [{

          "type": "date-uk", //The sorting for Uk dates

          "targets": 1 //Again the position of your column which has dates

        }],

      });

    </script>

    

 

You can see the table if  you click on: http://olympias-kolymvisi.eptastro.gr/production/tournaments.php

As you can see it doesn't sort the table correctly even when you press the asc/desc buttons

 

Any help would be appreciated.

Thanks

**Comment by William-H-M** [comment]
Hi, you have a console error you're not closing `$(document).ready(function() {` and try to merge the scripts I gave in one using `$(document).ready`

Error in line 390

@AndreiCN do you mind editing his response as is hard to read to other people or could you give me temporal access to edit it? Thanks

**Comment by eptastro** [comment]
Hi, I’ve edited it, but now I get an error:

 

DataTables warning: table id=datatable-responsive - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

 

and it still doesn’t sort the table. Any more  ideas?

**Comment by eptastro** [comment]
Hi again,

 

I fixed it like this:

 

      $('#datatable-responsive').dataTable( {

                                    "destroy": true,

                                    "aaSorting": [[ 0, 'desc' ]],

            "aoColumns": [

                { "sType": "date-uk" },

                                                                { "sType": "date-uk" },

                null,

                                                                null,

                                                                null,                                                       

                                                                null

            ], 

            "oLanguage": {

                                                                                                "sUrl": "media/he_HE.txt"                                           

                                    }

 

Now it works. Thanks for your help.

**Comment by AndreiCN** [comment]
He sended as a mail and unfortunately that doesn't support Markdown, we will also close this for now, thank you @William-H-M for your contribution !
