### ISSUE TITLE
How's the js file in the build directory built??

### ISSUE THREAD

**Issue by Ygilany** [puikinsh/gentelella#606]
I ran `gulp js` and generated the file `js` code that's supposedly the same as the one in the build directory. 

But Something is off. it seems that's theres so much more code in the `build/js/custom.js` then the actual code that's in `src/js/custom.js` and `src/js/helpers/smartresize.js` combined

can someone guide me on where to find the rest of the code?

**Comment by Miosss** [comment]
I confirm that - manually building scripts (mainly JS) gives much different result:
1. In the original (repo) build/ there are console.logs in the code...
2. Originial build/ has much flot (apparently) related code etc. - custom.js in the repo has 123 kB, while built custom.js is only 8kB...

There are also differences in building css:
1. Bracings are different - that is not a big problem, but differes from what is in the repository's build/ folder
2. There are parts of datepicket / Dropzone.js related code that differs between building manually and using original build/

I would assume, that build/ containts just files generated by gulp after each change / PR but it's not... Which makes my confused about what is THE code to use.

**Comment by funilrys** [comment]
Hello,
I think this one is related to what I said there https://github.com/puikinsh/gentelella/issues/406#issuecomment-360045680 ... 

Indeed, you're right the rest of the code is into `build/js/custom.js` ...

Anyway if you need a working `gulp js` or `gulp watch` you can work from my fork ... https://github.com/funilrys/gentelella
