### ISSUE TITLE
Module build failed: Unrecognised input when requiring css in Angular JS

### ISSUE THREAD

**Issue by okolafa** [puikinsh/gentelella#608]
After update from `1.3.0` to `1.4.0`, I am trying to require css from `gentelella/build/css/custom.css` in the Angular JS app and getting the following error:

```
Module build failed: Unrecognised input
...
near lines:
       background: linear-gradient(top, #f7f9fa 0%, #f0f0f0 100%);
       filter: progid: DXImageTransform.Microsoft.gradient( startColorstr='#f7f9fa', endColorstr='#f0f0f0', GradientType=0);
       -ms-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1) inset;
...
```

The solution is to quote the value in css as following:
```
filter: "progid: DXImageTransform.Microsoft.gradient( startColorstr='#f7f9fa', endColorstr='#f0f0f0', GradientType=0)";
```

Similar issue is discussed here: https://github.com/sass/sass/issues/467

I have no problem to create a Pull request with changes if you think this is a good solution.

**Comment by funilrys** [comment]
let's PR :+1:

**Comment by okolafa** [comment]
Created the PR: https://github.com/puikinsh/gentelella/pull/609

**Comment by AndreiCN** [comment]
Thank you @okolafa for your contribution ! 👍

**Comment by AndreiCN** [comment]
PR merged.
