### ISSUE TITLE
tables_dynamic.html : Responsive not working from asp:GridView 

### ISSUE THREAD

**Issue by salman1zubair** [puikinsh/gentelella#611]
tables_dynamic.html : Responsive not working from asp:GridView  i change the id from custom.js
 custom.min.js

` <asp:GridView ID="GrdLists" class="table table-striped table-bordered dt-responsive nowrap" runat="server" CellSpacing="0" Width="100%"> `
```

$('#GrdList').DataTable();

				$('#datatable-scroller').DataTable({
				  ajax: "js/datatables/json/scroller-demo.json",
				  deferRender: true,
				  scrollY: 380,
				  scrollCollapse: true,
				  scroller: true
				});
```

**Comment by William-H-M** [comment]
Hi, exactly what is not workin? Any error on your console? How does it appear the HTML structure of the table after have rendered on the browser? Sorry but we need more details than:

>Responsive not working from asp:GridView i change the id from custom.js
custom.min.js
