### ISSUE TITLE
setting the menu to the right side ??

### ISSUE THREAD

**Issue by LahmerIlyas** [puikinsh/gentelella#612]
Hi, I'm trying to use this template in my project (uses Arabic language), which requires for the side menu to be on the right side. Is there any way I can customize the template to do so??

**Comment by William-H-M** [comment]
Hi, if not wrong @mortezakarimi made one and was added to the milestone of the next release, 1.5.0, yoy chanc check it out at https://github.com/puikinsh/gentelella/issues/467#issuecomment-300170813

**Comment by AndreiCN** [comment]
We are working on a RTL version @LahmerIlyas , we will release it with 1.5.0 version, we will also close this ticket for now, thank you !
