### ISSUE TITLE
Vendor files shouldn't be versioned

### ISSUE THREAD

**Issue by Dylan-DPC** [puikinsh/gentelella#614]
Hey

Vendor files shouldn't be versioned (pushed on GIT). Instead they should be listed as dependencies in the `package.json` file. The user is expected to install the dependencies locally by running `npm install` or `yarn`. 
If you update the version of any dependency it can cause unnecessary merge conflicts for your users.

Thanks

**Comment by AndreiCN** [comment]
Thank you @Dylan-DPC for the suggestion , we will take this into consideration.

**Comment by Dylan-DPC** [comment]
Hope this is taken into consideration. Closing this issue. 😄
