### ISSUE TITLE
the drop down list not working in the template for mvc spring

### ISSUE THREAD

**Issue by ayasady** [puikinsh/gentelella#617]
hello , first thanks for your template it great , I have some problem in template when i run it in mvc spring , the drop down list not work , i run the page index.html in production folder evrey think work fine excepted the drop down list , for example when i click on the drop own list nothing happen no drop down list appaer , i add all css and js whice include in index.html but still when i click on the drop own list nothing happen
this is the code that i talke about it 

```
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
--
  | <div class="menu_section">
  | <h3>General</h3>
  | <ul class="nav side-menu">
  | <li><a>Home
  | <ul >
  | <li><a href="index.html">Dashboard</a></li>
  | <li><a href="index2.html">Dashboard2</a></li>
  | <li><a href="index3.html">Dashboard3</a></li>
  | </ul>
  | </li>
```

 can help what the wrong ?

**Comment by ayasady** [comment]
@AndreiCN  can help ?

**Comment by AndreiCN** [comment]
Your problem seems to be from JS , do you have any errors or so ?

**Comment by ayasady** [comment]
ok thanks I solves it , the problem was in JS I edit it and it work fine

**Comment by e2lira** [comment]
Can you tell me please, How solved the issue?
