### ISSUE TITLE
Release tag?

### ISSUE THREAD

**Issue by anand-singh** [puikinsh/gentelella#62]
@puikinsh: could you please make a release tag. So, I can request to add it in [WebJars](https://github.com/webjars) 

Thanks,
Anand

**Comment by puikinsh** [comment]
@anand-singh 

Thank you for pointing that out. I have now added release tag and for more info you can head to https://github.com/puikinsh/gentelella/releases

**Comment by anand-singh** [comment]
Here is the new WebJar: https://github.com/webjars/gentelella

This will be released shortly.

Thanks,
Anand

**Comment by puikinsh** [comment]
Awesome! Thank you!
