### ISSUE TITLE
jQuery error url.indexOf

### ISSUE THREAD

**Issue by spongeb00b** [puikinsh/gentelella#621]
I got this error from my browser console, googling around the problem is at the end of the src/js/custom.js on this line of code (cloning the branch having tag 1.4.0):

`$(window).load(function () {
        NProgress.done();
});`

whereas in the master branch the listener to the load event is declared using on() function.

`$(window).on('load', function() {
        NProgress.done();
    });`

However in the build/js/custom.js and custom.min.js the .load() method is used instead of .on('load', function(){})
and I got the error as well on the console

**Comment by selimgnaoui** [comment]
which JQuery version are u using ?

**Comment by spongeb00b** [comment]
v3.2.1

**Comment by AndreiCN** [comment]
That issue comes with higher than version 3 of jQuery. A Boostrap 4 version and also a latest version of jQuery are in development.
