### ISSUE TITLE
Click menu when use smartphone dont show menu

### ISSUE THREAD

**Issue by kunbero** [puikinsh/gentelella#63]
I have problem when i use this template in smartphone. When i click using mouse in computer i don't have problem, but when i click use smartphone with my finger, submenu i show but close again. 
Can you help me??

**Comment by tina562099** [comment]
I have the same problem, but I use the phone to enter the template [Demo](https://colorlib.com/polygon/gentelella/index.html), it would not have this problem, it makes me confused, someone can help? Thanks!

**Comment by christianesperar** [comment]
This pr https://github.com/puikinsh/gentelella/pull/66 will fix this bug

**Comment by puikinsh** [comment]
Fixed on https://github.com/puikinsh/gentelella/pull/66 thankt sto @christianesperar
