### ISSUE TITLE
unable to implement Individual column searching (select inputs) in my table

### ISSUE THREAD

**Issue by nadeem14375** [puikinsh/gentelella#630]
hi all,

I am trying to implement "Individual column searching (select inputs)" [https://datatables.net/examples/api/multi_filter_select.html](url) but unable to do. 

The `<tfoot>` don't work / make as select list.

Can anyone help me. my php file is attached, I am using codeigniter.

[students_list.zip](https://github.com/puikinsh/gentelella/files/1554158/students_list.zip)

**Comment by William-H-M** [comment]
Hi, Sorry but this is not the place to ask meybe at https://stackoverflow.com/ as this is not related to the template itself.
