### ISSUE TITLE
How can I disable side bar accordion

### ISSUE THREAD

**Issue by msarfernandez** [puikinsh/gentelella#631]
I have an mvc .net site with gentelella theme but each time user clics an option menu, all side bar is reloaded and the accordion close and open at reloading. I'd like to disable that so the reloading may be becomes more transparent.
Thanks.

**Comment by William-H-M** [comment]
Hi, so what you want is that after reload the current link never opne up on the menu if yes remove this:
https://github.com/puikinsh/gentelella/blob/bca6c620c62f616c3323cbf0bb4a0699cb3de2d4/src/js/custom.js#L7-L15

https://github.com/puikinsh/gentelella/blob/bca6c620c62f616c3323cbf0bb4a0699cb3de2d4/src/js/custom.js#L76

https://github.com/puikinsh/gentelella/blob/bca6c620c62f616c3323cbf0bb4a0699cb3de2d4/src/js/custom.js#L78-L82

If not then give us an example

**Comment by msarfernandez** [comment]
mmm no, with that idea I lose access to child menu items. I atach a gift with the "problem". Wich I need is to disable the accordion animation to prevent that effect;
Thanks for answer!

![accordionanimate](https://user-images.githubusercontent.com/7469760/34044128-9412706e-e182-11e7-9859-b942de44f079.gif)

**Comment by William-H-M** [comment]
Well I got it if you don't want the animation then just set `.slideDown(0, function()` It'll be fast enough for you to don't notice on most of the cases.

Note: on the last comment I cited the src/js as this is used for the git but in production the one used is build/js:

https://github.com/puikinsh/gentelella/blob/bca6c620c62f616c3323cbf0bb4a0699cb3de2d4/src/js/custom.js#L80

so change this line and the make it min (Not sure what IDE you use but VisualStudio make this is easy for me...)
https://github.com/puikinsh/gentelella/blob/bca6c620c62f616c3323cbf0bb4a0699cb3de2d4/build/js/custom.js#L126

**Comment by msarfernandez** [comment]
Good, that was helpfull, I don't have the animation anymore and it work better. Just a little more request, I don't  know if its possible. When page is reloading, menu is closed and opened. When there are just a few registers, its very fast, but when the query is a little longer, menu is closed until the loading ends and finally is opened again. 
Can we make menu still opened? The reloading will still exist, but it going to be less visual. I am right?

Yes, I am using Visual Studio.

Thanks a lot!

![closedopenedmenu](https://user-images.githubusercontent.com/7469760/34049306-b75c9758-e195-11e7-86ea-900c3fe740c5.gif)
