### ISSUE TITLE
Enable Dropdown on hover instead of click

### ISSUE THREAD

**Issue by vj-rana** [puikinsh/gentelella#634]
Hello, I know its a minor but I couldn't find the solution. I want the left sidebar menu options drop on hover instead of click. How to achieve this? It would be really great. Thanks

**Comment by rinkp** [comment]
Please look at [custom.js](../blob/master/src/js/custom.js). I think the `init_sidebar`-function is what you are looking for. 
You might be able to change 
Line 72: `$SIDEBAR_MENU.find('a').on('click', function(ev) {`
into `$SIDEBAR_MENU.find('a').on('hover', function(ev) {` but I haven't tested this change myself, so I'm not sure whether there will be issues.

**Comment by vijayrana-me** [comment]
Thank you for your reply. I tested it after changing, but its not working.

**Comment by AndreiCN** [comment]
Have you find a solution for this one @vijayrana-me ?

**Comment by vijayrana-me** [comment]
@AndreiCN No, I am unable to make any changes. Please ping me if you got any idea :)

**Comment by difara** [comment]
sorry if I revive an old thread but instead of using
`$SIDEBAR_MENU.find('a').on('hover', function(ev) {`

you could use this instead:
`$SIDEBAR_MENU.find('a').on('mosueover', function(ev) {`

**Comment by AndreiCN** [comment]
No worries @difara , actually thank you for your contribution :)

@vj-rana you can try this as a solution, good luck !

**Comment by difara** [comment]
if above solution is buggy you could just copy your code and makes it redundant (yeah.... redundant.......)
`$SIDEBAR_MENU.find('a').on('mouseenter', function(ev) { <function_here>`
`$SIDEBAR_MENU.find('a').on('mouseleave', function(ev) { <function_here>`

**Comment by vj-rana** [comment]
thanks, it worked @difara
