### ISSUE TITLE
Left nav broken in Safari browser

### ISSUE THREAD

**Issue by dickyj** [puikinsh/gentelella#638]
Hi,
I tried using the demo website in the Mac Safari browser, but seems like the left nav is not working.
https://colorlib.com/polygon/gentelella/index.html

I am using Safari 11.0.2 on the Mac Sierra OS.

![screen shot 2018-01-04 at 9 22 29 am](https://user-images.githubusercontent.com/6478334/34547879-dd633df8-f130-11e7-8e8f-e0a2b0dfe42a.png)

**Comment by AndreiCN** [comment]
Are you sure that's not from your side ? I'm asking because I've tested it and it's working just fine.
