### ISSUE TITLE
dynamic tables with Ajax 

### ISSUE THREAD

**Issue by recepysl** [puikinsh/gentelella#641]
Hi, 
Im using the dynamic tables. Data operations are dynamic (No postback or reload page ). So ın this case my table data comes with ajax.  Each time ın query i fill my data to table but the problem is, table feautures doesnt work(paging,search etc.). Here is my sample ajax code
`
$('#datatable').empty();
            $('#datatable').append(result);        
            $('#datatable').DataTable();
`
Thanks

**Comment by recepysl** [comment]
any help would be great

**Comment by William-H-M** [comment]
Hi, you're doing wrong this.

You're basically applying datatables twice (or more if you call it again), what you must do is call it once and then reload datatables with the data using the method [`.reload()` ](https://datatables.net/reference/api/ajax.reload())

Basically what you do is something like:
```

var table = $('#example').DataTable({
  ajax: {
    url: "controller/GetData",
    type: "POST"
  },
  columns: [
            { "data": "name" },
            { "data": "position" },
            { "data": "office" },
            { "data": "extn" },
            { "data": "start_date" },
            { "data": "salary" }
        ]
});
 
setInterval(function () {
    table.ajax.reload();
}, 30000 );
```

Reference:
https://datatables.net/reference/option/ajax
https://datatables.net/examples/ajax/objects.html

**Comment by AndreiCN** [comment]
@recepysl please close the ticket if you solved this one.

**Comment by recepysl** [comment]
Thanks a lot. Problem fixed.
