### ISSUE TITLE
Can´t change Calendar Language 

### ISSUE THREAD

**Issue by pedrotavares** [puikinsh/gentelella#642]
I have follow the documentation for the fullcalendar changing language, but with no sucess at all.
The calendar allways shows in the default language.
what i have done was this:
`<script src="vendors/fullcalendar/dist/fullcalendar.min.js"></script>
    <script src="vendors/fullcalendar/dist/lang/pt.js"></script>

   <script>

    $(document).ready(function() {

        $('#calendar').fullCalendar({
        });

    });

</script>`

**Comment by AndreiCN** [comment]
Did you check the console ? Do you have errors or something ?

**Comment by AndreiCN** [comment]
Ok, I will try to reproduce that and get back to you.

**Comment by pedrotavares** [comment]
What's strange is that in the examples of the Fullcalendar,  I can change the language using this method.

**Comment by krzysiekpiasecki** [comment]
@pedrotavares Do you really have no errors like:`'TypeError: undefined is not a function (near '...a.fullCalendar.datepickerLang...')' ?` when you add a lang script?

Do you update a vendor libraries?

**Comment by krzysiekpiasecki** [comment]
After clean install of the repository and then `bower update full-calendar` everything works fine. So if you consider that this answer resolved your problem plese close this ticket :)
