### ISSUE TITLE
Problem with Panel toolbox responsive

### ISSUE THREAD

**Issue by marcelogarbin** [puikinsh/gentelella#643]
Problem with the dropdown button when triggered in responsive mode. It breaks the layout.
![gentelella](https://user-images.githubusercontent.com/9335588/35012451-f1b5f3d0-faf0-11e7-88f0-e45f70f074ca.gif)

**Comment by AndreiCN** [comment]
Thank you @marcelogarbin  for pointing this out, we will take care of it.

**Comment by funilrys** [comment]
@AndreiCN Where is the commit which fixes this?

**Comment by AndreiCN** [comment]
Will be available in a few.
