### ISSUE TITLE
colspan on a table

### ISSUE THREAD

**Issue by beetlikeyg087** [puikinsh/gentelella#644]
I have a table that has 7 columns.
The table displays very good so far until I use attribute colspan="4" on the last row. 
Then the show property, search box and button links previous and next are gone.

Please help.

**Comment by AndreiCN** [comment]
Can you provide a screenshot ?

**Comment by beetlikeyg087** [comment]
![screenshot from 2018-01-22 14-44-06](https://user-images.githubusercontent.com/26866007/35580482-beb49438-061b-11e8-989b-cd5f0380b704.png)

This is the output when I use colspan on the last row

**Comment by AndreiCN** [comment]
Ok but I'm not quite sure what you want to achieve there. Can you share another one showing how should look or something ?

**Comment by William-H-M** [comment]
That and maybe some code....

**Comment by AndreiCN** [comment]
@beetlikeyg087 please provide some more details , some code maybe or if you solved this on your own please close the ticket.

**Comment by beetlikeyg087** [comment]
Thank you for your help, I just lack understanding plugin

I did not know that it is DataTable plugin then.

So, now it is working fine.
