### ISSUE TITLE
font-awesome not displayed with Firefox 58.0.1 (32bits)

### ISSUE THREAD

**Issue by bleu13** [puikinsh/gentelella#648]
Hello
In the context a school project I'am testing the template on multiple browsers and when using Firefox, font-awesome objects are only displayed as unicode.
I saw on Mozzila support some tips, but all are already in place without success.
Does any of you have any idea how to solve this problem?

**Comment by gokhanucar** [comment]
Try CDN (content delivery network) for font-awesome objects

Gökhan

1 Şub 2018 14:31 tarihinde "bleu13" <notifications@github.com> yazdı:

**Comment by bleu13** [comment]
thank @gokhanucar using CDN works, I as I has the same issue with glyphicons I found an other alternative under https://stackoverflow.com/questions/19085942/boootstrap-glyphicons-firefox-issues

**Comment by funilrys** [comment]
@bleu13 Do you see them as Unicode chars too when navigating to http://gentelella.ilrysfun.com/ 🤔

**Comment by bleu13** [comment]
No visual issue on  http://gentelella.ilrysfun.com/  with firefox (with or
without the browser patch)


2018-02-01 19:29 GMT+01:00 Nissar Chababy <notifications@github.com>:

**Comment by funilrys** [comment]
Well the source code can be found here https://github.com/funilrys/gentelella ... Maybe you can find where the issue is then ... I did a lot of work on my fork but I never touched the HTML (for now) 🤔
