### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by wilcorrea** [puikinsh/gentelella#65]
Thank you guys, how donate?

**Comment by puikinsh** [comment]
@wilcorrea 

Actually the best way to contribute to this project is to report some bugs or better yet fix something on your own and create pull request. That would be a huge deal for this project and we are interested in supporting it into a long run. 

If you think that the best way you can give back is by donating you can do that by by sending donation via PayPal to a.silkalns[at]gmail.com (replace at with @). 

Thank you!

**Comment by JamesAusten** [comment]
I found this theme today and its perfect for my needs. I'll be sure to link back and contribute! :+1:
