### ISSUE TITLE
Echart Bar - Label Text is out of boundary when long string passes

### ISSUE THREAD

**Issue by cr2chenl** [puikinsh/gentelella#650]
Hi,
    Plz find the attachment screenshot.
![image](https://user-images.githubusercontent.com/20284076/36037866-e852bbf2-0db5-11e8-8a8d-ceff9a026850.png)

It will auto wrap if the text is too long ? 
Does it related to something config under Chart.js ? Im a beginner on Web development.
How i can enable all category text for this bar chart and turn on auto wrap somewhere will help ? 

Thanks in advance ...

Code Im working on ...
 var echartBar = echarts.init(document.getElementById('mainb2'), theme);

                echartBar.setOption({
                    title: {
                        text: 'Auto Results Based on Builds',
                        subtext: 'IB Channel'
                    },
                    tooltip: {
                        trigger: 'axis'
                    },
                    legend: {
                        data: ['Pass', 'Fail', 'Skip']
                    },
                    toolbox: {
                        show: false
                    },
                    calculable: false,
                    xAxis: [{
                        type: 'category',
                        data: buildNameList
                    }],
                    yAxis: [{
                        type: 'value'
                    }],
                    series: [{
                        name: 'Pass',
                        type: 'bar',
                        data: passRateList,
                        markPoint: {
                            data: [{
                                type: 'max',
                                name: ''
                            }, {
                                type: 'min',
                                name: ''
                            }]
                        },
                       /* markLine: {
                            data: [{
                                type: 'average',
                                name: '???'
                            }]
                        }*/
                    }, {
                        name: 'Fail',
                        type: 'bar',
                        data: failRateList,
                        markPoint: {
                            data: [{
                                type: 'max',
                                name: ''
                            }, {
                                type: 'min',
                                name: ''
                            }]
                        },
                      /*  markLine: {
                            data: [{
                                type: 'average',
                                name: '???'
                            }]
                        }*/
                    }, {
                        name: 'Skip',
                        type: 'bar',
                        data: skipRateList,
                        markPoint: {
                            data: [{
                                type: 'max',
                                name: ''
                            }, {
                                type: 'min',
                                name: '???'
                            }]
                        },
                       /* markLine: {
                            data: [{
                                type: 'average',
                                name: '???'
                            }]
                        }*/
                    }]
                });

**Comment by cr2chenl** [comment]
is someone can help this. Or suggest somewhere i can enable auto wrap which enable should all long string under all bar ... thanks.

**Comment by luisriego** [comment]
Have You found a solution?

**Comment by cr2chenl** [comment]
nope .. im trying to edit js files and css .. no luck ... still need the help for this ..

**Comment by cr2chenl** [comment]
solve this issue.. there are two ways to implement .... rotate to 45 and change grid bottom value.. or use js under formatter to split label text by what you required .. normally will be 7 character per line will be ok ..

**Comment by xianghongai** [comment]
![how-to-align-left-of-yaxis-that-name](https://user-images.githubusercontent.com/2075006/52611399-61bebf00-2ec0-11e9-92a6-e3db66987b01.png)

The axis name align way base on x/y axis line ?
