### ISSUE TITLE
Could not find an option named "sourcemap".

### ISSUE THREAD

**Issue by klein0r** [puikinsh/gentelella#654]
When starting "gulp sass" or "gulp sass-minify" I get the following error. Which sass Version do I have to use to build those files correctly? Why is sass not installed with package.json?

```
npm install -g sass
/usr/local/bin/sass -> /usr/local/lib/node_modules/sass/sass.js
/usr/local/lib
└── sass@1.0.0-beta.5.2 
```

```
[21:00:51] Using gulpfile ~/Dev/gentelella/gulpfile.js
[21:00:51] Starting 'sass'...
[21:00:51] Could not find an option named "sourcemap".
[21:00:51] Usage: dart-sass <input>

    --[no-]stdin    Read the stylesheet from stdin.
-s, --style         Output style.
                    [expanded (default), compressed]

-c, --[no-]color    Whether to emit terminal colors.
    --[no-]trace    Print full Dart stack traces for exceptions.
-h, --help          Print this usage information.
    --version       Print the version of Dart Sass.
[21:00:51] Finished 'sass' after 424 ms
```

**Comment by funilrys** [comment]
Strange I did not get such things @klein0r :thinking:  Can you test if it happens with [my fork](https://github.com/funilrys/gentelella) ?

**Comment by funilrys** [comment]
Okay, I understand why it's happening ... I installed sass with `gem` globally ...

**Comment by funilrys** [comment]
```
# sass -v
Sass 3.5.5 (Bleeding Edge)
```

**Comment by klein0r** [comment]
Thanks a lot :) Should be added to documentation to do that 👍 

```
[21:18:42] Using gulpfile ~/Dev/gentelella/gulpfile.js
[21:18:42] Starting 'sass'...
[21:18:42] directory ./
[21:18:43] write ./app.css
[21:18:43] Finished 'sass' after 1.7 s
```

**Comment by ahmedfarag2010** [comment]
Hello there ..
I have the same error for two weeks almost i'm trying to fix this error
I tried the same steps but can't be resolved 

![1](https://user-images.githubusercontent.com/17453891/40534912-5acdb90e-5fbc-11e8-843d-7d92586f7764.png)

**Comment by funilrys** [comment]
May I ask how did you installed sass ?

**Comment by harsh-sri** [comment]
Hi,

I am getting the same issue, details are given below:

sass version: 1.5.1 compiled with dart2js 2.0.0-dev.59.0

could you please help me?

Thanks

**Comment by giancarlocunis** [comment]
Hi,

Had the same issue. I had installed npm sass globally for another project.
npm uninstall -g sass
Everything was working again as mention above.

Thanks.

**Comment by LzhBruce** [comment]
I find simple step:
    1.Run npm install gem command.
    2.Run gem install sass command.
ok.

**Comment by Js4Life** [comment]
" **gem install sass** "  fixes all issue!
