### ISSUE TITLE
Responsive not working with DataTable server side 

### ISSUE THREAD

**Issue by beetlikeyg087** [puikinsh/gentelella#656]
I spent hours to fix this by searching lots of sites but it seems not working for me.
I have a table that load data with DataTable (serverSide) and everything works fine.
Except that the table is not responsive when I press maximize tab.

These pictures are described as the issue.

![screenshot from 2018-02-22 11-00-23](https://user-images.githubusercontent.com/26866007/36520200-3adb59c2-17c2-11e8-90c2-33f0062c91ce.png)

![screenshot from 2018-02-22 11-00-30](https://user-images.githubusercontent.com/26866007/36520208-4db926dc-17c2-11e8-9003-9e2775503169.png)
                                       _Notice: there is a space on the right side._

If anyone can help, please.

**Comment by beetlikeyg087** [comment]
This is the code of DataTable part

         `$('#c-table').DataTable({
	                processing : true,
			serverSide : true,
			ajax : "{{ route('dt.ctm.all') }}",
			columns : [
			{ data : 'id', name : 'id'},
			{ data : 'name', name : 'name'},
			{ data : 'alias_name', name : 'alias_name'},
			{ data : 'phone_no', name : 'phone_no'},
			{ data : 'email', name : 'email'},
			{ data : 'address', name : 'address'},
			{ data: 'action', name: 'action', className: 'text-center', searchable: false, orderable : false 
			} ]
		});`

**Comment by masbudikusuma** [comment]
Some people add width="100%" on the table. and I'ts work for me..
