### ISSUE TITLE
Remove the Stray lines 

### ISSUE THREAD

**Issue by Sarnodeep** [puikinsh/gentelella#660]
Please remove this git head from the page 
"https://colorlib.com/polygon/gentelella/form.html"
"<<<<<<< HEAD ======= >>>>>>> refs/remotes/puikinsh/Development"

**Comment by William-H-M** [comment]
Duplicate of #433

**Comment by funilrys** [comment]
As I do not see this on http://gentelella.ilrysfun.com/form.html I suppose that this issue is related to the website not the repo :thinking:

**Comment by Sarnodeep** [comment]
My Bad :( yup this issue was related to the website... thank you for resolving it...
