### ISSUE TITLE
gentelella daterangepicker problem on mobile/responsive pages (custom.css)

### ISSUE THREAD

**Issue by egulhan** [puikinsh/gentelella#663]
Hi.

**daterangepicker** sets "calendar left" classes to the class attribute of left calendar. gentelella sets .left css class in **custom.css** like as following:

```
.left {
    float: left
}
```

This makes daterangepicker plugin unusable on pages. The problem is that any dates can not get picked from left calendar but right calendar works as expected.

I fixed it simply by doing:

```
.calendar.left {
   float: initial !important;
}
```

**Comment by egulhan** [comment]
I reproduced this on the demo page http://gentelella.ilrysfun.com/form_advanced.html. In the ss, the first calendar is unusable. [https://ibb.co/mMj69c](url)

**Comment by funilrys** [comment]
Great feel free to leave a PR there will merge it :+1:

**Comment by egulhan** [comment]
Should I create a branch from master to do my changes for PR?

**Comment by funilrys** [comment]
Yes from master to master. As I said at  https://github.com/puikinsh/gentelella/issues/406#issuecomment-360045680, I'm not going send a PR to here anyway so yes you can safely PR to master on my fork :+1:
