### ISSUE TITLE
How do I change colors?

### ISSUE THREAD

**Issue by martinmurciego** [puikinsh/gentelella#669]
How do I change colors or the theme of this template? Affecting the color of fonts, panels, sidebar and others?

The template elements are organized in some way that are affected by certain colors or styles?

**Comment by AndreiCN** [comment]
It's quite easy to change colors , just find a developer tool ( google extension ) for instance in order to find it in CSS. Will not affect colors/styles. If you have no further questions please close the ticket.

**Comment by arosales2015** [comment]
You can use "class" in your tags, next apply css to the class
