### ISSUE TITLE
Material Design?

### ISSUE THREAD

**Issue by abmmhasan** [puikinsh/gentelella#672]
What about a Material Design Version of this Theme?

**Comment by AndreiCN** [comment]
We don't have a plan to launch a Material Version anytime soon, however we appreciate your feedback, thank you very much ! If you have no further questions , please close the ticket.

**Comment by puikinsh** [comment]
Material design would mean designing and building a completely new template. 
If you aren't aware we have several new admin templates already [built](https://github.com/puikinsh?utf8=%E2%9C%93&tab=repositories&q=admin&type=&language=).
