### ISSUE TITLE
Is this BS theme multi-language ?

### ISSUE THREAD

**Issue by mansartesteban** [puikinsh/gentelella#678]
Hi Guys !

I would like to know how to change the language of this project.
I already changed the "lang" attribute to "fr" in the <html> tag and added a setlocale(LC_ALL, 'fr_FR'); in php to my main page and my browser is in french. But nothing is happening 😢 

I know that the html texts have to be generated by me in french, but i'm asked for the js classes like "datatables" and other ...
If it's not multi-language, is there a lang file somewhere with all texts ?

Thank you by advance guys 😄

**Comment by giansalex** [comment]
have you review the source code?

**Comment by mansartesteban** [comment]
Yes i've reviewed it, but i didn't see where this is. Could you help me more ?
I don't want to be arrogant but i'm a developer so if i ask here, it is because i've already watched ^^

**Comment by giansalex** [comment]
where do it says multilanguage?
I have not seen it anywhere

**Comment by mansartesteban** [comment]
Ok, you definitely don't know how to read ....
1. The title of my topic is "_Is this BS theme multi-language ?_" => You should answer "no" instead of "**have you review the source code?**".
2. I also ask "_If it's not multi-language, is there a lang file somewhere with all texts ?_" as which you should answer "no" ... again instead of being arrogant.
3. In response to you i asked "_Could you help me more ?_" you should help me again by saying "There isn't any multilang support" but you prefer to be unpleasant.
4. **"where do it says multilanguage?
I have not seen it anywhere"** => Maybe that why i asked here ...
Thank you for this nice help ....

**Comment by giansalex** [comment]
I'm in your same place, I don't know this project, but if in any place it says multilanguage why believe that
