### ISSUE TITLE
loosing alignment on <div> expand click

### ISSUE THREAD

**Issue by karthiksd9** [puikinsh/gentelella#681]
I have a page which has  3 `<DIV>` in a row. All the Div's are having collapse link (`collapse-link`) within that DIV.

If i expand first DIV, its height increases, which causes the miss alignment of the subsequent DIV's.

Please refer below images.
https://i.stack.imgur.com/JKfJv.jpg
https://i.stack.imgur.com/xJwuI.jpg

If i expand third collapse link, then its working fine.
https://i.stack.imgur.com/rH8jL.jpg

Stackoverflow Issue: https://stackoverflow.com/questions/49819454/jquery-ui-sortable-loosing-alignment-on-div-expand-click

**Comment by AndreiCN** [comment]
That's how float works. If that's not working for you, of course you can find another way to align the blocks but they are working just fine.
