### ISSUE TITLE
Long menu titles may break markup (chevron hangs or sidebar overlaps the body)

### ISSUE THREAD

**Issue by vvnc** [puikinsh/gentelella#683]
I've noticed that the menu item markup may break in some cases involving long menu titles. I know that the menu titles aren't supposed to be that long but in some cases it may be annoying.

For example, if title consists of several words splitted by a space, everything is ok:

String example: `<a>just a lot of small words with spaces are ok <span class="fa fa-chevron-down"></span></a>`

![image](https://user-images.githubusercontent.com/27448586/38940270-65fb8d52-4332-11e8-8336-fc7edb15170f.png)

But one very long name without spaces breaks it and the chevron hangs ugly in the corner going out outside of the block:

String example: `<a>one_very_long_long_title_is_not_ok <span class="fa fa-chevron-down"></span></a>`

![image](https://user-images.githubusercontent.com/27448586/38940327-85df75e8-4332-11e8-865d-386f0c72fb95.png)

And it reproduces in some cases even if there are some spaces:

String example: `<a>a a a a a a a a a a  abcdefghijkl<span class="fa fa-chevron-down"></span></a>`

![image](https://user-images.githubusercontent.com/27448586/38940348-913a589a-4332-11e8-93ec-2b546f8ec56f.png)

And if the word that is longer than, somewhat like 34 (it's aproximately because it depends on the exact letters because they have different widths) it breaks the entire markup, the sidebar starts to overlap with the body of a template:

![image](https://user-images.githubusercontent.com/27448586/38940448-d3be94ba-4332-11e8-85d3-18653885aaba.png)

String examples:

- no overlap, and chevron is ok: `<a>not_that_long_title_is_ok_11 <span class="fa fa-chevron-down"></span></a>`

- no overlap, but chevron hangs: `<a>one_very_long_long_title_is_not_ok <span class="fa fa-chevron-down"></span></a>`

- sidebar overlaps body: `<a>one_very_long_long_title_is_not_ok1 <span class="fa fa-chevron-down"></span></a>`, `<a>and_if_its_TOO_long_it_actually_breaks_the_entire_markup <span class="fa fa-chevron-down"></span></a>`

I'm using the latest Gentelella version from npm (1.4.0)

**Comment by AndreiCN** [comment]
I think nobody will actually use such a long title but thank you for pointing this out though :)

We will close this one for now.
