### ISSUE TITLE
Bug in the obsoleted gauge.js

### ISSUE THREAD

**Issue by vvnc** [puikinsh/gentelella#684]
The version of gauge.js that is used in Gentelella is broken, but this bug is already fixed in the latest version of gauge.js. The bug happens when the value and the angle of the gauge is set to 0. I've tested in on the index.html page of every version of Gentelella I've found:

- latest from npm (1.4.0);
- branch master;
- branch Update-1.5;
- branch dev;
- branch Development;
- branch Development-Febr.

![image](https://user-images.githubusercontent.com/27448586/39048854-a6c861ea-44a7-11e8-9701-5c0d28895279.png)

The bug it that when value is zero then gauge draws two pointers instead of one.

Here is some JS to quick test it in the dev console:

```
let elem = document.getElementById('chart_gauge_01');
let opts = {angle: 0};
let g = new Gauge(elem).setOptions(opts);
g.set(0);
```

I've solved this to myself by using the latest gauge.js.min script from the [gauge github](http://bernii.github.io/gauge.js/). I suggest putting it to the vendors folder instead of current.

**Comment by AndreiCN** [comment]
Thank you @vvnc for pointing this out, just replaced it in the 1.5 Update branch.
