### ISSUE TITLE
Email Validations are not working

### ISSUE THREAD

**Issue by pdvbalaji** [puikinsh/gentelella#685]
Hello ,

  We are using Gentelella Alela UI for MVC5 but some validations are not working even we taken all css and js also. suppose Email is not working . can you please guide me how to go .
Thanks & Regards
balaji

**Comment by AndreiCN** [comment]
Still have this issue ? If you do , can you please provide some more details about your issue, like screenshots or so? If you don't or you do not have further questions please close the issue, thank you !

**Comment by pdvbalaji** [comment]
Thank you AndreiCN , I change my project to typescript
