### ISSUE TITLE
radio button on general form doesn't work

### ISSUE THREAD

**Issue by lordspace** [puikinsh/gentelella#686]
you can't change the gender on that form there ... it stays on female

**Comment by William-H-M** [comment]
It does change, if you check on the Developer console you can see that the class `active` change between them, the thing is that Female button has `btn-primary` but Male has `btn-default` but It does change

**Comment by lordspace** [comment]
Ok. That's good but it should visually change as well.

**Comment by AndreiCN** [comment]
It is changing , it's subtle indeed ( visually ) but it's changing. If you have no further questions here, please close the ticket , thank you !
