### ISSUE TITLE
Why not use css variables in colors and other style configurations next versions?

### ISSUE THREAD

**Issue by martinmurciego** [puikinsh/gentelella#688]
Especially in colors styles to configure the theme of this admin template? Since it is not necessary to only use preprocessors to include them and be able to customize a theme.
https://www.w3schools.com/css/css3_variables.asp

:root {
  --main-color: #06c;
}
 
#foo h1 {
  color: var(--main-color);
}

**Comment by martinmurciego** [comment]
Using a color extractor I found that these colors are present in custom.css for this admin template:
![screenshot-2018-5-1 css color extractor de gentelella](https://user-images.githubusercontent.com/7759127/39494549-361ad936-4d6d-11e8-8aac-15a7d20ab433.png)

**Comment by AndreiCN** [comment]
We have other things to do first but you are free the make a PR with it of course. We will close this one for now, thank you for the suggestion though.
