### ISSUE TITLE
Can´t select submenu on mobile

### ISSUE THREAD

**Issue by diogomacedo92** [puikinsh/gentelella#69]
Hello :) 
When I open it on mobile device, if i try to open a sub-menu, when I select the first level option it shows me the full list of child menus and then close again. I have no time to select the child that I want...

Can you please help me? 

Thanks in advance!

**Comment by puikinsh** [comment]
Isn't this related to https://github.com/puikinsh/gentelella/issues/63 ?

**Comment by diogomacedo92** [comment]
Dear friend,
Im sorry for that. I searched the old topics but I didnt saw that. It really fixed my issue. Thank you ver much for you help!

**Comment by puikinsh** [comment]
Not a problem since it was fixed only yesterday.
