### ISSUE TITLE
Change to Angular JS 6, but the header function wouldnt work.

### ISSUE THREAD

**Issue by Arios509** [puikinsh/gentelella#692]
Hi there, I have face some issues that I change the theme to the Angular js 6 based, but the javascript doesn't work.

I change the header and the left side bar into app-header.component.html, and it just cant detect my javascript.
`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>MyApp</title>
  <base href="/">
  <style src="../../../styles.css"></style>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <script type="text/javascript" src="assets/vendors/jquery/dist/jquery.min.js"></script>
  <script type="text/javascript" src="assets/vendors/bootstrap/dist/js/bootstrap.min.js"></script>    
  <script type="text/javascript" src="assets/js/custom.min.js"></script>
  
</head>

<body class="nav-md">
 
      <app-root></app-root> 
 
</body>
</html>
`
This is my index.html, and I put my javascript inside this, and this still wont work.
But if I put all my header code into this, then it will work. Is that some part I miss or I need to put into another way?

**Comment by AndreiCN** [comment]
You can take [this](https://github.com/kmkatsma/angular2-webpack-starter-gentelella) as a guidance, good luck !
