### ISSUE TITLE
Cannot read property 'isValid' of undefined

### ISSUE THREAD

**Issue by goodjack** [puikinsh/gentelella#694]
Since there is no `#demo-form` and `#demo-form2` on my pages.

## Screenshot

![image](https://user-images.githubusercontent.com/1116129/40611999-505f02a6-62ab-11e8-9edf-6a9f0e068857.png)

![image](https://user-images.githubusercontent.com/1116129/40611838-934c03bc-62aa-11e8-813c-1c1e2732e38e.png)

## custom.js

https://github.com/puikinsh/gentelella/blob/4dea1e2769ab860e982ca76d26f14169654d1ab7/build/js/custom.js#L986-L994

**Comment by AndreiCN** [comment]
Well, if you have a form, replace #demo-form2 with your form ID, in case you don't need the form validation itself just remove the click event.

**Comment by goodjack** [comment]
@AndreiCN Thanks for your reply.
But I am using the CDN version of gentelella and I can't edit anything.

https://cdnjs.com/libraries/gentelella
