### ISSUE TITLE
Gentelella Multilevel Menu Did Not Work for Mobile View

### ISSUE THREAD

**Issue by manmoncang** [puikinsh/gentelella#701]
How to fix multilevel menu did not work if using small menu. <a href="https://imgbb.com/"><img src="https://image.ibb.co/no6Rjd/GENTELELLA.jpg" alt="GENTELELLA" border="0"></a>

If using normal view.... it's work
<a href="https://imgbb.com/"><img src="https://image.ibb.co/h97XPd/Captures.jpg" alt="Captures" border="0"></a>

**Comment by AndreiCN** [comment]
Check branch Update 1.5 , problem it's solved there.
