### ISSUE TITLE
Removing left panel section

### ISSUE THREAD

**Issue by sonaljeet** [puikinsh/gentelella#704]
Hello,
First of all, thanks a lot for this amazing template.
I am currently re-using this template and need to remove the left panel. I do not need it as per my requirement.
Could you please let me know which 'div' or any other section I need to update to remove the same.
![leftpanel](https://user-images.githubusercontent.com/31158961/41519872-58162d7e-72e8-11e8-89e0-97674adbd8a7.PNG)
Kindly refer the snapshot for more details.

Thanks in advance!
Sonaljeet

**Comment by AndreiCN** [comment]
Hi there, in order to remove the left panel, all you need do is find and remove the "left_col" from your HTML structure.
