### ISSUE TITLE
After Toggle the sidebar menu to smaller, the multilevel menu is not working.

### ISSUE THREAD

**Issue by suhailvs** [puikinsh/gentelella#724]
![gentelella](https://user-images.githubusercontent.com/2777384/43447011-10b0bf38-94c8-11e8-9483-879096230297.jpeg)
On the above picture Level One is a multilevel menu, and when i click it, it is not expanding rather close the menu.

**Comment by William-H-M** [comment]
Duplicate of #490 
Close this, thanks.
