### ISSUE TITLE
Remove overflow: hidden; from .tile so contents don't get cut

### ISSUE THREAD

**Issue by ixperiencenl** [puikinsh/gentelella#726]
When showing dynamic content (like colorpickers or selects), this gets cut off due to the overflow hidden property. Remove this on line 739 in the theme.scss file to get rid of this behaviour.

**Comment by ixperiencenl** [comment]
With overflow hidden: ![image](https://user-images.githubusercontent.com/9009015/43631452-865de728-9703-11e8-9fc6-dc46379d4abe.png)

overflow hidden removed: 
![image](https://user-images.githubusercontent.com/9009015/43631485-9f731440-9703-11e8-9ced-2702838bbe74.png)

**Comment by AndreiCN** [comment]
Well this seems like is not a part of Gentelella so we will close the ticket for now.
