### ISSUE TITLE
How to put multiple tables in one page?

### ISSUE THREAD

**Issue by mavewei** [puikinsh/gentelella#727]
Dear,

The page length and search bar will disappear if I add more than one tables on the same page, example add two "datatable-fixed-header" tables.

Is it possible to do it or it's totally impossible to achieve? Thanks

**Comment by yogmel** [comment]
Hi mavewei,

Is this what you looking for?
![table-fix](https://user-images.githubusercontent.com/3901809/44548504-a7aa7f80-a6f4-11e8-83b5-ce513dadce1d.jpg)

For this to be achieved, you need to add an aditional script:
```javascript
$(document).ready(function() {
    $('.table-fixed').DataTable( {
        fixedHeader: {
            header: true
        }
    });
});
```
I also inserted a class on each table (table-fixed), so they could be selected.

---

The references I used are:
[Bootstrap 4 DataTable](https://datatables.net/examples/styling/bootstrap4)
[FixedHeader example](https://datatables.net/release-datatables/extensions/FixedHeader/examples/options/two_tables.html)

**Comment by mavewei** [comment]
Thanks yogmei, it worked.
Cheers.
