### ISSUE TITLE
css issue & left menus do not open

### ISSUE THREAD

**Issue by Djas2017** [puikinsh/gentelella#738]
I have some css AND menu issues when uploading the project to a web server.

Does someone have similar issues and can help to fix them? 
See attached screenshot.

![gentelella-css-and-menu-issues](https://user-images.githubusercontent.com/25626639/45174640-61b3e800-b1d9-11e8-8f6b-7c50ffdfefc7.png)

 
Thanks

**Comment by yogmel** [comment]
Hi,

Could you please send us a file or URL with this bug? I wasn't able to recreate it here. :/

Thanks!

**Comment by AndreiCN** [comment]
Can you please share with us some more details about your issue in order to help you ? Also seems like you have some Javascript errors in there. A screenshot with your console would really help.

**Comment by Djas2017** [comment]
Thanks for the followup.

I have tried in another web server and this works very well without any modification. 
I didn't have the time to investigate further to see what is causing the issue in the first server.
