### ISSUE TITLE
Bootstrap 4 Compatibility

### ISSUE THREAD

**Issue by harunthuo** [puikinsh/gentelella#743]
Hi guys 

I see there's a  **Gentelella-Bootstrap-4** branch. 

So i installed the package using npm, imported the script and js(I'm using laravel's mix webpack)

in my _resources/assets/sass/app.scss_

`@import '~gentelella/build/css/custom.css';`

and in my _resources/assets/js/bootstrap.js_

`require('gentelella');`

but i still don't get the desired layout:

![bootstrap 4 incompatibility](https://user-images.githubusercontent.com/6682734/45915259-d84c1900-be5a-11e8-8d2e-de1ebd59f931.png)

Laravel 5.6 runs on Bootstrap 4 so looks like the Bootstrap 4 work for the package is not yet done?

**Comment by William-H-M** [comment]
Hi, Well it hasn't been announced by the main developers, so I guess it not done yet, you should wait until they officially announce it, at least you want to fix some of the errors on the layouts and contribute those to the branch.

**Comment by sannysoni123** [comment]
Gentelella-Bootstrap-4Hi I used bootstrap 3.3.7 Gentelella. but i need to move on and upgrade to bootstrap 4.

**Comment by cristianraiber** [comment]
@sannysoni123 - you might want to check this out: https://github.com/ColorlibHQ/gentelella/tree/Gentelella-BS4

**Comment by sannysoni123** [comment]
> @sannysoni123 - you might want to check this out: https://github.com/ColorlibHQ/gentelella/tree/Gentelella-BS4

thanks @cristianraiber.. thanks a lot.
