### ISSUE TITLE
use it with wordpress?

### ISSUE THREAD

**Issue by Jamen1147** [puikinsh/gentelella#764]
Can this be used with wordpress actually? I've integrated gentelella into my wordpress site and everything looks fine, but the sidebar is not working unfortunately. It seems that it's not active, I mean it shows up but when I click the items on the sidebar, there is just no response and there is also no response when I clicked the collapse btn on the nav bar. 

I've believe that I followed the instruction very strictly, so does it mean that it is not suitable using this with wordpress? Sorry for asking questions like this.

**Comment by puikinsh** [comment]
It can be used with WordPress if you have the skills to convert it. It is an HTML template with no dependence to some platform.
