### ISSUE TITLE
Hide / show chevron-up / down

### ISSUE THREAD

**Issue by tcaron** [puikinsh/gentelella#78]
Hello guys, first, thank for this theme, it's awesome.

I have a little problem. when i click on the chevron nothing happened but everything else working ..

http://puu.sh/ogte0/753404f7de.png

i use it on symfony2

here the js files that i use
`   {% block javascripts %}
                <script type="text/javascript" src="{{ asset ('Gintelella/js/jquery.min.js')}}"></script>
                <script type="text/javascript" src="{{ asset ('Gintelella/js/custom.js')}}"></script>
	   			<script type="text/javascript" src="{{ asset ('Gintelella/js/bootstrap.min.js')}}"></script>
				<script	type="text/javascript" src="{{ asset ('Gintelella/js/icheck/icheck.min.js')}}"></script>
				<script type="text/javascript" src="{{ asset ('Gintelella/js/pace/pace.min.js')}}"></script>
				<script type="text/javascript" src="{{ asset ('Gintelella/js/progressbar/bootstrap-progressbar.min.js') }}"></script>
				<script type="text/javascript" src="{{ asset ('Gintelella/js/nicescroll/jquery.nicescroll.min.js') }}"></script>
	   			<script type="text/javascript" src="{{ asset ('Gintelella/js/nprogress.js') }}"></script>
   {% endblock %}`

thank u

**Comment by wesleykaoru** [comment]
Are there any error messages in console?

**Comment by tcaron** [comment]
nothing, everything working except this :/

**Comment by christianesperar** [comment]
Do you have the class **collapse-link** on your link. It must be:
<li>
    <a class="collapse-link">
        <i class="fa fa-chevron-up"></i>
    </a>
</li>

**Comment by tcaron** [comment]
thanks for the answer and the update

http://puu.sh/oiTpH/5ce7d0e261.png
 i think i have the correct link and when i click on the chevron-up, the class changed to chevron-down, but the content doesn't hide

**Comment by christianesperar** [comment]
Do you have class x_content on your box div?

**Comment by tcaron** [comment]
http://puu.sh/oiUQh/313fdf052f.png

Yes, maybe this is the consequence of bad html structure of my part ?

**Comment by christianesperar** [comment]
It must be x_content and not x-content. Classes naming will revise soon.

**Comment by tcaron** [comment]
ahhhhhhh thanks my friend, that's work like a charm :')

**Comment by christianesperar** [comment]
Please close this.
