### ISSUE TITLE
Different button colors

### ISSUE THREAD

**Issue by PatrikHudak** [puikinsh/gentelella#82]
It seems that there is an inconsistency between demo page and actual repo. 

From my observations:

_.btn-primary_ and _.btn-success_ have default bootstrap colors in the repo. However, on the demo page, these colors are customized to match overall color scheme. I think that this was caused by upgrading Bootstrap from 3.3.2 to 3.3.6. Hover colors are set correctly.

Screenshots for better clarity:

Currect repo
![2016-04-15-16-37-47](https://cloud.githubusercontent.com/assets/6135225/14564879/c6a384e4-0328-11e6-8fb9-f83a0d49dc18.png)

[Demo page](https://colorlib.com/polygon/gentelella/form_buttons.html)
![2016-04-15-16-38-09](https://cloud.githubusercontent.com/assets/6135225/14564880/c6a48fba-0328-11e6-8ce1-7085a26f4a85.png)

Thanks.

**Comment by caipeichao** [comment]
Demo:
![image](https://cloud.githubusercontent.com/assets/1661871/14584833/d8420264-048d-11e6-920d-c3049ad05875.png)

Repo:
![image](https://cloud.githubusercontent.com/assets/1661871/14584835/e136e128-048d-11e6-9a90-6a25f8ff62b4.png)

**Comment by christianesperar** [comment]
I realign button on the theme design on PR https://github.com/puikinsh/gentelella/pull/84

**Comment by PatrikHudak** [comment]
Closing
