### ISSUE TITLE
bower components

### ISSUE THREAD

**Issue by huglester** [puikinsh/gentelella#90]
Hello

did you think about installing all the dependencies via bower.json?
that way it would be much easier to keep up to date versions on the dependencies, etc.

Thank you

**Comment by christianesperar** [comment]
Yup, this will be available on future release.

**Comment by huglester** [comment]
thank you very much. I think you can then close this issue, or others for reading:)

**Comment by rrussell** [comment]
good feature !

**Comment by christianesperar** [comment]
Already put some libraries to bower on pr https://github.com/puikinsh/gentelella/pull/102
