### ISSUE TITLE
Sidebar nav, default open

### ISSUE THREAD

**Issue by huglester** [puikinsh/gentelella#91]
Hello,

is there a way, to make sidebar navigation, show for example 'Home' group opened, then you enter the admin area?

Also for example have: Home > Testimonials
then I am in Testimonials - it keeps sidebar opened, but when I press EDIT on some of the items, sidebar closes, and I see only main groups, and I need to click arrow, to show group items again

Thank you

**Comment by christianesperar** [comment]
Do you mean when you click outside the menu bar, the menu that is open will close?

**Comment by christianesperar** [comment]
Is this solve? Please reopen it not.
