### ISSUE TITLE
Side-menu Bug

### ISSUE THREAD

**Issue by georgewoofbates** [puikinsh/gentelella#97]
When using this template with php I am running into a problem.

When I set a page in the side-menu to the file name index.php and then use a get form to reload the page with get info in the url (e.g. index.php?name=bob) the side menu no longer automatically adds the active class to the current page.

**Comment by georgewoofbates** [comment]
SOLVED: Just added the first line in custom.js to this:

`var URL = window.location.href.split('?')[0],`

**Comment by christianesperar** [comment]
Thanks, this fix is now on master. PR is https://github.com/puikinsh/gentelella/pull/111
